### ISSUE TITLE
simpleclient_hotspot should not depend on simpleclient_servlet

### ISSUE THREAD

**Issue by zimmi** [prometheus/client_java#103]
It seems like the dependency is not necessary.
I use the simpleclient together with [undertow core](https://github.com/undertow-io/undertow) without servlets, so this is a mild inconvenience.

Right now I do something like this:

```xml
<dependency>
    <groupId>io.prometheus</groupId>
    <artifactId>simpleclient_hotspot</artifactId>
    <version>${prometheus.version}</version>
    <exclusions>
        <exclusion>
            <groupId>io.prometheus</groupId>
            <artifactId>simpleclient_servlet</artifactId>
        </exclusion>
    </exclusions>
</dependency>
```

**Comment by brian-brazil** [comment]
Thanks for pointing this out, I'm surprised this wasn't caught sooner. Would you like to send a PR?

**Comment by zimmi** [comment]
I've never done that before, but I'll try. Thanks for asking, I feel honored. :)
I hope I'll have time on the weekend, maybe sooner.

**Comment by brian-brazil** [comment]
Looks like this slipped in in #74
