### ISSUE TITLE
Wrong type for Dropwizard Metrics Counter?

### ISSUE THREAD

**Issue by joschi** [prometheus/client_java#115]
The Javadoc comment for [`DropwizardExports#fromCounter(String, Counter)`](https://github.com/prometheus/client_java/blob/parent-0.0.14/simpleclient_dropwizard/src/main/java/io/prometheus/client/dropwizard/DropwizardExports.java#L27-L34) says "Export counter as prometheus counter" but the actual metric type being used is [Gauge](https://prometheus.io/docs/concepts/metric_types/#gauge).

Either the Javadoc comment is wrong or the implementation is using the wrong [Prometheus metric type](https://prometheus.io/docs/concepts/metric_types/).

**Comment by brian-brazil** [comment]
The comment is incorrect.

Dropwizard counters aren't counters, as they can be decremented. Would you like to send a PR?

**Comment by joschi** [comment]
@brian-brazil Sure, there you are: #116.
