### ISSUE TITLE
[prometheus-metrics-exposition-formats] Consider making protobuf optional

### ISSUE THREAD

**Issue by AB-xdev** [prometheus/client_java#1173]
Context:
I'm using Spring Boot and as [metrics implementation for actuator](https://docs.spring.io/spring-boot/reference/actuator/metrics.html#actuator.metrics.getting-started) ``micrometer-registry-prometheus`` which then uses ``prometheus-metrics-exposition-formats``

While inspecting our final built jar I noticed that your dependency is shipped with protobuf which is rather big (when compared to the rest):
![](https://github.com/user-attachments/assets/f171d2f4-62d1-4e86-ba67-f82e4ddc5d3f)

I'm also not actively using protobuf and therefore it would be great if this could somehow be excluded.

It's also noted in the docs that protobuf is somewhat [obsolete/experimental](https://github.com/prometheus/docs/blob/main/content/docs/instrumenting/exposition_formats.md#protobuf-format) so shipping this by default is maybe not needed in the first place.

**Comment by AB-xdev** [comment]
Another extrem good example why it's not wise to ship all dependencies (that are likely barely used) by default and use a more modulare approach:
https://github.com/protocolbuffers/protobuf/security/advisories/GHSA-735f-pc8j-v9w8

**Comment by AB-xdev** [comment]
For now we create a "workaround" project: https://github.com/xdev-software/prometheus-metrics-exposition-formats-no-protobuf

**Comment by AB-xdev** [comment]
Also:
In https://github.com/prometheus/client_java/commit/c9bb30bd361870ff412c1d817c41f573e457670e protobuf is now directly shaded into ``prometheus-metrics-exposition-formats`` and it can no longer be ignored -.-
I think it would be good to reverted this.

**Comment by AB-xdev** [comment]
Overview:
![](https://github.com/user-attachments/assets/68d12a68-b440-4417-99c2-f62ee2fd3e1d)

**Comment by fstab** [comment]
Thanks for reporting. Just a quick heads-up: @zeitlinger is the best person to answer this, but he's out this week, so it will likely take until next week before we can respond.
