### ISSUE TITLE
Global labels

### ISSUE THREAD

**Issue by Gouthamve** [prometheus/client_java#121]
Hi,

I want to add a label to all the metrics exposed. Just like prometheus appends instance label to all the metrics of a client, I want to add it at the client level.

For example I want to add **env=test** to all the metrics. Is it possible? If its not possible, would you a accept a PR?

Thanks,
Goutham.

**Comment by brian-brazil** [comment]
That's an anti-pattern, target labels should be provided at the Prometheus level via relabelling rather than from clients or exporters.

**Comment by Gouthamve** [comment]
Thanks! This might solve half my use case. Can you point me to some examples of relabelling_config?

But take the case of **env=beta/qa/prod**, in a dynamic environment such as AWS, its impossible to have static relabelling config. How do you propose I fix this?

**Comment by brian-brazil** [comment]
You can use EC2 tags for example to determine you labels. See http://www.robustperception.io/automatically-monitoring-ec2-instances/

**Comment by Gouthamve** [comment]
Well, that is out of the window! We are using tags for everything and as a result the tags API is throttled when we are spinning up machines rapidly. We are currently implementing the SD as a hack for now and will move to consul soon.

Hmm, I think I will make a wrapper over the Prometheus collectors that would automatically insert such info. Hope moving to consul will fix most of the issues of the peculiar use-case we have.

Thanks!

**Comment by brian-brazil** [comment]
Consul tags are a list rather than key/value so while you can use them with relabelling it's a bit more difficult.
