### ISSUE TITLE
Change in dependency visibility in a patch change

### ISSUE THREAD

**Issue by jack-berg** [prometheus/client_java#1219]
Transitive dependencies and their scope changed in a patch release. Was this intentional?

[prometheus-metrics-exporter-common-1.3.3.pom](https://repo1.maven.org/maven2/io/prometheus/prometheus-metrics-exporter-common/1.3.3/prometheus-metrics-exporter-common-1.3.3.pom) included:

```
<dependencies>
  <dependency>
    <groupId>io.prometheus</groupId>
    <artifactId>prometheus-metrics-model</artifactId>
    <version>${project.version}</version>
  </dependency>
  <dependency>
    <groupId>io.prometheus</groupId>
    <artifactId>prometheus-metrics-exposition-formats</artifactId>
    <version>${project.version}</version>
  </dependency>
</dependencies>
```

[/prometheus-metrics-exporter-common-1.3.4.pom](https://repo1.maven.org/maven2/io/prometheus/prometheus-metrics-exporter-common/1.3.4/prometheus-metrics-exporter-common-1.3.4.pom) included:

```
<dependencies>
  <dependency>
    <groupId>io.prometheus</groupId>
    <artifactId>prometheus-metrics-model</artifactId>
    <version>${project.version}</version>
  </dependency>
  <dependency>
    <groupId>io.prometheus</groupId>
    <artifactId>prometheus-metrics-exposition-textformats</artifactId>
    <version>${project.version}</version>
  </dependency>
  <dependency>
    <groupId>io.prometheus</groupId>
    <artifactId>prometheus-metrics-exposition-formats</artifactId>
    <version>${project.version}</version>
    <scope>runtime</scope>
  </dependency>
</dependencies>
```

Changes:
- `prometheus-metrics-exposition-formats` was reduced to scope `runtime`. 
- `prometheus-metrics-exposition-textformats` was added

This required me to intervene when updating. Not a big deal, but wanted to let you all know in case you have a policy to avoid this type of thing.

**Comment by zeitlinger** [comment]
Thanks for the feedback!

Yes, this was intentional - the [make Protobuf optional](https://prometheus.github.io/client_java/exporters/formats/#exclude-protobuf-exposition-format) part of https://github.com/prometheus/client_java/releases/tag/v1.3.4

We want to avoid breaking changes whenever possible (but there's no automated check for this) - can you point out what you had to change.

**Comment by zeitlinger** [comment]
Thanks for feedback - I think I'm OK with keeping it the way it is.
