### ISSUE TITLE
Async for Pushgateway

### ISSUE THREAD

**Issue by korrawit** [prometheus/client_java#123]
Hi,

Currently, I'm using push model to submit metric from App to Prometheus.

I have concern that now client using synchronous http model which has impact to application latency.

Is that possible for java client to connect to Pushgateway via http async model?

So, there is will be less impact to application.

Thanks,

**Comment by brian-brazil** [comment]
I'm not sure I understand your use case. The pushgateway is intended for batch jobs and would usually only be pushed to at the end of the job, in which case you definitely want sync.

**Comment by korrawit** [comment]
@brian-brazil I might misuse Prometheus. Actually my use case is about transaction application. I have put code to push metric to pushgateway at the end of all transaction. Metric about how many success/fail for last 5 minute. It's working fine so far.

Am I misuse it ? Please suggest.

Thanks,

**Comment by brian-brazil** [comment]
You should use normal instrumentation and have Prometheus scrape your applications.

**Comment by korrawit** [comment]
@brian-brazil Could you please elaborate the reason?

Thanks,

**Comment by brian-brazil** [comment]
What you're doing sounds like online serving rather than batch, thus there's no need to use the pushgateway.
