### ISSUE TITLE
Source files without license headers

### ISSUE THREAD

**Issue by puntogil** [prometheus/client_java#127]
Hi
The following source files are without license headers:

./benchmark/src/main/java/io/prometheus/benchmark/CounterBenchmark.java
./benchmark/src/main/java/io/prometheus/benchmark/GaugeBenchmark.java
./benchmark/src/main/java/io/prometheus/benchmark/SummaryBenchmark.java

./simpleclient/src/main/java/io/prometheus/client/Collector.java
./simpleclient/src/main/java/io/prometheus/client/CollectorRegistry.java
./simpleclient/src/main/java/io/prometheus/client/Counter.java
./simpleclient/src/main/java/io/prometheus/client/Gauge.java
./simpleclient/src/main/java/io/prometheus/client/Histogram.java
./simpleclient/src/main/java/io/prometheus/client/SimpleCollector.java
./simpleclient/src/main/java/io/prometheus/client/Summary.java

./simpleclient/src/test/java/io/prometheus/client/CollectorRegistryTest.java
./simpleclient/src/test/java/io/prometheus/client/CounterTest.java
./simpleclient/src/test/java/io/prometheus/client/GaugeTest.java
./simpleclient/src/test/java/io/prometheus/client/HistogramTest.java
./simpleclient/src/test/java/io/prometheus/client/SimpleCollectorTest.java
./simpleclient/src/test/java/io/prometheus/client/SummaryTest.java

./simpleclient_common/src/main/java/io/prometheus/client/exporter/common/TextFormat.java
./simpleclient_common/src/test/java/io/prometheus/client/exporter/common/TextFormatTest.java

./simpleclient_dropwizard/src/main/java/io/prometheus/client/dropwizard/DropwizardExports.java
./simpleclient_dropwizard/src/test/java/io/prometheus/client/dropwizard/DropwizardExportsTest.java

./simpleclient_graphite_bridge/src/main/java/io/prometheus/client/bridge/Graphite.java
./simpleclient_graphite_bridge/src/test/java/io/prometheus/client/bridge/GraphiteTest.java

./simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot/DefaultExports.java
./simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot/GarbageCollectorExports.java
./simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot/MemoryPoolsExports.java
./simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot/StandardExports.java
./simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot/ThreadExports.java

./simpleclient_hotspot/src/test/java/io/prometheus/client/hotspot/ExampleExporter.java
./simpleclient_hotspot/src/test/java/io/prometheus/client/hotspot/GarbageCollectorExportsTest.java
./simpleclient_hotspot/src/test/java/io/prometheus/client/hotspot/MemoryPoolsExportsTest.java
./simpleclient_hotspot/src/test/java/io/prometheus/client/hotspot/StandardExportsTest.java
./simpleclient_hotspot/src/test/java/io/prometheus/client/hotspot/ThreadExportsTest.java

./simpleclient_log4j/src/main/java/io/prometheus/client/log4j/InstrumentedAppender.java
./simpleclient_log4j/src/test/java/io/prometheus/client/log4j/InstrumentedAppenderTest.java

./simpleclient_logback/src/main/java/io/prometheus/client/logback/InstrumentedAppender.java
./simpleclient_logback/src/test/java/io/prometheus/client/logback/InstrumentedAppenderTest.java

./simpleclient_pushgateway/src/main/java/io/prometheus/client/exporter/PushGateway.java
./simpleclient_pushgateway/src/test/java/io/prometheus/client/exporter/ExamplePushGateway.java
./simpleclient_pushgateway/src/test/java/io/prometheus/client/exporter/PushGatewayTest.java

./simpleclient_servlet/src/main/java/io/prometheus/client/exporter/MetricsServlet.java
./simpleclient_servlet/src/test/java/io/prometheus/client/exporter/ExampleExporter.java

Please, confirm the licensing of code and/or content/s, and add license headers
https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Clarification

Thanks in advance
Regards

**Comment by brian-brazil** [comment]
Per the top-level LICENSE file, these are all Apache 2.0. DoubleAdder and Striped64 are the only files from elsehwhere, and they were public domain.
