### ISSUE TITLE
Make source / javadoc jars available through maven repo

### ISSUE THREAD

**Issue by ddewaele** [prometheus/client_java#131]
Would help debugging...

**Comment by brian-brazil** [comment]
They are available: https://repo1.maven.org/maven2/io/prometheus/simpleclient/0.0.15/

**Comment by ddewaele** [comment]
I was on a snapshot version. Are the snapshot sources also available in a public maven repo ?

**Comment by brian-brazil** [comment]
I have no idea, I'd advise against using snapshot versions as you don't know what code you're using.
