### ISSUE TITLE
Improve documentation/README and add examples.

### ISSUE THREAD

**Issue by oliver006** [prometheus/client_java#133]
I recently had the pleasure to instrument an old Java app and I found it hard to get started as the docs are missing examples.
The README has a large part on the maintenance of the library which isn't really helpful for most people that are just looking for a few simple copy-pastable snippets of code, the docs for the python library[1] is a lot better in this regard.

[1] https://github.com/prometheus/client_python

**Comment by brian-brazil** [comment]
The docs are in javadoc, which you can find at https://prometheus.io/client_java/

**Comment by oliver006** [comment]
Yeah, I eventually found that link but it also doesn't give a good, tutorial style instructions about how to get started with instrumenting my app. All the relevant information is hidden with the respective classes and not easily found.
I also found it lacking with with information about the `client.hotspot` package, it's not quite clear what e.g. the difference is between `StandardExports` and `DefaultExports`.

**Comment by oliver006** [comment]
Let me see if I can find some time in the next few days to get a better README doc cobbled together.

**Comment by oneiros-de** [comment]
The home page says "There are canonical examples defined in the class definition Javadoc of the client packages." - this might be true for _some_ packages, but e.g. the log4j and the jetty package have _zero_ javadoc.

**Comment by checketts** [comment]
I'm interested in taking this on. @oliver006 Do you have any in-flight work you would like me to build on?

**Comment by oliver006** [comment]
Hey @checketts - I started making changes, in particular I moved examples to the README so users can find them faster (similar to the docs of the Python client).
You can find them here: https://github.com/oliver006/client_java/tree/oh_improve_readme 

Please feel free to go ahead and re-use them or discard them as you see fit, I'm a bit pressed for time these days and won't be able to get to this any time soon.

**Comment by checketts** [comment]
@oliver006 Thanks for the response. I did a spike last night. (https://github.com/checketts/client_java/tree/readme)

If you don't mind commenting on #182 if anything appears to be missing I'll be happy to tackle it. (I understand if you are too short on time)

**Comment by oliver006** [comment]
Had a brief look, I really like what you did there!
