### ISSUE TITLE
Optional timestamp

### ISSUE THREAD

**Issue by feheraron** [prometheus/client_java#135]
Is it planned to support the 'optional timestamp' feature? 
E.g. Get Prometheus to use explicitly the pushed timestamp instead of the scraping time.

More on this:
https://docs.google.com/document/d/1ZjyKiKxZV83VI9ZKAXRGKaUKK2BIWCT7oiGBKDBpjEY

Cheers,

Aron

**Comment by brian-brazil** [comment]
Almost every person looking for this feature was going to use it incorrectly, so there's no plans to add it until https://github.com/prometheus/prometheus/issues/398 is resolved.

**Comment by feheraron** [comment]
Just read through the referenced discussions.
Though our usecase is different I get your point. Let's close this.

Thanks for the immediate reply.

**Comment by paphillon** [comment]
@brian-brazil - Since the dependent prometheus/prometheus#398 seems to be resolved, is there any plans to implement this? This feature will be helpful in cases of proxying metrics.
