### ISSUE TITLE
Expose /prometheus as a Spring Boot Mgmt Endpoint

### ISSUE THREAD

**Issue by eliezio** [prometheus/client_java#139]
I missed a simpleclient submodule that creates a Spring Boot Management Endpoint to expose the prometheus metrics. 
The existing simpleclient_servlet module requires additional glue-code to accomplish this task.

**Comment by eliezio** [comment]
Can I contribute with a new module based on the implementation drawn at
http://blog.monkey.codes/actuator-and-prometheus/?

**Comment by maust** [comment]
+1 (with an Spring-style annotation like @EnablePrometheusEndpoint would be nice)

**Comment by ovelindstrom** [comment]
+1

**Comment by maust** [comment]
Here is a starting point if somebody wants to use prometheus with spring boot: https://github.com/maust/prometheus-spring-boot

**Comment by sdomula** [comment]
I tried out the implementation of @maust. It works well.

**Comment by brian-brazil** [comment]
If someone sends a PR I'm willing to merge.

**Comment by eliezio** [comment]
Feature released on v0.0.18
