### ISSUE TITLE
Deprecate and/or rename push and pushAdd

### ISSUE THREAD

**Issue by turb** [prometheus/client_java#145]
Following #137 and #138, `push` and `pushAll` have been reversed.

We were using `push` in the way that was working, but not according to the documentation, obviously. After upgrade (we should have checked the changelog...), we spent some time figuring out why some metrics were nullified, and then changed it to `pushAll`.

However, any Prometheus java client user will have its Prometheus fail silently just by upgrading the library. It should be nice to rename and/or deprecate both methods instead in order to force developers to acknowledge this change. As it as been pointed out, those names are confusing.

Maybe only have one `push` method with a mandatory param `overrideWholeGroup` or `fullGroup`?

**Comment by brian-brazil** [comment]
The naming is the standard naming for a Prometheus client, however the initial implementation in the Java client got them the wrong way around. The bug fix was clearly flagged in the release notes.

> However, any Prometheus java client user will have its Prometheus fail silently just by upgrading the library. 

I'd expect most users not to be affected, as touching all metrics is usual.

**Comment by scoobyjah** [comment]
Just jumping in as a new prometheus user with a slight bit of confusion. I can't find any mention of a pushAll as mentioned above. When pushing metrics with the same name but different labels, the behaviour of the client is to replace any metric with that name, ignoring labels, is that correct? Is it not part of the purpose of prometheus labels to be able to query on them?

**Comment by brian-brazil** [comment]
He meant pushAdd.

> When pushing metrics with the same name but different labels, the behaviour of the client is to replace any metric with that name, ignoring labels, is that correct?

Yes, though within the grouping labels.

>  Is it not part of the purpose of prometheus labels to be able to query on them?

It is, I don't see how this relates to your question though.

**Comment by scoobyjah** [comment]
I think you've cleared my confusion, thanks. There was a misunderstanding of how grouping keys are meant to correlate with labels.
