### ISSUE TITLE
How can I use this in my own project?

### ISSUE THREAD

**Issue by liujiawinds** [prometheus/client_java#153]
I know how to use maven and import prometheus components into my project.
But I don't know what's next and how to expose my metrics to prometheus?
Do you have a guide reference ?
Thanks.

**Comment by brian-brazil** [comment]
See https://www.robustperception.io/instrumenting-java-with-prometheus/

**Comment by liujiawinds** [comment]
I have a lot of applications. Must have a http server to scrape metrics info for each application ?

**Comment by brian-brazil** [comment]
Yes. This is something it's best to put in your core/base libraries so that it only needs to be done once.

**Comment by email2liyang** [comment]
@brian-brazil  for the example you give https://www.robustperception.io/instrumenting-java-with-prometheus/ and https://github.com/prometheus/client_java/blob/master/simpleclient_servlet/src/main/java/io/prometheus/client/exporter/MetricsServlet.java

why the counter not get reset after /metrics is accessed? 

let's say we have x access at time point "a", then /metrics is scraped, then we got y access from time point "a" to time point "b" , and at time point "b" /metrics is scraped again. without counter reset, the counter value will be x+y, but it should be y times of access during time point "a" and time point "b"

**Comment by brian-brazil** [comment]
It's that way for resilience and to allow for multiple scrapers. See https://www.robustperception.io/how-does-a-prometheus-counter-work/

**Comment by email2liyang** [comment]
@brian-brazil ,thanks for the info
