### ISSUE TITLE
Getting started with spring-boot and prometheus

### ISSUE THREAD

**Issue by andrewrutter** [prometheus/client_java#156]
I am looking to expose metrics from a set of spring-boot services to prometheus but I guess I am missing some steps to bring the two together. I have the following in my pom:
```
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <!-- The client -->
        <dependency>
            <groupId>io.prometheus</groupId>
            <artifactId>simpleclient</artifactId>
            <version>0.0.18</version>
        </dependency>
        <!-- Hotspot JVM metrics-->
        <dependency>
            <groupId>io.prometheus</groupId>
            <artifactId>simpleclient_hotspot</artifactId>
            <version>0.0.18</version>
        </dependency>
        <!-- Exposition servlet-->
        <dependency>
            <groupId>io.prometheus</groupId>
            <artifactId>simpleclient_servlet</artifactId>
            <version>0.0.18</version>
        </dependency>
        <!-- Pushgateway exposition-->
        <dependency>
            <groupId>io.prometheus</groupId>
            <artifactId>simpleclient_pushgateway</artifactId>
            <version>0.0.18</version>
        </dependency>
        <dependency>
            <groupId>io.prometheus</groupId>
            <artifactId>simpleclient_spring_boot</artifactId>
            <version>0.0.18</version>
        </dependency>        
```
and have added the annotation from the javadocs to my main class:
```

    @EnablePrometheusEndpoint
    public class Application {

	public Application() {
	}

	public static void main(String[] args) {
		SpringApplication.run(Application.class, args);
	}
    }

```

If I run the application and navigate to any of the actuator endpoints I see metrics being reported back. The /prometheus endpoint is returning a 200 but has no additional content. Is tere something else I need to do in order to bridge to the metrics from actuator or even to get the basic hotspot metrics out?

Thanks in advance, Andrew

**Comment by Eloo** [comment]
Hi, 
you may need to add
`@EnableSpringBootMetricsCollector`
?
Regards
Eloo

**Comment by andrewrutter** [comment]
Thanks, simply annotated my main class as follows and its working like a charm
```
@EnablePrometheusEndpoint
@EnableSpringBootMetricsCollector
```

**Comment by johnrremitly** [comment]
FWIW, I continued to have an empty response after including both annotations (and all required dependencies). My issue was that I was not using the management port, and hadn't set the default server port to allow access to sensitive endpoints.

You can check if this is your issue by enabling access sensitive endpoints from your default server port by setting the following in your spring properties:

.properties:
```
management.security.enabled=false
```
or 

yaml:
```
management:
  security:
    enabled: false
```

It's not necessarily advised to allow access to all of these endpoints, but if this solves your problem, you can look into the proper way to expose the necessary endpoints.

:v:

**Comment by jlar310** [comment]
Late to the party, but I landed here while trying to solve the prometheus security problem. So I will add that if you use

```
endpoint:
  prometheus:
    sensitive: false
```
Then you don't have to disable security on all actuator endpoints.
