### ISSUE TITLE
Spring Boot improvements

### ISSUE THREAD

**Issue by pidster** [prometheus/client_java#158]
The Spring Boot support could be improved in the following ways:

- Use AutoConfiguration, so just adding the jar to the classpath is enough to launch the actuator classes
- Add a single `@EnablePrometheus` annotation, with parameters to enable/disable other configuration
- Use `@ConditionalXXX` to override the auto-configuration classes, where users would need to customise things
- Expose the common collector/exporters

I think there may be more opportunities, but if there's an interest in doing this I'll provide a PR for review.

**Comment by arnostv** [comment]
If you are going to work on Spring Boot integration,  I'd also suggest improving documentation a bit. For example to me it was not even clear if Spring Boot support we have right now is trying to:

- expose Prometheus metric in Spring Boot way - i.e. `GET host/metrics` shows JSON and will include Prometheus counters, timers, ...
- expose Spring metrics on Prometheus - i.e. `GET host/prometheus` shows metrics in text format and it will include some additional metrics from Spring Boot
- it just allows Spring Boot application to show only Prometheus metrics using Prometheus text format

Maybe all of those options?

**Comment by brian-brazil** [comment]
In terms of documentation for this repo generally, I'm considering doing similar to the python client and having examples in the README.md. While all our docs are currently in java doc, which classes are relevant is no longer really organically discoverable as the number of modules have grown.

**Comment by pidster** [comment]
@arnostv We could certainly make it more specific.

`GET host/metrics` will hit the standard Spring Boot 'metrics actuator' endpoint, it doesn't know about Prometheus stuff.

**Comment by pidster** [comment]
I will open a separate issue for improvements to docs after the above PR is reviewed.

**Comment by arockiaraj1994** [comment]
@arnostv worked fine for me, bit struggle to find the solution. It would be great if place in documentation 

Thanks
