### ISSUE TITLE
Dropwizard metrics missing in Prometheus

### ISSUE THREAD

**Issue by peking2** [prometheus/client_java#166]
Hello

I'm exporting Dropwizard metrics to Prometheus by using the following code, but I'm seeing some metrics are missing in Prometheus as below. Is it a known issue? Anyway to solve it?

Code:
        CollectorRegistry collectorRegistry = new CollectorRegistry();
        collectorRegistry.register(new DropwizardExports(environment.metrics()));
        environment.admin()
                .addServlet("prometheusMetrics", new MetricsServlet(collectorRegistry))
                .addMapping("/metrics");

Dropwizard Metrics:
{
count: 0,
max: 0,
mean: 0,
min: 0,
p50: 0,
p75: 0,
p95: 0,
p98: 0,
p99: 0,
p999: 0,
stddev: 0,
**m15_rate: 0,
m1_rate: 0,
m5_rate: 0,**
mean_rate: 0,
duration_units: "seconds",
rate_units: "calls/second"
}

Prometheus Metrics:
{quantile="0.5",} 0.0
{quantile="0.75",} 0.0
{quantile="0.95",} 0.0
{quantile="0.98",} 0.0
{quantile="0.99",} 0.0
{quantile="0.999",} 0.0
count 0.0

Thanks

**Comment by brian-brazil** [comment]
This is by design, you can calculate these more accurately using the `rate` function on the count.

**Comment by oker1** [comment]
While I agree on the rates, the min,max,mean values can't be calculated for a timer and they could be useful.

**Comment by brian-brazil** [comment]
min and max can't generally be calculated. Mean can be correctly calculated, however Dropwizard doesn't expose the information required to do so. Use a Prometheus Summary if you want that.

**Comment by oker1** [comment]
I'd rather have these metrics than replace Dropwizard, so is there a chance these metrics could be added with an optional flag?

**Comment by brian-brazil** [comment]
That's not likely to happen.

The DW integration is only indented as a tool for transition, while you're switching over to the Prometheus java client.
