### ISSUE TITLE
Add JVM deadlock metrics

### ISSUE THREAD

**Issue by davidkarlsen** [prometheus/client_java#169]
dropwizard JVM monitoring has support for "Breakdown of thread states, including deadlocks": http://metrics.dropwizard.io/3.1.0/manual/jvm/
else prometheus is on par with dropwizard metrics - I prefer using prometheus - if this gap could be closed it would be great.

**Comment by brian-brazil** [comment]
Feel free to send a pull request adding it to the hotspot stats.
