### ISSUE TITLE
use maven wrapper for build

### ISSUE THREAD

**Issue by pjfanning** [prometheus/client_java#180]
Travis CI supports an old version of Maven and they recommend using Maven Wrapper to allow builds to control which version of Maven is installed and used for the build. This pattern is used in Gradle builds a lot (gradlew).

https://github.com/travis-ci/travis-ci/issues/4872
https://github.com/takari/maven-wrapper

**Comment by pjfanning** [comment]
@brian-brazil I can implement this, if it makes sense - it should be pretty trivial

**Comment by pjfanning** [comment]
https://github.com/pjfanning/client_java/commit/3c4363a9af9e2ed6e092548a83b4340592a657a3

**Comment by brian-brazil** [comment]
I can't see it hurting if you'd like to send the PR
