### ISSUE TITLE
Metrics Servlet has a potential resource leak

### ISSUE THREAD

**Issue by iggyzap** [prometheus/client_java#190]
Hi,

I've found recently that Jboss server has run out of available file descriptors and all file descriptors were consumed by connections in CLOSE_WAIT state from JMX prometheus exporter to prometheus server.

I believe that only possible source of leaked descriptor in the following code: https://github.com/prometheus/client_java/blob/master/simpleclient_servlet/src/main/java/io/prometheus/client/exporter/MetricsServlet.java#L40

There print writer is not flushed  / closed and left to GC / jetty if an exception happens.

**Comment by pjfanning** [comment]
This can be closed

**Comment by iggyzap** [comment]
Agree, it's up to Jetty to correctly handle rest.
