### ISSUE TITLE
Too Many Modules? Should modlues be combined ie `simpleclient_logging`?

### ISSUE THREAD

**Issue by checketts** [prometheus/client_java#191]
I'm considering adding some support for Guava cache metrics.  Following the current convention we see a new module for each new sub-set of support. (`simpleclient_log4j` and `simpleclient_logback` as examples)

Would it make sense to have a `simpleclient_caches` module that uses `optional` dependencies for each different implementations (Guava, Caffeine, EhCache, etc.) or is it acceptable to continue adding fine-grained modules?

**Comment by brian-brazil** [comment]
Fine-grained modules are best I think. No point in creating more dependency hell than we have to.
