### ISSUE TITLE
Roadmap for 1.0

### ISSUE THREAD

**Issue by checketts** [prometheus/client_java#203]
I'm finding the Prometheus Java Client to be very useful and adding many custom collectors as needed.  Is there a roadmap or list of ideas that need attention?

The client already feels pretty robust and it is a little surprising that the version number is `0.0.20` right now. 

Similar to Prometheus' overall roadmap: https://prometheus.io/docs/introduction/roadmap/ are there any particular parts of the Prometheus Java Client that I could work on, review, or submit PRs?

Items that have my interest and that I am aware of:

- Improving Spring boot integration (making it integrate fully with Spring boot Actuator, likely by working with upstream)
- Instrumentation for Threadpools/Executors
- Ehcache/Redis/Memcached client instrumentation
- RabbitMQ instrumentation (likely with upstream)

These are all usecases that apply to applications I'm using. 

Are there any higher priority items or overall roadmap efforts that I could contribute to?

**Comment by brian-brazil** [comment]
The main thing from my standpoint is finishing off the ?name[]= support, and possibly adding a parser.

Integrations are handy, but don't affect the core.

**Comment by checketts** [comment]
By `?name[]=` support, do you mean for the endpoint `\metrics?name[]=` the ability to filter requested metrics as a parameter for that endpoint? I would be happy to start an issue and matching PR for the servlet/spring/vert.x endpoints.

I suppose a ProtoBuf output option would also be needed?

I don't know much about parsers though so I won't be too much help there.

**Comment by brian-brazil** [comment]
> the ability to filter requested metrics as a parameter for that endpoint?

Yes. See how it's done in Python.

> I suppose a ProtoBuf output option would also be needed? (As a separate issue)

That's not required.

> I don't know much about parsers though so I won't be too much help there.

It's a matter of porting the Python one.

**Comment by brian-brazil** [comment]
At this point I think there's largely just some cleanup to be done, as post 1.0 we shouldn't be doing breaking changes. For example DropwizardExports should be DropwizardCollector.

**Comment by brian-brazil** [comment]
I'm not explicitly tracking a 1.0 now, and there's still OpenMetrics at least to be sorted.
