### ISSUE TITLE
plugin

### ISSUE THREAD

**Issue by kfox1111** [prometheus/client_java#206]
I have an existing Jetty based web service that I would like to dynamically slide in the jetty module to. Is there any way to do that? If not, could there be?

**Comment by brian-brazil** [comment]
Can you expand on what you're trying to do?

The presumption is that you have access to the source and can change your code to include whatever bits of the client you need.

**Comment by kfox1111** [comment]
Yeah. that presumption is the problem I'm facing and asking for a fix for. I do have access to the source, but I'm an op more then a dev and get my prebuilt binaries from an upstream distro. I don't want to rebuild everything and have to maintain the fork just to add some slight monitoring functionality, but rather tweak a few config files and slide in a plugin. Maybe there is another java/prometheus plugin I'm looking for instead?

**Comment by brian-brazil** [comment]
It sounds like you're looking for the jmx exporter, as if the code isn't already instrumented with a Prometheus client then exposing it via jetty isn't going to help you much.

**Comment by kfox1111** [comment]
ok. I'll have a closer look at the jmx exporter. Thanks for the pointer. I'm just looking to get basic jetty usage statics out of the process and this java client mentioned jetty and the jmx exporter didn't mention it.

**Comment by brian-brazil** [comment]
If you want jetty stats, you need to add direct instrumentation yourself. Jetty does not provide stats in any form out of the box as far as I'm aware.

**Comment by kfox1111** [comment]
Could it be built as a plugin though rather then need to be compiled in? I was interested in https://github.com/prometheus/client_java/blob/master/simpleclient_jetty/src/main/java/io/prometheus/client/jetty/JettyStatisticsCollector.java  as it seems to gather the interesting bits.

**Comment by brian-brazil** [comment]
You could try to write a java agent to do that, but it'd be far simpler to change the code.
