### ISSUE TITLE
SpringBoot client error

### ISSUE THREAD

**Issue by kk-manh** [prometheus/client_java#207]
Hi,
Prometheus is unable to parse data exposed by the spring boot client library
I see the following error in the status page : 
text format parsing error in line 187: second HELP line for metric name "gauge_servo_response_prometheus"

Any ideas...

**Comment by brian-brazil** [comment]
That's likely the servo library exposing the same metric twice, which isn't permitted by the semantics of either spring boot or Prometheus.

**Comment by kk-manh** [comment]
Here is the sample code I am using :

`public class ControllerMetricsHandler
{

    @Autowired
    GaugeService gaugeService;

    @Autowired
    CounterService counterService;

    private Map<String, QueueMetric> metrics = new ConcurrentHashMap<>();

    public ControllerMetricsHandler()
    {

        for (int i = 0; i < 50; i++)
        {

            QueueMetric q = new QueueMetric();
            q.setQueueName("queue_" + i);
            metrics.put(q.getQueueName(), q);
        }

    }

    @Scheduled(fixedDelay = 5000)
    public void onQueueStatus()
    {

        metrics.keySet().forEach(queueName -> {

            QueueMetric qm = metrics.get(queueName);

            gaugeService.submit("controller_" + queueName + "_queue_depth", qm.getQueueDepth());
            gaugeService.submit("controller_" + queueName + "_consumers", qm.getConsumers());
            gaugeService.submit("controller_" + queueName + "_queue_publishrate", qm.getPublishRatePerSecond());
        });
    }
}`

**Comment by brian-brazil** [comment]
I'm not an expert in spring boot. All I can recommend is to use the prometheus java client directly, as it's designed to work with Prometheus and has label support which the current version of spring doesn't.

**Comment by kk-manh** [comment]
Ok.. So this is really not a spring boot actuator compatible exporter at all...
Sorry to say , but the name of the package is completely misleading.

**Comment by brian-brazil** [comment]
It is compatible with spring boot, however the modules you're using are sending spring boot bad data. You need to file a bug with the module authors to get it fixed.

**Comment by kk-manh** [comment]
So then your sample test SpringBootMetricsCollectorTest.java , clearly wont work with Prometheus....and as per the Spring cloud team , they have updated their documentation asking implementors to ensure uniqueuness of labels and metrics

**Comment by Eloo** [comment]
Can confirm this issue. I'm facing the same problem :/

**Comment by ezraroi** [comment]
Add this to your yml file:
```
spring.metrics.servo.enabled: false
```

And it will solve your problem.. the duplicate metrics will not be reported anymore

**Comment by kk-manh** [comment]
@ezraroi  Thanks for the tip.

Meanwhile I wrote a custom exporter to export spring boot actuator metrics to prometheus format without using the prometheus java client library. This keeps me shielded from any custom APIs.

**Comment by Eloo** [comment]
@kk-manh would you mind to share your exporter? :)
