### ISSUE TITLE
Timer example is misleading

### ISSUE THREAD

**Issue by lmlynik** [prometheus/client_java#209]
In https://github.com/prometheus/client_java/blob/parent-0.0.21/simpleclient/src/main/java/io/prometheus/client/SimpleTimer.java#L30

The line with observing is misleading, the timer is called during observation. I think it should be the counter, also what supposed to be the value for the label? Is it the same as the label defined at Timer itself or that label with `Value` suffixed?

**Comment by checketts** [comment]
Oops good point. 

`requestTimer.labels("aLabelValue").observe(requestTimer.elapsedSeconds());` is wrong it whouls be the `Summary` (requestLatency)

as in
`requestLatency.labels("aLabelValue").observe(requestTimer.elapsedSeconds());`
