### ISSUE TITLE
simpleclient_spring_web is no available in Maven Central

### ISSUE THREAD

**Issue by fedy2** [prometheus/client_java#219]
Looks like simpleclient_spring_web is not available in Maven Central:
http://search.maven.org/#search%7Cga%7C1%7Csimpleclient_spring_web

**Comment by brian-brazil** [comment]
There hasn't been a release yet that included it.

**Comment by fedy2** [comment]
Update the doc please: https://github.com/prometheus/client_java#spring-aop

**Comment by zlangbert** [comment]
I was also confused by this. Any eta on `simpleclient_spring_web`?

**Comment by lminot** [comment]
Same here any, ETA
