### ISSUE TITLE
Java client incorrectly flushes metric labels to pushgateway when -Dfile.encoding != UTF-8

### ISSUE THREAD

**Issue by fedotxxl** [prometheus/client_java#222]
1. Start application with -Dfile.encoding=cp1251
2. Created counter with label 'Привет мир!'
3. Check :9091/metrics

Looks like the problem is https://github.com/prometheus/client_java/blob/master/simpleclient_pushgateway/src/main/java/io/prometheus/client/exporter/PushGateway.java#L257 :

```
new BufferedWriter(new OutputStreamWriter(connection.getOutputStream()))
```

I think encoding should be forced to UTF-8

**Comment by brian-brazil** [comment]
This should probably be fixed down in TextFormat. Would you like to send a PR?
