### ISSUE TITLE
Global metrics prefix using spring boot client

### ISSUE THREAD

**Issue by holgerstolzenberg** [prometheus/client_java#224]
I am not quite sure if this is an issue or if I miss some configuration thing here. Consider following situation (simplified):

Deploying spring-boot app `app1`, you will get a  uptime gauge at
`http://app1:$port/$context-path/prometheus/uptime`

Deploying a second spring-boot app `app2`, you will get a  another uptime gauge at
`http://app2:$port/$context-path/prometheus/uptime`

Now when I access the prometheus server to have a look at the "Uptime" metrics graph, I only can see one metric "uptime".
* From which app is it coming?
* Is that only a shortcoming of the server UI that can be overcome using Grafana?
* Do I miss something about scrape config?

Does it make sense to introduce some kind of global configurable app prefix, so that prometheus metrics would sanitise to `http://app:$port/$context-path/prometheus/app_uptime` for example?

**Comment by brian-brazil** [comment]
This sounds like your Prometheus is misconfigured, and you're somehow ending up with the two targets clashing (or aren't in fact scraping the 2nd app at all). Usage questions are best asked at https://groups.google.com/forum/#!forum/prometheus-users

> Does it make sense to introduce some kind of global configurable app prefix, so that prometheus metrics would sanitise

That's considered an anti-pattern, this is what labels are for.
