### ISSUE TITLE
[Q] What is the best practice for healthchecks

### ISSUE THREAD

**Issue by agentgt** [prometheus/client_java#235]
We are in the process of possibly converting from Dropwizard Metrics to Prometheus.

Dropwizard Metrics have essentially what is a special boolean metric of health/unhealthy but they are separate from all the other metrics. 

Healthchecks in the Dropwizard world are analogous to production unit tests.

I assume the way to convert these over to Prometheus would be to have them as a gauge or something else?

**Comment by checketts** [comment]
If the intent is to alert on them via Prometheus, I think a Gauge that returns `failing_heath_check{check="checkName"}` and a count of the failures is a good start. You even could iterate through your HealthChecks as a custom collector to build that number.

That being said, Prometheus lets us expose the underlying metric that helps determine the health instead. So you can move the health check from a boolean to expose that actual underlying metric that failed.

**Comment by brian-brazil** [comment]
The real question is what sort of health check you're doing and why, as each has its own approaches (very few of which would involve Prometheus).  As this is more a usage question, https://groups.google.com/forum/#!aboutgroup/prometheus-users is the best place for it.
