### ISSUE TITLE
Instrumenting org.eclipse.jetty.util.thread.QueuedThreadPool 

### ISSUE THREAD

**Issue by cenkakin** [prometheus/client_java#242]
Hi,

I think it would be very beneficial if we can get metrics for org.eclipse.jetty.util.thread.QueuedThreadPool in addition to io.prometheus.client.jetty.JettyStatisticsCollector. What do you think about that? 

Thanks in advance.

**Comment by brian-brazil** [comment]
That sounds fine, would you like to send a PR?

I'd suggest looking at the hibernate module as an example.
