### ISSUE TITLE
DropwizardExports exposes Meter as Counter and ignores mean & 1m/5m/15m EWMA values

### ISSUE THREAD

**Issue by jonfreedman** [prometheus/client_java#245]
I think [DropwizardExports#fromMeter](https://github.com/prometheus/client_java/blob/master/simpleclient_dropwizard/src/main/java/io/prometheus/client/dropwizard/DropwizardExports.java#L107) should export 5 metrics not 1, the mean rate + 1min, 5min & 15min rates in addition to the total.

The main rationale for this is that if someone has made the decision to use a dropwizard [Meter](http://metrics.dropwizard.io/3.2.2/manual/core.html#man-core-meters) instead of a [Counter](http://metrics.dropwizard.io/3.2.2/manual/core.html#man-core-counters) they definitely care about those values and may not care about the total at all.

**Comment by brian-brazil** [comment]
This behaviour is correct, we calculate these on the Prometheus side from the total with the `rate()` function..
