### ISSUE TITLE
Extract Interfaces for CollectorRegistry and Samples

### ISSUE THREAD

**Issue by checketts** [prometheus/client_java#249]
In contributing to https://github.com/spring-projects/spring-metrics I'm attempting to make it simpler to register metrics in a way that mirrors that library's api. (Primarily the `compute if absent` approach where the user calls to retrieve a metric and it is created/registered if it doesn't already exist)

I realize that the prometheus `simple_client` is written with a very different approach, so instead of trying to fight it, I wanted to create my own implementation of a registry that has a simpler/more forgiving behavior.

Would a PR be acceptable to extract interfaces for `CollectorRegistry`, `MetricFamilySamples` and `MetricFamilySamples.Sample`?

**Comment by brian-brazil** [comment]
> Primarily the compute if absent approach where the user calls to retrieve a metric and it is created/registered if it doesn't already exist

This is considered an anti-pattern both performance wise and semantically.

Create your metrics as static final fields.

**Comment by checketts** [comment]
That is good advice for applications. (And frankly that is the design choice that library made that I'm not in control of). I'm trying to make it easier for libraries to be able to expose Prometheus metrics, and I'm also trying to avoid the anti-pattern of coding against concrete classes instead of interfaces.

Are you opposed to me creating `interface`s for the classes mentioned above?

**Comment by brian-brazil** [comment]
All applications are fundamentally libraries, which should use static fields. Is there some particular technical reason that wouldn't work?

I'm opposed to this if this is what you're trying to use it for.

**Comment by checketts** [comment]
I'm not saying usage will depart from using static fields. But I'm also saying that isn't my call in that library.

My current concern is that I'm seeing the project hack around the current limitation by just wrapping the existing Prometheus library. Note how the [Gauge](https://github.com/spring-projects/spring-metrics/blob/master/src/main/java/org/springframework/metrics/instrument/prometheus/PrometheusGauge.java#L22) is being wrapped in this class.

I wanted to improve their implementation by using interfaces on their classes so the wrapping was minimized. I don't know that I'll be able to improve that Gauge exactly, but as they are adding parts that are similar to Prometheus' custom `Collector`s, I wanted to try to leverage interfaces to minimize the wrapping.

A recent example is [this PR](https://github.com/spring-projects/spring-metrics/pull/33/files#diff-36d62c1dc3633301d0f4051c94bfa7edR50) that tries to create a `MeterReporter` which ends up exporting metrics, then reconverting them again for the purpose of sending to the CollectorRegistry.

**Comment by brian-brazil** [comment]
My stance having seen this style of code in the past is to avoid all wrapping, and use the client library directly. 

I've never seen any abstraction over an instrumentation library to work out. In my experience they only serve to frustrate usage, debugging and maintenance while losing key features.

The problem here is in the decision to wrap, not how the java client is implemented.

**Comment by checketts** [comment]
> All applications are fundamentally libraries

That assertion ignores that fact that a team writing an application can choose their metrics platform, but a library needs to be flexible

> use the client library directly

How can a library do that and still be able to report to Spectator, DataDog, or Prometheus depending on the user's needs?

> I've never seen any abstraction over an instrumentation library to work out...

I understand your skepticism. That is exactly why I'm trying to contribute to the Spring Metrics because I don't want to end up with a sub-par slice of metrics.

**Comment by brian-brazil** [comment]
> That assertion ignores that fact that a team writing an application can choose their metrics platform, but a library needs to be flexible

That's something I've not seen work. The design of instrumentation clients tend to end up being pretty tightly bound to what's on the other side (for example Dropwizard seems to be designed with the presumption that the other end can't do math) - so if you need to support multiple paradigms you're usually best using all of the respective instrumentation systems for each.

> How can a library do that and still be able to report to Spectator, DataDog, or Prometheus depending on the user's needs?

The Prometheus answer is that instrumentation and exposition are two different things. So you instrument with Prometheus, and then you can expose out to whatever monitoring system you want on the other end. This is why simpleclient_graphite is included with this library and also the Python/Go clients, to serve as a simple example of writing out to a non-Prometheus monitoring system

The Prometheus model/paradigm is sufficiently sophisticated/simple that you can almost always get a good conversion to another paradigm. I know a company using Prometheus that has it talking out to Datadog for example.

> I understand your skepticism. That is exactly why I'm trying to contribute to the Spring Metrics because I don't want to end up with a sub-par slice of metrics.

This is a bit more than skepticism, I've seen this sort of thing many times before. It's one of my major pet peeves.

I would recommend that end users use the client library directly, but there's often scope for a few custom collectors or utilities to make things easier for users of a particular framework.

**Comment by checketts** [comment]
> The Prometheus answer is that instrumentation and exposition are two different things

Yes! And that is why I want these interfaces to hook into the exposition. 

Granted the approach is slightly different in this case since I only want to use the `simple_client`'s exposition libraries, but that is my goal: remove the code wrapping and allow the code in `spring-metrics` to write out to their internal representations. 

The limitations I ran into in `TextFormat` are with the usage of internal fields like `.name` and `.help` force me to instantiate the `MetricFamilySamples` classes instead of exposing the existing fields:
```java
Collector.MetricFamilySamples metricFamilySamples = mfs.nextElement();
      writer.write("# HELP ");
      writer.write(metricFamilySamples.name);
      writer.write(' ');
      writeEscapedHelp(writer, metricFamilySamples.help);
```

I reget bringing up the `CollectorRegistry` and`Collector` classes since that is distracting from the core thing I want to solve, though it would be nice for all to be interfaces.

**Comment by brian-brazil** [comment]
> Yes! And that is why I want these interfaces to hook into the exposition.

The interface for that is `CollectorRegistry.metricFamilySamples`

What you've asked for is a hook into the instrumentation API, which is a different beast.

What you want is a custom collector, which is the standard way to get data from a non-Prometheus instrumentation system into the registry.
