### ISSUE TITLE
[Dropwizard] Invalid type for Gauge 

### ISSUE THREAD

**Issue by vanDonselaar** [prometheus/client_java#250]
The client doesn't know how to handle the default Dropwizard metrics that are registered by Dropwizard.

```
DEBUG Invalid type for Gauge jvm_threads_deadlocks: java.util.Collections$EmptySet
DEBUG Invalid type for Gauge jvm_attribute_vendor: java.lang.String
DEBUG Invalid type for Gauge jvm_attribute_name: java.lang.String
```

**Comment by brian-brazil** [comment]
I tested this just last week and it worked fine. Can you share your code and module versions?

Also, nothing is registered by default with Dropwizard metrics.

**Comment by brian-brazil** [comment]
I've not heard back not this and there's no other reports, so I'm going to presume this was a usage issue and close for now.
