### ISSUE TITLE
Pushgateway module doesn't support SSL

### ISSUE THREAD

**Issue by swsnider** [prometheus/client_java#258]
Pushgateway URL is hard-coded to use 'http', which prevents it from working in our environment.

**Comment by theneva** [comment]
This is solved by using the constructor if/when #257 is merged!

**Comment by robachmann** [comment]
Looking forward to a release with this change and HTTPS support.

**Comment by sanjaychandak** [comment]
I am using 0.0.23 with Spring Boot 1.5.4.RELEASE but still I get the java.lang.NullPointerException: null
	at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.includedCollectorIterator(CollectorRegistry.java:148)

Which version has this issue been fixed?

**Comment by robachmann** [comment]
I think we just have to wait until @brian-brazil releases a new version.

**Comment by brian-brazil** [comment]
I'm waiting on #267 before doing a release.
