### ISSUE TITLE
Line 43 of TextFormat is wrong - always appends a comma to labelNames

### ISSUE THREAD

**Issue by alexp700** [prometheus/client_java#262]
As I see it, it always adds a comma to the list of labelNames, so this isn't parsed correctly by prometheus, or am I doing it wrong?

Thanks,

Alex

**Comment by checketts** [comment]
That is intentional.

**Comment by brian-brazil** [comment]
Make sure you're using the latest version of the python parser or prometheus, whichever it is you're using.

**Comment by alexp700** [comment]
I am using 1.7 - so almost the latest (when I started).

**Comment by yuanman** [comment]
my prometheus version is 2.0.0, can not scrape the metric. the log is "no token found". 
Default lablename is this format? have comma in the end?  like this  --> info_size{type="o",} 679.0

**Comment by checketts** [comment]
@yuanman The trailing comma is expected and not . I suspect you have a metric name with a hyphen in it. That is not allowed since it can be mistaken for a subtraction sign.
