### ISSUE TITLE
[minor] JettyStatisticsCollector: most metrics should probably be counters

### ISSUE THREAD

**Issue by mpartel** [prometheus/client_java#263]
It looks like most (but not all) of the metrics in [JettyStatisticsCollector](https://github.com/prometheus/client_java/blob/master/simpleclient_jetty/src/main/java/io/prometheus/client/jetty/JettyStatisticsCollector.java) should be counters rather than gauges.

**Comment by brian-brazil** [comment]
I had just noticed that over on #247

**Comment by brian-brazil** [comment]
This is fixed now.
