### ISSUE TITLE
Metrics Endpoint in Spring Boot responds with 406 if called with Accept: text/plain

### ISSUE THREAD

**Issue by predic8** [prometheus/client_java#265]
I have a Spring Boot project with the following dependency:

```
<dependency>
  <groupId>io.prometheus</groupId>
  <artifactId>simpleclient_spring_boot</artifactId>
  <version>0.0.23</version>
</dependency>
```

The following call works and returns the metrics despite the wrong MIME type.

`curl http://localhost:8080/prometheus -v -H "Accept: application/json"`

However using text/plain it does not work:

```
$ curl http://localhost:8080/prometheus -v -H "Accept: text/plain"                                                                                                                                                            
> GET /prometheus HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.51.0
> Accept: text/plain
>
< HTTP/1.1 406 Not Acceptable
< Date: Wed, 21 Jun 2017 09:08:33 GMT
< X-Application-Context: application
< Cache-Control: must-revalidate,no-cache,no-store
< Content-Length: 0
```

Unfortunately prometheus can not be tweaked to send the wrong Accept header.

I tried several Spring Boot versions and I also included the JSON libraries. The following demo project has the same problem:

https://github.com/njanor/spring-boot-prometheus-demo

**Comment by predic8** [comment]
PR with fix:

https://github.com/prometheus/client_java/pull/267

**Comment by massenz** [comment]
:+1: 
Does anyone know whether there's a workaround?

**Comment by massenz** [comment]
As far as I can tell this has been fixed in the `0.0.24` release - thanks, everyone!

**Comment by MCoulombe727** [comment]
I'm facing the same issue. I tried multiple versions of simpleclient_spring_boot and I still receive 406 when trying to access the prometheus metrics endpoint, is there a workaround?

**Comment by MCoulombe727** [comment]
For the record, a misconfiguration in our spring applications removed all the HttpMessageConverter except jackson for json so out app was unable to produce a text/plain response that Prometheus expects.
