### ISSUE TITLE
Regression bug in 0.0.23 ?

### ISSUE THREAD

**Issue by merlijntishauser** [prometheus/client_java#266]
Hi, 

The /prometheus endpoint encapsulates the response in quotes. This was fixed in 0.0.22, but has returned now in the latest version.

**Comment by brian-brazil** [comment]
Which module is this?

**Comment by martijnvdgrift** [comment]
io.prometheus:simpleclient:0.0.23

**Comment by brian-brazil** [comment]
That's the instrumentation client, it doesn't do HTTP. Which exposition module are you using?

**Comment by mbode** [comment]
Might be related to #267?

**Comment by brian-brazil** [comment]
I believe this is fixed now, if not please let us know.
