### ISSUE TITLE
Implementing interceptor for collecting data from Spring RestTemplate

### ISSUE THREAD

**Issue by cenkakin** [prometheus/client_java#268]
I think it would be very useful if prometheus serves us Spring RestTemplate metrics. What do you think about adding that to simpleclient_spring_web module? 

Thanks in advance,

**Comment by brian-brazil** [comment]
From a quick peek, doing something via ClientHttpRequestInterceptor would make sense.

**Comment by cenkakin** [comment]
Yes, I think so too. I have already implemented something. I will send a PR as soon as possible.

**Comment by brian-brazil** [comment]
It turns out that we can't get at the non-interpolated URL, so this wouldn't be much use. Instrumentation of this needs to be at a different level.
