### ISSUE TITLE
Histogram returning wrong values

### ISSUE THREAD

**Issue by pofuk** [prometheus/client_java#270]
Histogram is returning wrong values.

What i would expect from histogram:
**Bin**	  |             **Count**
0.5 to 1.49 |	132
1.5 to 2.49 |	34
2.5 to 3.49 |	4

What i get:
**Bin**	      |         **Count**
less then 1.49 |	        132
less then 2.49	|          34+132
less then 3.49	 |          4+34+132

Problematic code:
io.prometheus.client.Histogram.Child::get
```
 double[] buckets = new double[cumulativeCounts.length];
      double acc = 0;
      for (int i = 0; i < cumulativeCounts.length; ++i) {
        acc += cumulativeCounts[i].sum();
        buckets[i] = acc;
      }
      return new Value(sum.sum(), buckets);
```

**should be:**
 ```
double[] buckets = new double[cumulativeCounts.length];
      double acc = 0;
      for (int i = 0; i < cumulativeCounts.length; ++i) {
        buckets[i] = cumulativeCounts[i].sum();
      }
      return new Value(sum.sum(), buckets);
```
Am i missing the point here?

**Comment by brian-brazil** [comment]
This behaviour is correct, Prometheus histograms are exposed cumulatively.

**Comment by pofuk** [comment]
Then this is not histogram, rather should be called cumulative frequency?

http://www.s-cool.co.uk/a-level/maths/representation-of-data/revise-it/histograms-and-cumulative-frequency
