### ISSUE TITLE
Duplicate metrics

### ISSUE THREAD

**Issue by ewolff** [prometheus/client_java#271]
I just published an update to the project https://github.com/ewolff/microservice-consul . It basically a simple sample application to show microservices and Consul. Now I added Prometheus. However, some metrics were duplicated so I did a hack https://github.com/ewolff/microservice-consul/blob/master/microservice-consul-demo/microservice-consul-demo-order/src/main/java/com/ewolff/microservice/order/prometheus/MetricsServletFix.java . This resolves the issue. `gauge_servo_response_health` and `gauge_servo_response_prometheus` were examples. Upon startup there were no duplicates. So it happened after the `/health` or `/prometheus` Endpoint were accessed.

I tried to implement a minimal version to make it easier to reproduce but that seems to be hard. I.e. https://github.com/thomasdarimont/spring-boot-prometheus-example doesn't have that problem. So maybe I did something stupid but I am not sure what.

**Comment by brian-brazil** [comment]
This usually means you registered the same metric twice somewhere, with newer versions of the client you'll get an error at registration time if that happens. What client version are you on, and where are these metrics coming from?

**Comment by ewolff** [comment]
I am using 0.0.23. I just have one single `SpringBootMetricsCollector` similar to the sample and to what it says in the documentation. I have no idea how a metric could be registered twice.

Upon startup the metrics mentioned do not exist. They are created once specific endpoints are accessed. So there might be a problem in that code. But the endpoints are created by Spring Boot Actuator. Therefore the problem has to be either in Spring Boot or the Prometheus client IMHO - unless I did something stupid.

**Comment by brian-brazil** [comment]
Ah, this is likely a bug in whatever is producing those Spring metrics as a few modules are known to have duplicates (including servo). I'd suggest filing a bug with servo. See #130

**Comment by ewolff** [comment]
Ah, thanks - that sounds a lot like my problem. I didn't look hard enough :-)
