### ISSUE TITLE
simpleclient_spring_boot depends on spring-boot-starter-web now?

### ISSUE THREAD

**Issue by atrepczik** [prometheus/client_java#274]
In the most recent release of simpleclient, Spring Boot dependencies have been updated. Along with that it seems spring-boot-starter-web has become a compile time dependency whereas it previously has been test-scoped. Is this on purpose? It builds just fine without.

https://github.com/prometheus/client_java/compare/parent-0.0.23...parent-0.0.24#diff-b809dadb2515a75f45862ca6818b38b5L106

**Comment by brian-brazil** [comment]
That looks like a mistake, would you like to send a PR readding the scope?

**Comment by atrepczik** [comment]
Sure, I will create a PR shortly.
