### ISSUE TITLE
Metric and label names should be checked for validity

### ISSUE THREAD

**Issue by juliusv** [prometheus/client_java#28]
Reporting this because users placed a dash into a metric name, which was then not queriable via Prometheus (the query language cannot tell a dash/minus apart).

The client library should check that metric and label names are valid ones that can be queried through the query language later (and we should add the same check upon ingestion in Prometheus):

Metric names have to adhere to this regex:

- `[a-zA-Z_:]([a-zA-Z0-9_:])*`

Similarly, label names need need to adhere to this one (basically, no colons allowed):

- `[a-zA-Z_]([a-zA-Z0-9_])*`

There are currently no restrictions on label values.

**Comment by awesomescot** [comment]
If there are no colons allowed in labels, then using the ec2 exporter how are we to access tags like this: aws:cloudformation:stack-name?  These are quite common if you use cloudformation at all.  Is there any work around for this?

**Comment by brian-brazil** [comment]
Such values are sanitized by the cloudwatch exporter, so that should all work fine.

**Comment by pingleig** [comment]
Sorry for digging up old issue, in case someone found this via google and wonder how the label name is sanitized 

https://github.com/prometheus/cloudwatch_exporter/blob/78bb98e34e6f5cacc3a0e17a3f7e7686b458711a/src/main/java/io/prometheus/cloudwatch/CloudWatchCollector.java#L520-L528

```java
private String safeName(String s) {
  // Change invalid chars to underscore, and merge underscores.
  return s.replaceAll("[^a-zA-Z0-9:_]", "_").replaceAll("__+", "_");
}

private String safeLabelName(String s) {
  // Change invalid chars to underscore, and merge underscores.
  return s.replaceAll("[^a-zA-Z0-9_]", "_").replaceAll("__+", "_");
}
```
