### ISSUE TITLE
Duplicate JettyStatisticsCollector classes with different contents

### ISSUE THREAD

**Issue by davidkarlsen** [prometheus/client_java#280]
See:  https://groups.google.com/forum/#!topic/prometheus-developers/YOru7A2LCwY

The simpleclient_jetty and the simpleclient_jetty_jdk8 contain the same class in the same package - but with different code - additionally the class in the jdk8 is not under sourcecontrol when checking github.

**Comment by brian-brazil** [comment]
This is something weird Maven is doing, a clean client produces this too.
