### ISSUE TITLE
public Configuration class or starter prometheus config

### ISSUE THREAD

**Issue by poppop0911** [prometheus/client_java#284]
should public below two class, then Configuration by self
1. PrometheusMetricsConfiguration 
2. PrometheusEndpointConfiguration

```
@Configuration
@Import({ PrometheusMetricsConfiguration.class, PrometheusEndpointConfiguration.class })
public class PrometheusConfig {

}
```

or starter prometheus config，Prometheus client  endpoint auto starter 
Enable*  style is not better than starter

**Comment by brian-brazil** [comment]
I have no idea what you are asking here. Can you expand?

**Comment by poppop0911** [comment]
We need to use the prometheus client in many MicroServices in many projects, using Enable * annotations will be intrusive to the application, we hope that the same as spring-boot-starter-actuator's  AutoConfiguration, not need  Enable *  make Configuration effect.

**Comment by poppop0911** [comment]
or public below two class,

PrometheusMetricsConfiguration
PrometheusEndpointConfiguration

we can autoConfiguration by self  through  META-INF/spring.provides

**Comment by checketts** [comment]
So you are just requesting that the 2 classes be made `public` so you can leverage Spring autoconfiguration instead of requiring the `@EnablePrometheus` line of code.

I agree with that approach.

Where would you be adding the `META-INF/spring.factories`? Would that be in your own code?  (I'm not familiar with `provides`)

**Comment by poppop0911** [comment]
Yes,  _public_ 2 classes for make autoconfiguration by self 

[Creating your own auto-configuration](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-developing-auto-configuration.html
)

[spring-boot-custom-starter example/](https://github.com/thomasdarimont/spring-boot-custom-starter-example/tree/master/spring-boot-hello-starter)
