### ISSUE TITLE
missing HistogramMetricFamily

### ISSUE THREAD

**Issue by dams** [prometheus/client_java#285]
The HistogramMetricFamily is mentioned in the documentation (see https://github.com/prometheus/client_java/blame/master/README.md#L625 ) but it seems that it was never implemented, as I can't find the class anywhere. Am I missing something ? Is it not yet implemented ? Thanks

**Comment by checketts** [comment]
Good catch. Looks like it was overlooked.

**Comment by brian-brazil** [comment]
The histogram metric is sufficiently complicated that a helper function would do basically nothing to reduce code complexity, thus it was not included.

**Comment by dams** [comment]
@brian-brazil I think it could still simplify things, like separate between normal labels and buckets, and would help make code more readable/balanced when dealing with various types of metrics

**Comment by brian-brazil** [comment]
Do you have an example of how it'd make it simpler?

I note that the need for histograms in custom collectors is quite rare, very few other systems produce histograms in a way compatible with what Prometheus uses.

**Comment by dams** [comment]
@brian-brazil I'm not an expert, but I thought that HistogramMetricFamily could generate the _bucket, _count, _sum timeseries, given a basename, buckets definitions, and values. But maybe it's not adding enough value compared with doing it manually.

I'm coding a kafka exporter to provide a prometheus endpoint from kafka messages. We forge them, so we make sure they are compatible with prometheus.

**Comment by brian-brazil** [comment]
You probably want a normal histogram for that.

**Comment by dams** [comment]
I'm building a custom collector (reads kafka messages, provides a prom endpoint), so I would need to go from having normal histograms to something that I can add to a MetricFamilySamples. How do I do that ?

**Comment by brian-brazil** [comment]
In the usual fashion, register the histogram.

**Comment by dams** [comment]
that's what my first implementation was doing, but I moved to using GaugeMetricFamily because of the documentation paragraph about proxying. Anyway I suggest that the doc at least removes the mention of HistogramMetricFamily, and at best is clearer on when to use MetricFamily directly

**Comment by brian-brazil** [comment]
But you're not proxying here, you're creating a new metric iirc.

**Comment by checketts** [comment]
The readme line mentioning the `HistogramMetricFamily` was a section I had copied from the Python client readme. Does Python have a `HistogramMetricFamily`? Or does it also need to remove that line from the readme?

**Comment by brian-brazil** [comment]
The Python client does, maps are easier to use in Python so a HistogramMetricFamily is useful there.
