### ISSUE TITLE
determine metric value at collect time

### ISSUE THREAD

**Issue by caarlos0** [prometheus/client_java#287]
in the client_go package, we can use [`prometheus.NewGaugeFunc(opts, function)`](https://godoc.org/github.com/prometheus/client_golang/prometheus#NewGaugeFunc) to create metrics which values are determined at collect time by the function passed to it.

Seems like client_java doesn't have this feature.

Is there a way of doing it? Any plans to implement it?

**Comment by brian-brazil** [comment]
See https://prometheus.io/client_java/io/prometheus/client/SimpleCollector.html#setChild-Child-java.lang.String...-

This is only briefly mentioned in the readme to reduce abuse, as most of the time you want a normal gauge.
