### ISSUE TITLE
Only write HELP and TYPE once per metric name

### ISSUE THREAD

**Issue by felixbarny** [prometheus/client_java#288]
If using the same metric name with different tags, the output of `TextFormat.write004` contains the `# HELP` and `# TYPE` comments more than once, leading to parsing errors.

See also https://github.com/stagemonitor/stagemonitor/issues/298.

The simplest solution would be to take track of metric names inside `TextFormat.write004` (via a Set) which already are commented.

**Comment by brian-brazil** [comment]
This is incorrect usage on your end you should only be returning a given metric once. Looking at that issue those should have different metric names rather than a type label.

**Comment by felixbarny** [comment]
Stagemonitor also produces lots of timers named `response_time`. These metrics have a `operation_name` tag which can be the URL or the controller method name, for example.

Examples:

```
response_time{operation_name="SearchController#searchItems"}
response_time{operation_name="ItemsController#showItem"}
```

How could I map that into prometheus if one metric names have to be unique?

**Comment by brian-brazil** [comment]
You need to gather them up into one metric in your collector. That metric should also have a unit such as seconds.

**Comment by felixbarny** [comment]
> You need to gather them up into one metric in your collector

I don't quite understand. How would that look like?

**Comment by brian-brazil** [comment]
The JMX exporter has an example, as it also needs to do that.

**Comment by felixbarny** [comment]
So you mean I have to append tags like operation_name to the metric name?

**Comment by giannello** [comment]
@felixbarny no, the `operation_name` should be a label, as it is now.
The metric name should be changed from `response_time` to `response_time_seconds`, and values must be provided in seconds. The requirements are defined at https://prometheus.io/docs/practices/naming/

**Comment by felixbarny** [comment]
Thx for the reply. But then I still have multiple metrics named `response_time_seconds`.

Based on the below statement I thought that was invalid?

> This is incorrect usage on your end you should only be returning a given metric once.

**Comment by giannello** [comment]
An example from the JMX exporter library:
```
# HELP jvm_memory_bytes_used Used bytes of a given JVM memory area.
# TYPE jvm_memory_bytes_used gauge
jvm_memory_bytes_used{area="heap",} 9.67254824E8
jvm_memory_bytes_used{area="nonheap",} 1.51896304E8
# HELP jvm_memory_bytes_committed Committed (bytes) of a given JVM memory area.
# TYPE jvm_memory_bytes_committed gauge
jvm_memory_bytes_committed{area="heap",} 8.371830784E9
jvm_memory_bytes_committed{area="nonheap",} 1.57331456E8
```
As you can see, metrics are defined once (HELP and TYPE are not repeated), but it's perfectly valid to have multiple lines with the same metric if the labels are different.

**Comment by felixbarny** [comment]
I think the problem is that `TextFormat.write004` doesn't ensure that `# HELP` and `# TYPE` is only printed once.

**Comment by brian-brazil** [comment]
No, the presumption is that if you're writing a custom collector that you know what you're doing.

**Comment by felixbarny** [comment]
Ok, I see. But it feels like there is a lot of duplicated code out there which is doing something like this:

```java
new MetricFamilySamples(name.getName(), metricNameAlreadyAdded ? null : Type.GAUGE, metricNameAlreadyAdded ? null : getHelpMessage(name, gauge), Collections.singletonList(sample))
```

Isn't that something that could be added to `TextFormat.write004` in order to reduce code duplication and to serve the principle of least astonishment?

**Comment by felixbarny** [comment]
It also seems like the Dropwizard exporter has a simmilar problem: https://github.com/prometheus/client_java/blob/master/simpleclient_dropwizard/src/main/java/io/prometheus/client/dropwizard/DropwizardExports.java#L45

If the same metric name is used multiple times, for example to do that:
```
jvm_memory_bytes_used{area="heap",} 9.67254824E8
jvm_memory_bytes_used{area="nonheap",} 1.51896304E8
```

It would end up with multiple `# HELP` and `# TYPE` lines.

**Comment by brian-brazil** [comment]
The dropwizard exporter does not have that problem, it doesn't support labels.

**Comment by felixbarny** [comment]
Well, the Dropwizard exporter does not have the problem as Dropwizard does not support tags. That's why the metric name is always unique.

**Comment by brian-brazil** [comment]
That's not something that's planned currently, at most we'd throw an exception in that case.

**Comment by felixbarny** [comment]
I could gladly provide a pull request for the de-duplication.

Although it is quite apparent to me that there must only be one `# HELP` and `# TYPE` line per metric name, I feel that it's quite strange that you have to call the MetricFamilySamples constructor with null values if it has already been called before:

```
new MetricFamilySamples("name1", Type.GAUGE, "help message", value1)
new MetricFamilySamples("name1", null, null, value1)
```

At least for me that's a quite surprising behavior as the second MetricFamilySample still is of type `GAUGE` not of type `null`.

Plus, it would be trivial in `TextFormat.write004` to de-duplicate.

**Comment by brian-brazil** [comment]
That is incorrect usage of MetricFamilySamples, you should only call it once with a given metric name. I'd suggest following the example in https://github.com/prometheus/client_java#custom-collectors rather than using that class directly.
