### ISSUE TITLE
The counter is broken

### ISSUE THREAD

**Issue by voronaam** [prometheus/client_java#294]
```
        // noLabels = Counter.build().name("nolabels").help("help").register(registry);
	long counter = 9200000000000000l;
	noLabels.inc(counter);
	for (int i = 0; i < 30; i++) {
		noLabels.inc();
		System.out.println(String.format("%32.0f", noLabels.get()));
	};
```

Expected output:
```
                9200000000000001
                9200000000000002
                9200000000000003
```

Actual output:
```
                9200000000000000
                9200000000000000
                9200000000000000
                9200000000000000
                9200000000000000
                9200000000000000
```

I think `AtomicLong` would be much better suited for a counter.

**Comment by checketts** [comment]
While using an atomic long could be more efficient in Java and specifically for a Counter, the Prometheus server treats all metrics as doubles and I'm guessing would likely lose the precision anyways. By making those assumptions Prometheus can be extremely consistent and efficient.

If a counter is measuring single events, that means it could be measuring 10,000 events every second for over 20,000 years and not begin to lose precision. If it is measuring other things like bytes processed (that increment at a higher rate) then it can still go for a very long time (and going at that high rate the individual precision likely doesn't matter).

**Comment by voronaam** [comment]
This came about in the internal review. I am concerned about the performance penalty, but the correctness is a more obvious issue.

We do not have any use cases suffering from the lost precision yet, but an end user may arrive to big numbers in a counter in a various ways:
- total time spent in certain code (DB query - after a few parallel long queries, the fast ones are not going to affect the count)
- total count of items retrieved from a backend (or their size, as you pointed out)
- number or size of items observed to be queued - once the queue is drained the small numbers observed are not going to affect the counter

Do you think it is possible to fix the Prometheus as well?

**Comment by checketts** [comment]
I can't speak to changing Prometheus itself, since I don't contribute to it. But I really doubt it. 

Also consider the recommendation by https://www.robustperception.io/who-wants-seconds/ regarding measuring time. Instead of measuring milliseconds or nanoseconds, using seconds allows leveraging the precision of the double and adding several orders of magnitude of capacity.

Lastly, keep in mind that Prometheus is not intended as a transactional tracking system. It is for metrics that are ephemeral. I think precision (at such high values) has a lower priority to speed, resiliency, and metric storage capacity. 

(I'm just a light contributor to this project, and not a core commiter on it or Prometheus itself. Perhaps their opinions differ from my own.)

**Comment by voronaam** [comment]
After reading the article you linked I think there is an even greater cause for concern. In my original code the units were milliseconds and adding integers requires a corner case to care about the loss of precisions. The article however suggests the use of seconds. So, 1ms call would be `0.001d`, which has some precision loss already. Adding this to the counter would lead to even easier way to see counter artefacts.

Interestingly enough, the article even provides a use case for it:

> I’ve seen an RPC system for which different uses had typical latencies ranging from nanoseconds to months

I just did a quick test and it only takes 10 month-long jobs to screw the precision for tracking new ns-long jobs. 10 `1month` jobs and a 1000 `1ns` jobs add to `25920000.000998` instead of `25920000.001`.

I do now know the use case the author talks about, but it is a great reason not to use `double` type for metrics.

**Comment by brian-brazil** [comment]
Prometheus uses float64s and there's no plans to change this.

The case you suggest is extremely unlikely in practice.

**Comment by voronaam** [comment]
Excuse me, are not you are the author of the blog post linked just couple of comments above? The one that talks about exactly that "extremely unlikely" case.

It puzzles me that you make a great case against using float64 and yet go ahead to use it.

**Comment by brian-brazil** [comment]
There are currently no plans to switch Prometheus to a type other than float64. This as it has already been discussed extensively, and it is working as it has been engineered to work.

**Comment by voronaam** [comment]
I would not call that "engineered".
