### ISSUE TITLE
Vertx MetricsHandler not usable with rx-version

### ISSUE THREAD

**Issue by MarWestermann** [prometheus/client_java#298]
Hi,
when I use the rxjava version of Router (io.vertx.rxjava.ext.web.Router) I cannot use the metricsHandler in that. because it expects a Handler<io.vertx.rxjava.ext.web.RoutingContext>

**Comment by brian-brazil** [comment]
What would you propose to fix this?

**Comment by MarWestermann** [comment]
we could have a rxified implementation of the handler with a io.vertx.rxjava.ext.web.RoutingContext param and delegate the call to the current handler method. Maybe extract that to an own file.
