### ISSUE TITLE
DropwizardExports throws NPE if gauge's value is null

### ISSUE THREAD

**Issue by DmitryLipiev** [prometheus/client_java#301]
**What did you do?**

Tried to export Dropwizard metrics

**What did you expect to see?**

A list of Prometheus metrics in my browser

**What did you see instead? Under which circumstances?**

Internal server error. Some of our gauge metrics are initialized to null, when DropwizardExports comes across them it throws NPE at line 54:
LOGGER.log(Level.FINE, String.format("Invalid type for Gauge %s: %s", name, obj.getClass().getName()));  

**Environment**

Ubuntu 16.04, Java8

* System information:

Linux 4.4.0-96-generic x86_64

**Comment by brian-brazil** [comment]
#352 should fix this.
