### ISSUE TITLE
DropwizardExports - export additional metrics from Timers

### ISSUE THREAD

**Issue by bhemar** [prometheus/client_java#308]
It would be very useful if DropwizardExports exports additional metrics from timers, like **JmxReporter** from drowizard library does.

Additional metrics should be:
* mean time
* max time
* min time 
* 1m,5m,15m rates

Here is the JmxReporter example:

![timers](https://user-images.githubusercontent.com/3889793/32456273-51bb51a2-c325-11e7-9636-84608f73acea.jpg)

If you agree with that, I can start working on pull request...

**Comment by brian-brazil** [comment]
These are excluded on purpose, see https://prometheus.io/docs/instrumenting/writing_exporters/#drop-less-useful-statistics
