### ISSUE TITLE
Unable to create custom endpoints while using HTTPServer classes.

### ISSUE THREAD

**Issue by srinivascodes** [prometheus/client_java#310]
HTTPServer class just provides 2 endpoints, which are, `/` and `/metrics`. I want to create more endpoints for my server, but while creating server for my app using HTTPServer(provided by prometheus client lib) I cannot create custom endpoints because there is no provision like **server.createContext("name of the endpoint", Name of the handler class)**. Kindly look into this issue or suggest some way to create custom endpoints while using simpleclient_HTTPServer library.

**Comment by brian-brazil** [comment]
The HTTPServer is intended to be a simple way to get up and running if you don't already have a http server of some form. If you need something more complex, you probably want the servlet.

**Comment by srinivascodes** [comment]
Suppose I have an endpoint `/info` and I want to use Counter metrics for counting the number of hits on that endpoint. Can you tell me how can I achieve this using HTTPServer classes? I tried many ways of doing it. One of the ways was to use a static nested class named **HTTPMetricHandler** but it is private. Let me know how can I achieve that using HTTPServer class.

**Comment by brian-brazil** [comment]
That's not the way this class is intended to be used. I'm afraid I can't help you with general Java programming questions.
