### ISSUE TITLE
Dangerous behavior with null label values

### ISSUE THREAD

**Issue by apesternikov** [prometheus/client_java#315]
SimpleCollector is trying to validate labels
- to match number of labels configured on .build()
- to be a non-null value.
In both cases it throws IllegalArgumentException.
(https://github.com/prometheus/client_java/blob/755ba6e89e75525ba5fab502b3014156d485f7a9/simpleclient/src/main/java/io/prometheus/client/SimpleCollector.java#L64)
It is probably ok for number of labels enforcing. Doing this for null values is extremely dangerous since it introduces RuntimeException at execution time in production if label value is dynamic. Unfortunately, our data model assumes null as legitimate empty value so instrumenting our code turns into a minefield experience - you don't really know when it blows in production.
Can we change the semantics and treat null label value as empty ""? If it is ok, I have the change ready for PR.
If empty value does not play well with prometheus data model, it is ok to ignore such metric update (with special global null metric counter maybe?). It is not ok to throw runtime exception in metric collection for otherwise legitimate value.
Any thoughts @brian-brazil ?

**Comment by brian-brazil** [comment]
Null is not a possible Prometheus label value, we only accept UTF-8 strings. The empty sting is not the same as null, and treating one as the other could create misleading results. I'd suggest handling this in your code.

**Comment by apesternikov** [comment]
This is a real world code. Large team worked on it over years. It would be a extremely nontrivial effort to change its data model. The only reasonable way to instrument it with prometheus would be to create a wrapper around the prometheus client api to handle this special case, exactly what I am trying to avoid. Also, something is telling me that our situation is not exactly unique.
Can we at least make it configurable non-default? something like cough-public-static-method-cough on SimpleCollector:
`public static void setDefaultLabelValue(String defaultValue)`
if it is not set - keep current default behavior of throwing runtime exception.

**Comment by brian-brazil** [comment]
You don't have to change your data model, just where you're doing instrumentation as your data model and the Prometheus data model don't match.

> something like cough-public-static-method-cough on SimpleCollector:

Global flags that subtly change behaviour don't sound like the best idea to me.

**Comment by apesternikov** [comment]
It is safe to assume it is everywhere, so either all calls would look something like
`that.labels(SomeUtil.denullify(label1), SomeUtil.denullify(label2), SomeUtil.denullify(label3)).inc()`
or we have to wrap api to make more sane. I am fine with that, I just thought we are not the only once who would use some peace of mind knowing that instrumented code would not blow up suddenly in production when data changes.

**Comment by brian-brazil** [comment]
I believe you're only the 2nd person to have issues with this approach, so after 3 years I think it's safe to say it's not a problem in general.

**Comment by mufid** [comment]
Hi, we face the same issue. It would be very easy to change the labels with very little to no validation. My suggestion is to add default value or listener.

This behaviour is dangerous and we don't expect that. It is something like Logger that can throw exception. We don't expect instrumentation to throw exception.

**Comment by mufid** [comment]
Hi, I've made a repository to address such issue as mentioned by @apesternikov. If you happen facing the same issue, please kindly see this repo: https://github.com/safeprometheus/client_java
