### ISSUE TITLE
Gauge class is throwing NPE with labels

### ISSUE THREAD

**Issue by rthirumal1999** [prometheus/client_java#318]
I have the following code, and when It gets invoked, it throws NPE. By commenting label, it worked
    
    private static final Gauge requestTotal = Gauge.build()
        .name("HelloApp")
        .labelNames("CurrentRequests")
        .help("Guage Current Requests").register();

    public void doFilter(ServletRequest request, ServletResponse response, FilterChain chain) throws IOException, ServletException {

        System.out.println("GatewayFilter =====" + requestTotal);
        HttpServletRequest req = (HttpServletRequest) request;
        requestTotal.inc();
        chain.doFilter(request, response);
        requestTotal.dec();
    }

2017-11-28 13:55:30.883  INFO 11999 --- [           main] o.c.p.s.j.JavaMetricsApplication         : Started JavaMetricsApplication in 5.527 seconds (JVM running for 5.935)
GatewayFilter =====io.prometheus.client.Gauge@7ed7259e
2017-11-28 13:55:39.776  WARN 11999 --- [tp2147046752-50] org.eclipse.jetty.server.HttpChannel     : /hello

java.lang.NullPointerException: null
	at io.prometheus.client.Gauge.inc(Gauge.java:234) ~[simpleclient-0.0.23.jar!/:na]
	at io.prometheus.client.Gauge.inc(Gauge.java:228) ~[simpleclient-0.0.23.jar!/:na]
	at org.cbp.pspd.samples.javametrics.GatewayFilter.doFilter(GatewayFilter.java:27) ~[classes!/:na]

Version(s)

	compile 'io.prometheus:simpleclient_spring_boot:0.0.21'
	compile 'io.prometheus:simpleclient_servlet:0.0.21'
	compile 'io.prometheus:simpleclient_hotspot:0.0.21'
	compile group: 'io.prometheus', name: 'simpleclient_spring_web', version: '0.0.23'

**Comment by brian-brazil** [comment]
https://github.com/prometheus/client_java#labels

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by rthirumal1999** [comment]
I am trying to provide labels though the annotations to @PrometheusTimeMethod. I don't see it supports it. 
Can you clarify? Or am I missing something

Thanks
