### ISSUE TITLE
TextFormat write004

### ISSUE THREAD

**Issue by nicopoirier** [prometheus/client_java#321]
Hello

In the method write004 of class TextFormat, prometheus client has a small bug. The method generate an extra comma in the labels after the last attribute.

https://github.com/prometheus/client_java/blob/1a8bf7da57402f444861c32abc9e0c7cd313748e/simpleclient_common/src/main/java/io/prometheus/client/exporter/common/TextFormat.java#L43

Regards

**Comment by brian-brazil** [comment]
This behaviour is correct.
