### ISSUE TITLE
Include Application name in Prometheus Output

### ISSUE THREAD

**Issue by harishkadamudi** [prometheus/client_java#323]
Hi Team,

Is there anyway that I can Include application name in Prometheus output.
Ex. rather than threads_daemon 106.0, I'd like too see append application name.
Let's say springbootapp_threads_daemon 106.0

**Comment by brian-brazil** [comment]
The application name is a target label on the Prometheus side. Metric names should not contain the name of the application, they should point to a line of code in whatever file that metric is defined in.

**Comment by harishkadamudi** [comment]
Anyway to achieve this, just append appname?
