### ISSUE TITLE
HttpServer tries and fails to create a Jetty HttpServer when defined by SPI

### ISSUE THREAD

**Issue by kagkarlsson** [prometheus/client_java#326]
The `HTTPServer` will not start when using Jetty as `HttpServerProvider`. Might be as easy as to call `.create(addr,..)` directly, without call to `bind(...)`.

Unless the intent is to always start a com.sun Server, then perhaps that should be done more explicitly.

```FATAL ERROR in native method: processing of -javaagent failed
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.NullPointerException
	at org.eclipse.jetty.http.spi.JettyHttpServer.bind(JettyHttpServer.java:94)
	at org.eclipse.jetty.http.spi.JettyHttpServerProvider.createHttpServer(JettyHttpServerProvider.java:69)
	at com.sun.net.httpserver.HttpServer.create(HttpServer.java:130)
	at com.sun.net.httpserver.HttpServer.create(HttpServer.java:105)
	at io.prometheus.jmx.shaded.io.prometheus.client.exporter.HTTPServer.<init>(HTTPServer.java:144)
	at io.prometheus.jmx.shaded.io.prometheus.jmx.JavaAgent.premain(JavaAgent.java:38)
	... 6 more
```
  
**Versions:**
jmx_exporter:  0.1.0
simpleclient_httpserver: 0.1.0  (by transitive dependency)

**Comment by brian-brazil** [comment]
That's an old version of the jmx exporter. Is there a bug here in client_java?

**Comment by kagkarlsson** [comment]
Yes, I believe it could be considered a bug in `client_java` which is used by `jmx_exporter`. If you want to support a pluggable HttpServer I think you might want to call `.create(addr,..)` instead of `create()` and then `bind(addr, .....) which causes the NPE for jetty.  (have not tested yet though)

Or, to always get a `sun.net.httpserver.HttpServerImpl`, instantiate it directly.

**Comment by brian-brazil** [comment]
We're not trying to create a pluggable http server, merely a hardcoded http server.

**Comment by kagkarlsson** [comment]
Hmm.. easier said than done it seems. Seems we are forced through the SPI-mechanism, `HttpServerImpl` and `DefaultHttpServerProvider` both seem to be internal.

Btw. the issue can be reproduced by adding the following dependency to `simpleclient_httpserver` and running its tests.

```
<dependency>
    <groupId>org.eclipse.jetty</groupId>
    <artifactId>jetty-http-spi</artifactId>
    <version>9.2.22.v20170606</version>
</dependency>
```

**Comment by kagkarlsson** [comment]
`create(addr,..)` does not seem to work with `jetty-http-spi` either..

**Comment by brian-brazil** [comment]
I'm still not understanding where the issue is. jmx_exporter 0.1.0 does not use jetty, it uses the built-in HttpServer that comes with the Java.

**Comment by kagkarlsson** [comment]
Ok, sorry for being unclear!

As far as I can see, jmx_exporter uses `HTTPServer` from `simpleclient_httpserver` which technically uses the JDK's `HttpServerProvider.provider()` to instantiate a `HttpServer`. `HttpServerProvider` uses the Java SPI-mechanism to determine what `HttpServer` implementation to instantiate, and in most cases that will be the built-in `sun.net.httpserver.HttpServerImpl`. However, since SPI is used, if I put a `jetty-http-spi` dependency on the classpath, it will instead try to instantiate a Jetty-httpserver, which fails.

So it is a pretty edgy case. We are using `jetty-http-spi` in our application to expose RMI services over Jetty. Ultimately, we would just like to get the jmx_exporter to work in our app, but after looking at the possibilities, I am not clear on how we can achieve that in our current setup.

**Comment by brian-brazil** [comment]
So are we using the APIs incorrectly, or is `jetty-http-spi` not following the spec?

**Comment by kagkarlsson** [comment]
Javadoc for `HttpServer`
https://docs.oracle.com/javase/8/docs/jre/api/net/httpserver/spec/com/sun/net/httpserver/HttpServer.html

There is some dodgy code in `com.sun.net.httpserver.HttpServer`:
```
    public static HttpServer create() throws IOException {
        return create((InetSocketAddress)null, 0);
    }

    public static HttpServer create(InetSocketAddress var0, int var1) throws IOException {
        HttpServerProvider var2 = HttpServerProvider.provider();
        return var2.createHttpServer(var0, var1);
    }
```

Calling `create()` results in a call `create(null, 0)` which seems a bit dodgy, and is not handled gracefully by Jetty. `addr` is assumed to be not-null.

I think it would be better for you to call `create(addr,..)` directly in [HTTPServer](https://github.com/prometheus/client_java/blob/master/simpleclient_httpserver/src/main/java/io/prometheus/client/exporter/HTTPServer.java#L144),
but have not been able to verify that with Jetty yet.

**Comment by brian-brazil** [comment]
That sounds to me like jetty isn't implementing `create()` correctly.

**Comment by kagkarlsson** [comment]
One could make that argument, but the SPI interface has no no-parameter `create`, and says nothing of `addr` potentially being null. One could also make the argument that `com.sun.net.httpserver.HttpServer` is a misbehaving utility-class not using `HttpServerProvider` correctly I think.

Am however having problems getting the tests in `io.prometheus.client.exporter.TestHTTPServer` to run with Jetty, even after patching `HTTPServer` to call `create(addr, ..) directly. The server is not responding...

**Comment by kagkarlsson** [comment]
Is it possible to expose the jmx-exporter on an existing web-server, i.e. not run it as a javaagent?

**Comment by brian-brazil** [comment]
We're using `com.sun.net.httpserver.HttpServer` as documented. If you're injecting another implementation that breaks, I don't think the bug is in our code. I think it's either in Java or Jetty.

> Is it possible to expose the jmx-exporter on an existing web-server, i.e. not run it as a javaagent?

The collector can be used on its own, but if you can do that you should use direct instrumentation rather than having to get into JMX.

**Comment by kagkarlsson** [comment]
Yes I agree, the bug is not in your code. I am not sure I will pursue this any further due to the limited success of my patch-attempts.

Regarding the jmx_exporter, is primarily meant to be used to monitor third-party jvm-applications like cassandra, kafka etc? And if we develop a java-app, we should primarily try to use `client_java` directly?

**Comment by brian-brazil** [comment]
> Regarding the jmx_exporter, is primarily meant to be used to monitor third-party jvm-applications like cassandra, kafka etc?

Yes.

>  And if we develop a java-app, we should primarily try to use client_java directly?

Yes. You only want to use the JMX exporter if you can't change the source.

**Comment by kagkarlsson** [comment]
For future readers, this issue is being fixed in Jetty:
https://github.com/eclipse/jetty.project/issues/2114
