### ISSUE TITLE
How to sanitize metric names and dimensions in prometheus?

### ISSUE THREAD

**Issue by digambarGitHub** [prometheus/client_java#327]
While scraping data from prometheus, how to verify that metric name or dimensions provided to query are correct or not? Who will handle the responsibility?

**Comment by digambarGitHub** [comment]
If I need to use client_java library , then do I need to do any external configuration for that?

**Comment by brian-brazil** [comment]
Any data in Prometheus has already passed validation.

**Comment by digambarGitHub** [comment]
Can prometheus apply filter to metric labels while scraping data from targets?
e.g. Target have matric **metric_1**{label_1="value_1", label_2="value_2",lable_3="value_3"}. 

My requirement is to pull/scrape only those metrics which has all above 3 lables (lable_1, lable_2,lable_3 and it must have specific values), if metric does not have any of these 3 lables then do not scrape that metric.

**Comment by brian-brazil** [comment]
Yes, but that's nothing to do with client_java - and also an odd thing to want. If you don't want it scraped, don't expose it in the first place.

**Comment by digambarGitHub** [comment]
How can we achieve this? Please let me know, I also want to filter if label has specific value or not.

**Comment by brian-brazil** [comment]
Don't create the metric/child in question.

**Comment by brian-brazil** [comment]
This does not appear to be an issue with the library, closing.
