### ISSUE TITLE
Fixed / global labels for standard collectors

### ISSUE THREAD

**Issue by naude-r** [prometheus/client_java#330]
We would like to add a fixed label / value to all hotspot / hibernate metrics. This is needed to differentiate between different services. An example label would be e.g. service_name="MyService".

We could not find an elegant solution apart from writing our own version of the relevant collectors.

Any ideas appreciated.

**Comment by brian-brazil** [comment]
This is an anti-pattern in Prometheus, this use case should handle this via service discovery on the Prometheus side.

**Comment by naude-r** [comment]
Thank you. That makes sense.
