### ISSUE TITLE
add uptime to StandardExports

### ISSUE THREAD

**Issue by davidkarlsen** [prometheus/client_java#336]
It would be nice to add uptime (https://docs.oracle.com/javase/7/docs/api/java/lang/management/RuntimeMXBean.html#getUptime()) to StandardExports as this can be used to determine if the process has been restarted etc.

**Comment by brian-brazil** [comment]
That's already available as process_start_time_seconds.

**Comment by brian-brazil** [comment]
> Is the idea that downstream dashboards compute the uptime as now - startTime?

Yes, Prometheus has a `time()` function for this.

> Still opposed to adding it? 

It'd be duplicating data we already have, and in a form that's less useful in general.

**Comment by ryanhall07** [comment]
In case others find it useful in the future, here is the prometheus rule I added to record process uptime. Need to record it since I'm exporting out of Prometheus.

```
record: process_uptime_seconds
expr: timestamp(process_start_time_seconds) - process_start_time_seconds
```
