### ISSUE TITLE
feature request: Enable adding labels in @PrometheusTimeMethod

### ISSUE THREAD

**Issue by yarix** [prometheus/client_java#340]
The @PrometheusTimeMethod is very easy to use, it would be nice it there will be an option to add labels in addition to the 'name' and 'help' that are mandatory.

the labels will have to come in pairs of key:value here is a simple example.
```java
@PrometheusTimeMethod(name="internal_method_seconds", 
                           help="some benchmarks", 
                           labelPairs={"component","backend","method":"updateDB"})
public void updateDB(String customerName, Integer amount) {
  //do something
}
```

some more advanced usecases might be by adding values from the method arguments, something like:
```java
@PrometheusTimeMethod(name="backend_method_seconds", 
                           help="some benchmarks", 
                           labelPairs={"component", "backend", "customer":"$customerName"})
public void insertRecord(String customerName, RecData data) {
  //do something
}
```

**Comment by brian-brazil** [comment]
Java annotations are not powerful enough to do this, and that "component" label should be in the metric name. You want to use normal instrumentation here.

**Comment by yarix** [comment]
Thanks Brian, 
Yes, i know it's not powerful enough (that's the point of this issue :smiley: ). For advanced statistics, I use Histograms and also add custom labels inside the method based on business logic. 
Yet, the java annotation is a bit 'too simple', (I hope people will vote for such need).

**Comment by brian-brazil** [comment]
I mean Java isn't powerful enough to do this, even if it made sense it is not a feature that could be added.

As soon as you want anything custom you have to do the instrumentation yourself.
