### ISSUE TITLE
NullPointerException setting labels for histogram in java client

### ISSUE THREAD

**Issue by jtktam** [prometheus/client_java#344]
Histogram callDuration = Histogram.build().name("some_metric").help("Some Metric").labelNames("production","server1");
...
Histogram.Timer timer = callDuration.startTimer();

**this causes a null pointer exception when it tries to set timer on the histogram**

removing the labelNames so that the declaration is 

Histogram callDuration = Histogram.build().name("some_metric").help("Some Metric");
...
Histogram.Timer timer = callDuration.startTimer();

**this works**

if labels are not supported for histogram then the method shouldn't accept and set the labels.. then crash when you actually use it

**Comment by brian-brazil** [comment]
You need to call labels().

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by jtktam** [comment]
if histogram extends simplecollector<histogram.child> and the labels method is only on the histogram.child, your suggestion of using the labels method would mean an extra unnecessary declaration.  shouldn't there be a way to call labels from histogram directly?

**Comment by sysmat** [comment]
I also have this problem with summery and I'm setting labels

simpleclient_servlet ver:  0.6.0

```
static final Summary SUMMERY= Summary.build()
                                                    .namespace("aaaa")
                                                    .name("summery")
                                                    .help("execution")
                                                    .labelNames("method", "env")
                                                    .register();    
SUMMERY.labels("get", "qa");
Summary.Timer timerExec = SUMMERY.startTimer();
 // error:  java.lang.NullPointerException at io.prometheus.client.Summary.startTimer(Summary.java:315)

```
is this supported or bug or I'm doing something wrong, Regards

**Comment by kolapkardhaval** [comment]
@jtktam I am getting the same issue. My code is as below:
Step 1
histogram=Histogram.build()
                .name("response_time_seconds")
                .help("response time in seconds")
                .labelNames("Controller", "Method", "Path", "Verb", "Status")
                .register(collectorRegistry);
Step 2
Histogram.Timer requestTimer = histogram.startTimer();
Step 3
histogram.labels(controller, method, path, verb, status)
                      .observe(responseTime);

What am I doing wrong?

**Comment by dreamershl** [comment]
It is because you need call the startTimer for labeled  children since it is labeld.

 Histogram.Timer requestTimer = histogram.labels(controller, method, path, verb, status).startTimer();

**Comment by anandsunderraman** [comment]
I think it would help to add this to the read me
