### ISSUE TITLE
spring-boot 2 breaking changes

### ISSUE THREAD

**Issue by jorgheymans** [prometheus/client_java#345]
Actuator in spring boot 2.0R2 has quite a few changes that make this exporter not compile anymore. Given that 2.0 is going to go out in a couple of days (according to https://github.com/spring-projects/spring-boot/milestone/52 at least) it would be nice to support it. How should the compilation errors be dealt with ? Consider 0.2.0 the last version that supports spring boot 1.x and move everything over to 2.x ? Or have two versions in parallel ?

**Comment by brian-brazil** [comment]
This only supports 1.x, and it is not planned to support 2.x.

**Comment by checketts** [comment]
@jorgheymans Prometheus support is included in Spring boot 2. To enable it see here: https://stackoverflow.com/a/48766683/970308

**Comment by jorgheymans** [comment]
alrighty thanks for the quick reply, closing here.

**Comment by thestevenbell** [comment]
These documents https://docs.spring.io/spring-metrics/docs/current/public/prometheus are out of date.  Following the directions results in a project that will not compile.
