### ISSUE TITLE
Spring boot client registers incorrect status code when exception is thrown

### ISSUE THREAD

**Issue by marcosnils** [prometheus/client_java#347]
When a spring boot `RestController` throws an exception, the prometheus integration registers a 200 status code instead of 500. This doesn't happen with the native spring metrics library. 

Here's an example project I put together with some unit tests to demonstrate the issue. Just clone the repo and run `mvn test` to get the error.

Here's the controller returning the exception:
https://github.com/marcosnils/spring-boot-prom/blob/master/src/main/java/com/prom/controller/ErrorController.java#L17-L20

And here's the test that compares native `spring metrics` vs `prometheus` instrumentation:
https://github.com/marcosnils/spring-boot-prom/blob/master/src/test/java/com/prom/ErrorControllerTest.java#L31-L38

https://github.com/marcosnils/spring-boot-prom

/cc @arrodriguez

**Comment by marcosnils** [comment]
@brian-brazil any ideas about this?. Any hints where to look at so I can craft a PR to fix it?

**Comment by brian-brazil** [comment]
Which metric is the issue with?

**Comment by marcosnils** [comment]
@brian-brazil http_server_requests_count and http_server_requests_sum are the ones that I saw. But I believe that any metric that handles a status_code will be impacted by this.

**Comment by brian-brazil** [comment]
Those metrics aren't coming from this code. I think you need to take this up with Spring.

**Comment by marcosnils** [comment]
@brian-brazil spring generates the metrics but IIUC, this library translates them to the prometheus format. Check https://docs.spring.io/spring-metrics/docs/current/public/prometheus#timers

Have you seen the example project I put together?. Can you take a quick look at the tests to see if you can help me understand where the problem comes from?. The issue appears when I add this library in the `POM` file and use the @Timed annotation.

**Comment by brian-brazil** [comment]
That instrumentation is not from client_java, we've no Timed annotation.

**Comment by marcosnils** [comment]
@brian-brazil the annotatoin is spring's but isn't this your library? compile `'io.prometheus:simpleclient_common:latest.release'`.

That is the library the transaltes the spring native metrics into prometheus. That's where the error happens.

**Comment by brian-brazil** [comment]
I doubt that our code would change label values, this is most likely a case of bad data being provided to client_java.

**Comment by marcosnils** [comment]
Thanks for being supportive. Maintainers like you make people want to contribute to OS projects :+1:

**Comment by marcosnils** [comment]
In case someone is interested in this issue, I've managed to fix it by using micrometer instead of spring's recommended way to add prometheus metrics described here (https://docs.spring.io/spring-metrics/docs/current/public/prometheus).
