### ISSUE TITLE
Implement text format version 0.0.4

### ISSUE THREAD

**Issue by beorn7** [prometheus/client_java#35]
The plan is to replace JSON as the human readable format by the new simple&flat text format (v 0.0.4, see https://docs.google.com/document/d/1ZjyKiKxZV83VI9ZKAXRGKaUKK2BIWCT7oiGBKDBpjEY/edit?usp=sharing ), so that JSON support can be completely removed.

All 'rich' client libraries should therefore support the text format (even if they also support the protobuf format, which is preferred for machine-machine interaction). 

This issue tracks the implementation for the Java client.

@matttproud I hope you have some cycles left to do this. If not, please unassign, and I'll see what can be done at Soundcloud.

**Comment by brian-brazil** [comment]
The simpleclient implements text version 0.0.4, is that enough to resolve this?

**Comment by beorn7** [comment]
I'll close this as it gets more and more misleading. I'll file a new issue for the 'real' thing (deprecating the old client).
