### ISSUE TITLE
Release request

### ISSUE THREAD

**Issue by marcust** [prometheus/client_java#355]
@brian-brazil could you be so kind to release the current state as 0.3.1? I ran into the same NullPointerException issue and actually prepared a patch until I saw that someone already fixed it. Given that the release cycles are rather long I would kindly ask you to do a dot release.

Thanks

**Comment by brian-brazil** [comment]
I was hoping on getting a fix for https://github.com/prometheus/jmx_exporter/issues/251 in with the next release.

**Comment by marcust** [comment]
Ok, was just wondering what the plan is. Maybe I'll have some time next week to have a look as well, but it looks like a rather obscure issue.

**Comment by brian-brazil** [comment]
It's a simple one to fix, we need to not cache the mBeans at startup.
