### ISSUE TITLE
Pushgateway support

### ISSUE THREAD

**Issue by beorn7** [prometheus/client_java#36]
The Java library should support pushes to the Pushgateway.

I assume this to be a fairly easy change. (Corresponding change in the Go client library see https://github.com/prometheus/client_golang/commit/c21d91ceb94eb2c0f8c0f544307ab2d2a41919a1 , relevant change is 30 LOC.) @matttproud @brian-brazil if you are working on client_java anyway, perhaps you can just sneak this change in somewhere? Otherwise, I'll look for somebody at Soundcloud to do it (possibly myself, but as said elsewhere, I have to come back to Java after 9 years absence - Maven was a hipster tool back then...).

**Comment by brian-brazil** [comment]
The simpleclient_pushgateway module supports this.
