### ISSUE TITLE
Pushgateway client does not support Basic Authentication

### ISSUE THREAD

**Issue by tom-mi** [prometheus/client_java#364]
When running the pushgateway behind a reverse proxy with basic auth enabled, as [recommended in the FAQ](https://prometheus.io/docs/introduction/faq/#why-don%27t-the-prometheus-server-components-support-tls-or-authentication?-can-i-add-those?), it is not possible to use the Java Client, as it does not support Basic Authentication.

Please fix.

**Comment by cluttazi** [comment]
+1

**Comment by bitsal** [comment]
Please look at my PR. I am open to polish it as needed in order to merge the PR.
