### ISSUE TITLE
[enhancement] Should `MetricsFilter` add an option for the label Name `status`

### ISSUE THREAD

**Issue by wangyanbn** [prometheus/client_java#379]
Now `io.prometheus.client.filter.MetricsFilter` has two  label Names: `path`, `method`.
Should we add an option for the label Name `status`, which stands for the HTTP status?
The `MetricsFilter` of Spring Boot (`org.springframework.boot.actuate.autoconfigure.MetricsFilter`) has three attributes: path, status and  response time.
If we add the `status` label, then we can make more detailed metrics analysis. We can make it as an option , not adding this label by default.

**Comment by brian-brazil** [comment]
MetricsFilter is just something to get you up an running quickly. If you want something custom, you can create your own metrics via direct instrumentation.

Be careful of cardinality with such a label.
