### ISSUE TITLE
#3 save

### ISSUE THREAD

**Issue by lexihogan** [prometheus/client_java#380]
assign me and i can fix it, but i need permissions

**Comment by brian-brazil** [comment]
Can you explain what you think is wrong?

**Comment by checketts** [comment]
I think @lexihogan is referring to the comments made on https://github.com/prometheus/client_java/commit/e6653f7b06363578a11f210d8a83d7453f172792#commitcomment-28733810 

Looks like the pom versions need `-SNAPSHOT`

**Comment by checketts** [comment]
@lexihogan Create a PR with your fixes via a frok. Permissions aren't needed on the main repo.

**Comment by brian-brazil** [comment]
That's a commit part of the release process, you should be using the released poms not arbitrary commits.
