### ISSUE TITLE
does the client automatically publish jmx mertices (heap size memory, thread number)?

### ISSUE THREAD

**Issue by geniusayush** [prometheus/client_java#400]

**Comment by brian-brazil** [comment]
https://github.com/prometheus/client_java#included-collectors

**Comment by agolomoodysaada** [comment]
@brian-brazil , it says in the README that this client exposes JMX metrics however I am not able to pull out JMX metrics such as kafka client metrics. Is there any way to remove the need to run a separate jmx exporter instance and instead pull this data directly out of this java client?

**Comment by dgmneto** [comment]
@agolomoodysaada, did you find any solution? I'm facing the exact same problem.

**Comment by agolomoodysaada** [comment]
@dgmneto , you can follow up discussion here: https://github.com/prometheus/jmx_exporter/pull/305

**Comment by zhenik** [comment]
Hi guys, maybe  this release could resolve your issue, take a look at [this release](https://github.com/sysco-middleware/kafka-client-collector)
