### ISSUE TITLE
TimeOut feature in Histogram/Summary

### ISSUE THREAD

**Issue by atulverma1997** [prometheus/client_java#401]
Proposal:
Sometimes a user start timer, but don't want to stop it. In such cases, the duration is not logged in any bucket. So, there should be a timeout settings in Histogram/Summary, so that user can configure after how much time, the timer should be automatically stopped, and logged in the appropriate bucket.

Use Case:
In my case, I send an HTTP request to an API, which could give a TimeOutException. In this case, I start the timer before sending the request. Here, I catch a TimeOutException in which I log the exception using Counter metric, but don't stop the Histogram.Timer. That is why, the timer starts, but it dont stop and is not logged in any of the bucket. There can be timeout setting in Histogram in which I can configure that after this much time, the duration should be logged in infinity bucket

**Comment by brian-brazil** [comment]
This behaviour would be incorrect, the request did not take infinite time it took however long the timeout was. It'd break the _sum to consider it to be infinite. It's your responsibility to stop the timer, such as by putting it in a finally block.

**Comment by atulverma1997** [comment]
What if a user start the timer and don't want to stop it ? 
In that case, a timeout feature can be added, which will automatically stop the timer if a user doesn't stop it.

**Comment by brian-brazil** [comment]
That's outside the scope of this library, if you want more complicated semantics (which I don't advise) it's up to you do handle them in your application. I would consider a timer not stopped by normal control flow to be a bug.

**Comment by atulverma1997** [comment]
Thank you @brian-brazil , 

I will change the code logic upon your advice, will try to make it simpler.
