### ISSUE TITLE
@EnablePrometheusEndpoint throws exception with Spring Boot 2.x

### ISSUE THREAD

**Issue by talkingscott** [prometheus/client_java#403]
Using the EnablePrometheusEndpoint annotation in a Spring Boot 2.0.3 application that ends with the following:

`Caused by: java.lang.IllegalStateException: Failed to introspect annotated methods on class io.prometheus.client.spring.boot.PrometheusEndpointConfiguration
Caused by: java.lang.NoClassDefFoundError: org/springframework/boot/actuate/endpoint/AbstractEndpoint
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.actuate.endpoint.AbstractEndpoint`

Looking at Spring Boot source, I see clearly that org.springframework.boot.actuate.endpoint.AbstractEndpoint no longer exists.  The closest thing in that package is now AbstractExposedEndpoint.

If you can, please let me know whether there is any plan to support Spring Boot 2.x in the future.

**Comment by talkingscott** [comment]
Nevermind.  Further down my page of google results I found [https://github.com/prometheus/client_java/issues/345], which suggests there will be no Spring Boot 2.x support from this project because micrometer will handle the endpoint.

**Comment by wotbstars** [comment]
Sorry to ask. Does it mean that Prometheus could not be used with Spring Boot 2.0 and above ?

**Comment by brian-brazil** [comment]
Prometheus is orthogonal to the clients. This particular integration only supports 1.0, however client_java in general will work with anything on the JVM.
