### ISSUE TITLE
Simple java client creating metrics with variable values in the name

### ISSUE THREAD

**Issue by JayT29** [prometheus/client_java#418]
We have a google cloud platform project with an api deployed onto kubernetes clusters. The api is a Java spring boot app and is using the Prometheus java client to gather metrics about the api.

We are then using stackdriver to show a dashboard of the api’s performance. The issue is that we are hitting the stack driver limit of 500 custom metrics. As shown by our GCP logs for the cluster:

component=remote msg="Unrecoverable error sending samples to remote storage" err="rpc error: code = ResourceExhausted desc = Your metric descriptor quota has been exhausted."

It seems that the Prometheus client is gathering metrics for endpoints including any parameters in the url. Here are a couple of examples:

# TYPE gauge_response_member_password_reset_b85f877ad38784686173f330045fd994d8b4c09a_37ef2f93_9ea4_4e28_b1cf_e6204ffce2fa gauge
gauge_response_member_password_reset_b85f877ad38784686173f330045fd994d8b4c09a_37ef2f93_9ea4_4e28_b1cf_e6204ffce2fa 1.0

# TYPE gauge_response_member_password_reset_passwordResetToken_clientId gauge
gauge_response_member_password_reset_passwordResetToken_clientId 290.0y

So, it is creating a log for the endpoint above which includes the data provided in the get url parameters, this is in addition to the metric for the same endpoint which just has the parameter names.

We are using the simpleclient plugins from Prometheus and are just using the out-of-the-box settings at present:

compile group: 'io.prometheus', name: 'simpleclient', version: '0.5.0'
compile group: 'io.prometheus', name: 'simpleclient_spring_boot', version: '0.5.0'

Shouldn't it just be creating the one set of metircs for the end-point which would be named with the variables names e.g. and not multiple entries with different names based on the passed in variable?

**Comment by brian-brazil** [comment]
Can you share your code?

**Comment by jpt1971** [comment]
Hey sure, here is the pertinent elements of our code:

build.gradle:

```
compile ('org.springframework.boot:spring-boot-starter:1.5.7.RELEASE')
compile ('org.springframework.boot:spring-boot-starter-web:1.1.4.RELEASE')
compile("org.springframework.boot:spring-boot-starter-security:1.5.7.RELEASE")
...
compile group: 'io.prometheus', name: 'simpleclient', version: '0.5.0'
compile group: 'io.prometheus', name: 'simpleclient_spring_boot', version: '0.5.0'
```

related application.properties entry:

`management.security.enabled=false`

Prometheus enabled Rest Controller:

```
@EnablePrometheusEndpoint
@EnableSpringBootMetricsCollector
@RestController
public class IndexController {
```

There is nothing 'special' about the end-points which are creating this issue but here is an example of a declaration just in case:

```
	@GetMapping("/member-password-reset/{passwordResetToken}/{clientId}")
	@ResponseStatus(HttpStatus.OK)
	public VerifyPasswordResetTokenResponse verifyPasswordResetTokenHandler(
			@PathVariable("passwordResetToken") String passwordResetToken, @PathVariable("clientId") String clientId)
	{
		LOGGER.log(Action.VERIFY_PASSWORD_RESET_TOKEN_REQUEST, passwordResetToken);
```

And that is all, I have changed in code to implement Prometheus, which works great until we noticed this issue with creating too many metrics. It should be noted that this is not consistent behaviour. I don't have exact counts but from a days worth of traffic - maybe 2000 change password requests are received from which about 15-20% lead to a new metric with the rest being covered correctly by the metric which has not had the variable values transposed. Have tried 'turning it off and on again' but the issue reappears after running for a while.

We are running this on a Kubernetes cluster and have implemented a Prometheus service to scrape the logs to StackDriver as per:

https://cloud.google.com/monitoring/kubernetes-engine/prometheus

**Comment by brian-brazil** [comment]
We're taking in the metrics that spring itself produces, so you should look at what options spring itself has for this.
