### ISSUE TITLE
JVM threads metrics

### ISSUE THREAD

**Issue by mr-git** [prometheus/client_java#420]
Why there are `jvm_threads_peak`, `jvm_threads_daemon` and `jvm_threads_current` insterad of `jvm_threads` with extra label with dimension values like: `peak`, `daemon` and `current`?

**Comment by brian-brazil** [comment]
See https://prometheus.io/docs/instrumenting/writing_exporters/#labels, these don't make sense when averaged or summed so they're different metrics with different names.
