### ISSUE TITLE
TextParser: HELP line optional?

### ISSUE THREAD

**Issue by eaglerainbow** [prometheus/client_java#425]
Hi Brian, 

This is in reference to https://github.com/promregator/promregator/issues/73, where a tricky situation with `HELP` lines happens. Here is the situation in a nutshell:

* Promregator parses Prometheus' Exposition Format requests and aggregates/forwards them. 
* For this, Promregator has its own Prometheus' Exposition Format parser. The parser is tolerant enough to accept metrics without a `# HELP` line. 
* The format itself explicitly permits that both `# HELP` and `# TYPE` are optional (see also https://prometheus.io/docs/instrumenting/exposition_formats/#grouping-and-sorting, first sentence there). 
* Promregator's parser outputs its data in the `MetricFamilySamples` format. 
* After a lot of processing, in the end the class `TextFormat` (of this project here) is used to generate a proper Exposition Format string again, which then is sent to Prometheus.
* https://github.com/promregator/promregator/issues/73 documents a situation, where a metric *without* `# HELP` line is processed through the system - and fails.
* As https://github.com/prometheus/client_java/blob/1950cff385518eae45651df47547f80547d72c1a/simpleclient_common/src/main/java/io/prometheus/client/exporter/common/TextFormat.java#L23 is not conditional and the `metricFamilySamples.help` is `null`, an NPE is raised.

I also stumbled over the check at https://github.com/prometheus/client_java/blob/1950cff385518eae45651df47547f80547d72c1a/simpleclient/src/main/java/io/prometheus/client/SimpleCollector.java#L165 which prevents that any "java-natively" generated metrics comes without a "help" string. I used blame and that line dates back to the very first commits in the repository. The commit's description does not give me any indication why a help string must be enforced. I also could not find any indication in the javadocs that this is enforced at all (or why this is the case). 

In general, I am quite in favor that metrics *should* have a help. However, the `TextFormat` class currently only implements a subset of the specification and for my case this causes compatibility issues.

What do you think about the situation?
* Is it possible to relax (only) the `TextFormat` class in that sense? (a PR would not be rocket science - only the unit tests would be a little tricky).
* Was there a special intention behind the idea to enforce help strings even though the protocol is more generous?

Thanks for your insights!

**Comment by brian-brazil** [comment]
Per the client library guidelines, an empty help string should be accepted
(though I don't see a need to support null). If that's not the case, please
send a PR.

**Comment by brian-brazil** [comment]
Missing help should be identical to enjoy empty help.

**Comment by eaglerainbow** [comment]
Ok, thanks. Then I will convert the `null`s into empty strings. 
See also commits attached to https://github.com/promregator/promregator/issues/73
