### ISSUE TITLE
Allow override when registering Collector.

### ISSUE THREAD

**Issue by llech** [prometheus/client_java#429]
Currently CollectorRegistry throws IllegalArgumentException when attempting to register Collector under the name, that is already used.

It was thought to be consistent with recommended usage: create Collectors as static final variables, so that  they will be created only once during JVM lifetime, right?

Well, in OSGi environment the answer is, left...

When the bundle is restarted or reloaded, the static variables are created once again, so that I have this exception during Collector creation, and bundle creation fails. Bundle restart can be triggered by installing another bundle, and it's quite a natural state of art.

So for my needs, I need to fork and modify the library to support such behavior. I think of adding extra optional parameter to register() method : allowOverride (default false). As alternative, an existing collector could be returned by register() method, which would allow to re-use existing statistics, and not reset them upon bundle restart. 

Would such change be welcome in the code basis, so that I could merge it back? Otherwise I'd just keep my modified version of library. As long as it is present in github, it would be OK, from the licence point of view?

**Comment by brian-brazil** [comment]
Another thing to consider is that once a metric is registered, it should in principle exist until the process terminates - without resetting or similar. A way to have metrics persist state over the lifetime of the process is desirable.

**Comment by llech** [comment]
I've created pull request https://github.com/prometheus/client_java/pull/430
I've needed to add the possibility to tell MetricsServlet which CollectorRegistry to use.
On servlet destroy, you need to deregister Collector as well, otherwise simply removing and adding servlet would trigger IllegalArgumentException in init() method.

**Comment by brian-brazil** [comment]
Per the PR, direct instrumentation is probably a better approach here as the filter is meant to be a quick way to get something simple going.
