### ISSUE TITLE
Metric aggregation (Short lived jobs)

### ISSUE THREAD

**Issue by Draczech** [prometheus/client_java#433]
Hi, this might be a bit off topic, but it is related to the java client anyway.
Recently I started working on Prometheus based monitoring in our company. We are using metrics library which I ported from [kamon](https://kamon.io/documentation/0.6.x/get-started/) to [dropwizard](https://metrics.dropwizard.io/4.0.0/) and added possibility of metrics push and pull for Prometheus.

With classic application metrics everything works fine so far, but I have a use case in which we would like to query our YARN resource manager via its REST API and send the data to Prometheus as well. There are some queries previously managed by the old library as well to check mostly for exceptionally long running time for some jobs (and later use some alerting for processing the metrics).

Let's say I receive N results from the YARN response, each with `startTime, finishTime, elapsedTime, cpuUsage, memoryUsage` which are the metrics to process and some other metadata. I cannot simply use just few selected metrics, as there would be clash in names and it would not be possible to publish all results into Prometheus.

What I could do is to publish app results as individual time series. But that cannot be done simply by single pusher as there would be multiple items with the same name/help. And push request results into `400` response in such case. Prometheus gateway accepts following format though:
```
# HELP start_time_ms Generated from DW metric (metric=start_time)
# TYPE start_time_ms gauge
start_time_ms{app="application_1",} 15
start_time_ms{app="application_2",} 10
# HELP elapsed_time_ms Generated from DW metric (metric=elapsed_time)
# TYPE elapsed_time_ms gauge
elapsed_time_ms{app="application_1",} 20
elapsed_time_ms{app="application_2",} 30
```
But before I start hacking my [Collector](https://github.com/prometheus/client_java/blob/master/simpleclient/src/main/java/io/prometheus/client/Collector.java) into creating such format somehow I would like to ask what is the recommended approach for this case. Because creating numerous time series for single use only does not sound like the best idea. Neither does bending the [DropWizardExports](https://github.com/prometheus/client_java/blob/master/simpleclient_dropwizard/src/main/java/io/prometheus/client/dropwizard/DropwizardExports.java) to some crazy format.

I could publish some aggregated data only, of course. But then I lose the information about problematic apps which would be handy for alerting otherwise (as it gets most likely lost in the averaged data). And introducing any thresholds into my code does not seem right as alerts are designed for such cases.

Thanks for any help on this!

**Comment by brian-brazil** [comment]
This is question is out of scope of client libraries. It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
