### ISSUE TITLE
Number of threads when open Prometheus exporter server

### ISSUE THREAD

**Issue by DatPhanTien** [prometheus/client_java#438]
Dear all,

Our versions:
Prometheus 0.5.0 
CentOS 7.4
JAVA hotspot 1.8.0_181

When we open a HTTPServer (code https://github.com/prometheus/client_java/blob/master/simpleclient_httpserver/src/main/java/io/prometheus/client/exporter/HTTPServer.java) for exporting metrics, we noticed that the HTTP server opens an executor service of a pool of 5 threads by default (this value is hardcoded)
`executorService = Executors.newFixedThreadPool(5, DaemonThreadFactory.defaultThreadFactory(daemon));`

We register our metric collector:
`new OurCustomCollector().register();`

When Prometheus collects the metric values, the `collect()` method is called 5 times instead of once (in 5 different threads as created above).
`2018-11-08 11:12:02,221 - INFO  - pool-5-thread-3 - com.OurCustomCollector - Collecting the current custom metric
2018-11-08 11:12:02,918 - INFO  - pool-5-thread-4 - com.OurCustomCollector - Collecting the current custom metric`

Could you please let us know if this is normal? If it is NOT, what would be the reason?  Besides, what was the reason to set the number of threads hardcoded to the value of 5?

Best
Tien Dat

**Comment by brian-brazil** [comment]
Are you sure there's only one scrape happening?

**Comment by DatPhanTien** [comment]
Hello. I am pretty sure. Only one prometheus instance pointing to this exporter server

**Comment by brian-brazil** [comment]
What happens if you turn off the prometheus scraping, and hit it by hand?

**Comment by DatPhanTien** [comment]
Well, I just found out the reason. That was because one of my colleagues has a Docker container running Prometheus on his VM. Once we kill his Docker container, the number of collect() method call returns to 1, every scraping time.

When we hit it by hand, the collect method is called once more.

So this is basically my false alarm. Sorry and thanks for your quick react.
