### ISSUE TITLE
0.5.1 release?

### ISSUE THREAD

**Issue by leoconco** [prometheus/client_java#439]
There have been a couple of important bugs ( Size header for example). If no release is planned soon, could you please release something with these fixes?

**Comment by snago** [comment]
Yes, I also would like a release. I am looking forward to the fixed thread state metrics #391 #419 and replacing my prototype code with the final memory allocation exports #434.

ping @brian-brazil

**Comment by mkurde** [comment]
> Agree, I need PR #413, which fixed the bug when using with istio envoy proxy sidecar.

I second that. We have the issues described in [prometheus/jmx_exporter#304](https://github.com/prometheus/jmx_exporter/issues/304) and and would be awesome we could fix that soon to get our metrics back.
