### ISSUE TITLE
CKMSQuantiles.Item toString uses illegal formatter

### ISSUE THREAD

**Issue by Draczech** [prometheus/client_java#441]
In [CKMSQuantiles class](https://github.com/prometheus/client_java/blob/master/simpleclient/src/main/java/io/prometheus/client/CKMSQuantiles.java), line 270, there is following formatter: `return String.format("%d, %d, %d", value, g, delta);` where value is of `double`, not an integer.

This can cause some problems when debugging an application in IDE. Thanks for fixing the bug.

**Comment by brian-brazil** [comment]
Would you like to send a PR?

**Comment by Draczech** [comment]
PR done in https://github.com/prometheus/client_java/pull/442
