### ISSUE TITLE
Bridge graphite java package dependency missing

### ISSUE THREAD

**Issue by codecheetos** [prometheus/client_java#444]
Please document that graphite bridge is part of this dependency.
```
<dependency>
  <groupId>io.prometheus</groupId>
    <artifactId>simpleclient_graphite_bridge</artifactId>
  <version>0.0.13</version>
</dependency>
```
More documentation in here.
https://www.robustperception.io/exporting-to-graphite-with-the-prometheus-java-client

**Comment by brian-brazil** [comment]
I'm a bit confused, what exactly are you looking for?

**Comment by brian-brazil** [comment]
I'm not sure what you're asking for, so closing for now.
