### ISSUE TITLE
Add a "register or get" method on CollectorRegistry

### ISSUE THREAD

**Issue by dandew** [prometheus/client_java#463]
When `CollectorRegistry` is used in a context where `Collector` instances are created dynamically, users have to create their own cache in front of `CollectorRegistry` to make sure `register` is called only once per `Collector`. This is wasteful because `CollectorRegistry` also contains a `Collector` cache.

Please a "register or get" method that allows to attempt to register a `Collector` and returns the actually registered `Collector`.

Name suggestions: `tryRegister` `registerOrGet`

**Comment by brian-brazil** [comment]
See https://www.robustperception.io/why-predeclare-metrics, if you need this then you're using the library incorrectly.

**Comment by dandew** [comment]
The reasons given in this post why not creating metrics beforehand is suboptimal are all valid. Unfortunately, the reality in the field is not that perfect and there are cases where dynamic KPIs are needed.

So yeah, reality is incorrect.

**Comment by brian-brazil** [comment]
Then you probably want a custom Collector rather than direct instrumentation.

**Comment by kstrijbos** [comment]
We are also having issues with a method like this missing from the CollectorRegistry. We're using a setup with different classloaders in which the CollectorRegistry comes from a classloader higher up, but the static collectors come from classloaders lower in the hierarchy. This means that every pod/job/build/... uses the same CollectorRegistry but different static collectors. This ends in the "multiple collectors with the same name" issue.

A method like this would enable us to check for existing collectors.
