### ISSUE TITLE
CollectorRegistry.filteredMetricFamilySamples should filter on metrics name, not samples name

### ISSUE THREAD

**Issue by peergynt** [prometheus/client_java#466]
If I have an Histogram named `my_histogram`, I need to pass the 3 strings:
-  `my_histogram_count`
-  `my_histogram_sum`
-  `my_histogram_bucket`

to `CollectorRegistry.filteredMetricFamilySamples()` to see all the samples of my histogram.

I was thinking that it would make more sense to filter on the metric name, and not have the client trying to figure out all the possible sample names.

**Comment by brian-brazil** [comment]
This is how it's implemented in both clients that have it currently. One reason is so that you can pick out just the sum/count of a histogram, without having to transfer all the buckets.

**Comment by peergynt** [comment]
Opened PR #474 to clarify behavior.
