### ISSUE TITLE
Issue when use prometheus client with solr-exporter in cloud mode

### ISSUE THREAD

**Issue by hoantv** [prometheus/client_java#467]
used solr-prometheus-exporter java with Solr 6.6.x. It worked fine with a standalone Solr. But when I used with SolrCloud (./solr-exporter -z zookeeper), it didn't work. I enabled logging and saw that:
1. Metrics collection was fine.
2. Registry was updated successfully.
3. Could not get metrics via http://localhost:port/metrics. htttserver worked (telnet port ok).
 After i debugged, I saw httpserver could not get data from registry if s is null. So I added not null condition checking . It works.
 private static void writeEscapedLabelValue(Writer writer, String s) throws IOException {
        if (s != null) {
            for (int i = 0; i < s.length(); i++) {
                char c = s.charAt(i);
                switch (c) {
                    case '\\':
                        writer.append("\\\\");
                        break;
                    case '\"':
                        writer.append("\\\"");
                        break;
                    case '\n':
                        writer.append("\\n");
                        break;
                    default:
                        writer.append(c);
                }
            }
        }
    }

**Comment by brian-brazil** [comment]
null is not a valid utf-8 string, this is a bug in your exporter.
