### ISSUE TITLE
Rethrow exception if it is instance of RuntimeException, otherwise wrap with RuntimeException

### ISSUE THREAD

**Issue by pitometsyurii** [prometheus/client_java#477]
https://github.com/prometheus/client_java/blob/4e0e7527b048f1ffd0382dcb74c0b9dab23b4d9f/simpleclient/src/main/java/io/prometheus/client/Histogram.java#L223

An application with Spring can have registered exception handlers for custom exception. Catching all exceptions and throwing RuntimeException will simply ignore registered exception handlers and can return 500.

**Comment by brian-brazil** [comment]
The problem with that is that is would require changing the signature, which would be a breaking change.

**Comment by CodeEsthete** [comment]
At least we may check if e instanceof RuntimeException already and rethrow it, otherwise wrap with RuntimeException.

**Comment by brian-brazil** [comment]
That we could do.

**Comment by jthurne** [comment]
@brian-brazil it looks like the fix was merged in December. Would it be possible to build a new release with the fix in it?

In my opinion, this is a fairly serious issue as it silently breaks error handling for anyone who uses the time methods.

**Comment by brian-brazil** [comment]
0.8.1 is out.
