### ISSUE TITLE
Thread contention in TimeWindowQuantiles because of `synchronized`

### ISSUE THREAD

**Issue by t3hnar** [prometheus/client_java#480]
Hello guys,
Use of Summary gives considerable performance penalty because of multiple `synchronized` calls in `.observe` flow.
Will you able to fix this?

**Comment by brian-brazil** [comment]
This is a fundamental issue with client-side quantiles. If you remove the quantiles or use a Histogram instead, you can avoid this specific problem.

**Comment by t3hnar** [comment]
> This is a fundamental issue with client-side quantiles

do you mean that this is not solvable without `synchronized ` problem in computer science ?

**Comment by brian-brazil** [comment]
I've yet to see a solution that doesn't require this.

**Comment by rrakos-evo** [comment]
I'll investigate if we could use `atomics` / `compare-and-swap` instead of `locks` / `synchronized`, as that might yield better performance for our use cases.

**Comment by rrakos-evo** [comment]
I might have found something strange, but I could be misunderstanding the details. 🤔

It looks like [TimeWindowQuantiles#get](https://github.com/prometheus/client_java/blob/master/simpleclient/src/main/java/io/prometheus/client/TimeWindowQuantiles.java#L30) reads `current bucket`, but [TimeWindowQuantiles#insert](https://github.com/prometheus/client_java/blob/master/simpleclient/src/main/java/io/prometheus/client/TimeWindowQuantiles.java#L35) writes `all buckets`.
Note that [CKMSQuantiles#insert](https://github.com/prometheus/client_java/blob/master/simpleclient/src/main/java/io/prometheus/client/CKMSQuantiles.java#L90) is `synchronized`, so the writes are causing unnecessary thread contention.
I'm wondering what's the point of writing buckets which are never read?

**Comment by brian-brazil** [comment]
They're rotated through. Having a quantile that represents recent data (rather than since process start) is tricky.

**Comment by rrakos-evo** [comment]
I’ll check out `HdrHistogram` as the next experiment, as it looks like it’s designed exactly for our use case, but I’m not sure how well it integrates with Prometheus.

**Comment by rrakos-evo** [comment]
We'll continue with profiling the alternatives and experiments (#481, #482, #483, #484) under realistic workload(s), as I can't produce similar thread contention with synthetic benchmarks.

**Comment by rrakos-evo** [comment]
I'm still working on testing and profiling #482 + #484 using different use cases.
I won't be able to test them in isolation as I was asked to test them together.
I won't be able to test #481 and #483 as those are mutually exclusive to #484.

**Comment by rrakos-evo** [comment]
I'm sorry, but I still couldn't get back to this, but I'll try this week. 🙁

**Comment by brian-brazil** [comment]
#481 is in now.
