### ISSUE TITLE
Please accept arrays or iterables of label names/values

### ISSUE THREAD

**Issue by zpingcai** [prometheus/client_java#489]
Hi, I'm using this library in a Kotlin codebase, and I think there's a performance issue of passing label names and their values as varargs in Kotlin. 
Basically, Kotlin doesn't treat `String...` as `String[]`. The walk-around to pass in an array is by using a spread operator, which will create a copy of the original array. Since there could be thousands of records every minute, creating countless number of duplicate arrays is definitely a waste of resources.

**Comment by brian-brazil** [comment]
You can cache the return value of `labels`, otherwise we do already accept an array in the form of `String...`. This sounds more like a feature request for Kotlin, as if it is indeed a performance issue then it affects far more than this.

**Comment by zpingcai** [comment]
@brian-brazil Good idea! Thanks for telling the trick!
