### ISSUE TITLE
URLs in Poms are incorrect (for submodules)

### ISSUE THREAD

**Issue by ST-DDT** [prometheus/client_java#499]
Maven seems to append the submodules name/path to the url, thus the poms of the submodules reference a non existing page.

Examples:
http://github.com/prometheus/client_java/simpleclient
http://github.com/prometheus/client_java/simpleclient_common

Ref: https://github.com/prometheus/client_java/blob/master/pom.xml#L17

Please configure a working url for the submodules as well.

PS: While you are at it, please change your urls to use `https`

**Comment by brian-brazil** [comment]
What's this used for? We only set this in the parent.

**Comment by ST-DDT** [comment]
We have to report all libraries we use in our project to our customer including a working link to said project. Maven can generate these lists as part of the `site` goal, but the entire page is useless if the links on it aren't working. Manually fixing these (for ~100 libs per module) is quite a lot of effort, so I opened the issue here to fix it at the root.

**Comment by brian-brazil** [comment]
The docs say this value is inherited, so sounds like a bug. It's also optional, so I don't think you can generally assume it is present.

**Comment by brian-brazil** [comment]
I don't think there's anything to do here.
