### ISSUE TITLE
Pushgateway complaints on Helptext formatting 

### ISSUE THREAD

**Issue by mrunesson** [prometheus/client_java#501]
The prometheus pushgateway complains with
`msg="metric families inconsistent help strings" err="Metric families have inconsistent help strings. The latter will have priority. This is bad. Fix your pushed metrics!" ` when pushing metrics with the java library from a Apache Spark/Apache beam pipeline. 
Reason is that lot of lambdas are used and the class name of the lambdas is different on each deploy. When doing `metric.getClass().getName()` they look like `org.apache.beam.runners.spark.metrics.WithMetricsSupport$$Lambda$174/1482259285` and the prometheus pushgateway do not like that help texts are changing for metrics. 

The code that does this is here:
https://github.com/prometheus/client_java/blob/d7825cf87cd61a65b20fc2277b8f5e52bd7ec5f7/simpleclient_dropwizard/src/main/java/io/prometheus/client/dropwizard/DropwizardExports.java#L45-L46

I suggest to make the client library more nice to Prometheus pushgateway that the class name is not written out in the help text.
OR
Add support for turn off sending help messages to the pushgateway.

**Comment by brian-brazil** [comment]
I'm not sure this is a good use of the pushgateway dropwizard metrics should never be ending up there, however that warning is largely harmless. For debugging that message is quite useful.

@beorn7 any thoughts?

**Comment by beorn7** [comment]
Pushgateway has, with the given data and exposition model, no other choice but to "pick a winner" if there are two different help strings for the same metric name. As this _might_ indicate a real problem (e.g. an accidental name collision of completely unrelated metrics), Pushgateway prints out the warning.

What the client side is doing with this situation, is really up to them.

**Comment by mrunesson** [comment]
It is unfortunate that the lib controls help text as it does. Some Spark jobs are short-lived batch jobs, where it make sense to use the push gateway. According to our team responsible for the prometheus pushgateway it does not behave well and give the above message when help text for metrics change. 
I would say it make sense to make the library not writing help text in a way that it change per deploy since it the server it calls complains.  If it desired to keep the classname a solution can be to filter out last part of classname for lambdas. For instance instead of be `org.apache.beam.runners.spark.metrics.WithMetricsSupport$$Lambda$174/148225928` just take `org.apache.beam.runners.spark.metrics.WithMetricsSupport$$Lambda` which keep the class name for understandability and not change help text sent to pushgateway and make it happy.

**Comment by brian-brazil** [comment]
That'd be a layering violation though, we shouldn't care how classes are structured in some cases.

I'd suggest looking at using client_java directly.
