### ISSUE TITLE
ClassCastException in MemoryAllocationExports

### ISSUE THREAD

**Issue by kebuu** [prometheus/client_java#504]
Hello, 
I am working with an IBM jdk which seems to have a **GarbageCollectorMXBean** not being a **NotificationEmitter**. That's why I get a **ClassCastException** on line **29** of class **MemoryAllocationExports**.
Could it be possible to check if the **GarbageCollectorMXBean** is an instance of **NotificationEmitter** before casting it ?
Regards

**Comment by brian-brazil** [comment]
Would you like to send a PR?

**Comment by kebuu** [comment]
Ok, I'll will.
