### ISSUE TITLE
Integer histogram buckets are labeled with decimal values

### ISSUE THREAD

**Issue by alechenninger** [prometheus/client_java#506]
I believe this is the same issue as found in in the python client here: https://github.com/prometheus/client_python/issues/345

and discussed here: https://github.com/prometheus/client_golang/issues/500

Due to the use of Double.toString(bucket) for the le label value, values equivalent to integers like `1` are labeled like `le="1.0"`. Based on above issues, I expect `le="1"`.

**Comment by brian-brazil** [comment]
This client is following the Prometheus format spec. When this repo supports OpenMetrics it'll also follow that spec.

**Comment by alechenninger** [comment]
Aren't both compatible with prometheus format? As you said in https://github.com/prometheus/client_golang/issues/500 , it isn't specified for prometheus format.

What is the timeline for OpenMetrics support? It seems like the python client tries to support both, why not follow a similar strategy with all clients?

**Comment by brian-brazil** [comment]
I haven't gotten around to it yet, and there's still some minor details being worked out.

**Comment by alechenninger** [comment]
@brian-brazil Was this fixed?

**Comment by brian-brazil** [comment]
There was never a bug.
