### ISSUE TITLE
Publish a BOM

### ISSUE THREAD

**Issue by mikeholler** [prometheus/client_java#508]
Hey there! Love the project, but I would love it if there was a BOM file that is published for each version. If you're not familiar with a BOM,it stands for "Bill of Materials" it helps your Gradle (in my case, but it's originally a Maven thing) file look like this:

```
implementation("io.prometheus:simpleclient-bom:0.6.0")
implementation("io.prometheus:simpleclient_common")
implementation("io.prometheus:simpleclient_dropwizard")
implementation("io.prometheus:simpleclient_servlet")
```

Instead of this:

```
val prometheusVersion by extra { "0.6.0" }

implementation("io.prometheus:simpleclient:$prometheusVersion")
implementation("io.prometheus:simpleclient_common:$prometheusVersion")
implementation("io.prometheus:simpleclient_dropwizard:$prometheusVersion")
implementation("io.prometheus:simpleclient_servlet:$prometheusVersion")
```

Notice how you just leave the versions off when you use a BOM. This can help reduce the number of dependency compatibility surprises one can encounter, especially if a transitive dependency brings in a newer version of one of the components (it'll be reduced to the BOM's version).

Here's a deeper dive into how a BOM works:

https://howtodoinjava.com/maven/maven-bom-bill-of-materials-dependency/

**Comment by mikeholler** [comment]
@brian-brazil I'm not sure what point you're trying to make here, can you clarify? BOM usage isn't required if it exists (both of the code samples I provided would work after publishing a BOM).

**Comment by brian-brazil** [comment]
I'm not seeing how this additional complexity helps, nor if it'd work with our existing workflows. Have you run into actual issues here?

**Comment by mikeholler** [comment]
@brian-brazil thanks for responding, and absolutely it can be helpful. Here's an example of where you can easily run into problems:

* A new version of prometheus client is published. In this new version, let's say the `simpleclient_common` and `simpleclient_httpserver` communicate differently with one another than they did before, but the developer-facing interface remains unchanged.
* I add a new library dependency that depends on this new version of prometheus, but only `simpleclient_common`.
* Maven/Gradle/etc will resolve this by pulling the newer version of `simpleclient_common`, and the older version of `simpleclient_httpserver`
* This action produces no clear error, but could have unintended consequences because `simpleclient_common`'s new version isn't tested against `simpleclient_httpserver` on the new version

A BOM solves this problem, and IMO the level of complexity it adds is trivial. It's just one POM file that you create once and forget about (wiring it up so that it gets published with every new version), only updating it when you need to add or remove a prometheus library (e.g., `simpleclient_newmodule`).

**Comment by nickflink** [comment]
I also think this is a great enhancement.  It feels much better to handle dependencies with boms rather than pulling in the bits sharing the same version.  With a bom I can feel confident that I delegate the versioning to the library which makes coding simpler overall and helps to limit annoying dependency issues.

**Comment by mikeholler** [comment]
Fair enough, it's been a while since I've used this library and I'm just getting into it. Similar example:

* I'm depending directly on `io.prometheus:simpleclient_log4j:0.6.0`
* A transitive dependency I'm using depends on `io.prometheus:simpleclient_jetty:0.7.0`
* Both `simpleclient_log4j` and `simpleclient_jetty` depend on `io.prometheus:simpleclient`, but there's a conflict over which version to pull. `0.7.0` will get pulled if using Maven/Gradle.
* This means the following libraries will be on the path:
** `io.prometheus:simpleclient_log4j:0.6.0`
** `io.prometheus:simpleclient_jetty:0.7.0`
** `io.prometheus:simpleclient:0.7.0`

`simpleclient_log4j:0.6.0` was never tested with `simpleclient:0.7.0` and could result in unexpected behavior (even if the code compiles). BOMs were invented to solve this problem.

**Comment by mikeholler** [comment]
For clarity -- the above example would lock us to 0.6.0 on all of the libraries if I had depended on the 0.6.0 BOM (assuming such a BOM existed)

**Comment by brian-brazil** [comment]
That doesn't seem safe, the code may depend on a change in jetty 0.7.0. We're pretty careful to avoid changing the various internal interfaces across versions.

**Comment by mikeholler** [comment]
Would you strongly consider accepting an MR adding this feature assuming it simply added a `simpleclient_bom` top-level folder and a single POM inside?

**Comment by mikeholler** [comment]
Sorry, PR. I use GitLab daily so MR is stuck in my vocab.

**Comment by mikeholler** [comment]
I have limited time with which to contribute and only want to spend the time if it's something that's likely to be used.

**Comment by njhill** [comment]
+10 for this. @brian-brazil publishing a bom when you have a collection of sub-artifacts that are used together (including where some/many may be optional) is very standard and helps consumers of the library regardless of whether they are using maven/gradle etc. The biggest benefit is when you have a big tree of transitive dependencies, some of which themselves might depend on one or more prometheus artifacts but not necessarily the same versions of them.

This is done for example by [netty](https://mvnrepository.com/artifact/io.netty/netty-bom), [grpc-java](https://mvnrepository.com/artifact/io.grpc/grpc-bom), [spring](https://mvnrepository.com/artifact/org.springframework/spring-framework-bom), [jetty](https://mvnrepository.com/artifact/org.eclipse.jetty/jetty-bom), ... Here's a good overview in case you are interested: https://howtodoinjava.com/maven/maven-bom-bill-of-materials-dependency/

**Comment by brian-brazil** [comment]
Would this work seamlessly with our release process (standard mvn prepare/release)?

**Comment by njhill** [comment]
@brian-brazil yes I think it works with maven-release-plugin, and the addition is very simple as @mikeholler states above https://github.com/prometheus/client_java/issues/508#issuecomment-545110816

**Comment by brian-brazil** [comment]
If it can get updated automatically on release, then that sounds good.

**Comment by maxmil** [comment]
We'd be keen to use this but I don't think it's been released yet. This is a +1 for 0.9.1.
