### ISSUE TITLE
Metrics page renders for any path

### ISSUE THREAD

**Issue by agolubev** [prometheus/client_java#510]
Documentation says that access point is localhost:9001/metrics
However metrics page renders for localhost:9001/123 or any other path as well.
Perhaps need to limit to some well known endpoint. 
Tried on [Cinnamon] Agent version 2.12.0

**Comment by brian-brazil** [comment]
How is this a problem?

**Comment by agolubev** [comment]
It is a little confusing first as there is one endpoint mentioned in docs. And potentially this can be a security issue (chances are small - but still)

**Comment by brian-brazil** [comment]
If you want to restrict it you can setup your own HTTP server, which is how most users are expected to do things. The httpserver we provide is for getting up and running quickly.

**Comment by agolubev** [comment]
As long as microservices with java plugin are usually in some container within internal network I'm not too concern about security more about consistency. 
At least it should be reflected in documentation. 
Question  I got from client - as long as we have lagom endpoints like :9000/api/datacenters will we have metrics for this page available on :9001/api/datacenters?

**Comment by brian-brazil** [comment]
I can't help you with specific frameworks I'm afraid.

**Comment by agolubev** [comment]
Sorry, created ticket for wrong repo. Thanks for patience.
