### ISSUE TITLE
Wrong TextFormat output for histogram correct data

### ISSUE THREAD

**Issue by bbccccn** [prometheus/client_java#511]
Hello!

It seems that for at least versions `0.6`, `0.7` and master (tested on commit [
c33fab0](https://github.com/prometheus/client_java/commit/c33fab09d78d360128ad62e99d1880039e38b604)) TextFormat somehow calculates **wrong** amounts for histogram metrics _if_ execution of the code was quick enough.

Steps & testcase to reproduce:
1. Setup Histogram with some amount of buckets;
2. Observe code execution duration neither via `histogram.time()` or `histogram.startTimer()` & `timer.close()/timer.observeDuration()`. Important detail - execution time of measured code should be very small - I used `Thread.sleep(10)` for testing;
3. Call `TextFormat.write004(_,_)` with new `StringWriter` and `registry.metricFamilySamples()`
4. Check that instead of only one bucket value increased *all* buckets values increased.

What is strange is that for different time different buckets increased by 1.
In debug mode underlying array which holds all buckets values shows **correct** values.

Test example which failing available [here](https://github.com/bbccccn/client_java/commit/2a0be132732673890f35e48289bc2ceb14ebde61).

**Comment by brian-brazil** [comment]
This behaviour is correct, histograms are cumulative.

**Comment by bbccccn** [comment]
So, it's correct behavior for printer to show value of some certain bucket as sum of all previous buckets?

**Comment by brian-brazil** [comment]
Yes.

**Comment by bbccccn** [comment]
Thanks for explanation!
