### ISSUE TITLE
Feature request: Add ability to clear child's value of Counter object for pushgw

### ISSUE THREAD

**Issue by marimt** [prometheus/client_java#512]
When using the pushgw there is the ability to clear a counter collection object. This will clear all the children of the counter. However, what is needed is the ability to clear only the counter value a particular child of the counter object while keeping everything else (i.e. labelValues, labelNames) the same.

In the code below I am using a static registry and maintaining a map of collection objects where the key is the metric_name and the value is the collection object. Everything works fine except I cannot clear the child of a collection object when I need to. 

Below is a snippet of the functionality I'd like to accomplish:
```
samples = ((Counter) collector).collect();
Collector.MetricFamilySamples mySingleSample = samples.get(0);

for (Collector.MetricFamilySamples.Sample sample : samples.get(0).samples) {
  if (sample.labelValues.get(0).equals(myUniqueId)) {
  
  // *****Example of method signature*****
  sample.clear_value();
  }
}
```

Alternatively, children of a counter object can become public instead of protected to allow access to them.

Use case: Say we have 10 interfaces across 3 switches where each have in_pkts metric. I am getting the count of in_pkts of the interface. If the interface counters are reset by a human or by hardware reboot for 1 interface out of my 10 interfaces then my count needs to be cleared for only for that particular interface.

I talked on iirc with Julius and SuperQ and I understand that there are better options for scraping device metrics but, presently, what is needed is the ability to clear a child counter's value. 

**Bug Report**
What did you do?
`((Counter) collector).clear()`

**Comment by brian-brazil** [comment]
See https://github.com/prometheus/client_java#custom-collectors
