### ISSUE TITLE
[feature request]bounded multi gauge

### ISSUE THREAD

**Issue by riverbuilding** [prometheus/client_java#513]
1. case description:
use gauge to record time cost of service.
then prometheus scrape it with certain period.
since gauge is just one value, it is some certain value keeps while others are dropped. 

2. it is much convenient if bounded multi gauge is provided, which makes current gauge as one specific case of it: its size equals 1.

3. which ones should be kept while which ones should dropped can be a policy and could provide some default implements such as oldest used.

4. make it configurable when built gauge so that users can customrize it.

**Comment by brian-brazil** [comment]
This sounds like a very niche use case, you're free to build your own collectors in order to satisfy this need.

**Comment by riverbuilding** [comment]
got it. thanks
