### ISSUE TITLE
Pushgateway doRequest throws IO exception with http 200 response

### ISSUE THREAD

**Issue by zyxmn-rvu** [prometheus/client_java#517]
Hello,

I always get the following IO Exception when I push metrics to the pushgateway. The exception message is as follows.

```
IOException Response code from http://localhost:9091/metrics/job/job_name/instance/localhost was 200  io.prometheus.client.exporter.PushGateway.doRequest (PushGateway.java:273)
```

I noticed there was a recent change on the checking of the response code here https://github.com/prometheus/client_java/commit/ddf03f1a939d7c41659bdf7b4a150657ffa5cadb#diff-03479f39aa27f4338f7e985625fd388e.  

I am unclear how to diagnose this at the moment. Are there scenarios where we can get an IO exception for a 200 http response in this context ?

Thanks!

**Comment by brian-brazil** [comment]
What version of the Java client are you using?

**Comment by zyxmn-rvu** [comment]
Hi, I am using a clojure wrapper . Here is the link to the version .https://github.com/soundcloud/prometheus-clj/blob/master/project.clj#L11 . Seems to be 0.0.14

**Comment by brian-brazil** [comment]
You need 0.18.0.

**Comment by zyxmn-rvu** [comment]
I am assuming that was a mistype? Do you mean 0.0.18 or 0.8.0

**Comment by brian-brazil** [comment]
Oh sorry, 0.8.0.

**Comment by brian-brazil** [comment]
Did 0.8.0 resolve this for you?

**Comment by namsoo2** [comment]
I am using 0.9.0 and have the same problem.

```
errorCode: Response code from http://localhost:9091/metrics/job/service/phase/real/host/batch001 was 200

Exception: java.io.IOException: Response code from http://localhost:9091/metrics/job/service/phase/real/host/batch001 was 200
at io.prometheus.client.exporter.PushGateway.doRequest(PushGateway.java:325)
at io.prometheus.client.exporter.PushGateway.pushAdd(PushGateway.java:182)
at org.springframework.boot.actuate.metrics.export.prometheus.PrometheusPushGatewayManager.push(PrometheusPushGatewayManager.java:108)
at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
Location: org.springframework.boot.actuate.metrics.export.prometheus.PrometheusPushGatewayManager.push():119
```

![image](https://user-images.githubusercontent.com/14154661/85990145-87ecec80-ba2c-11ea-91ff-d37ffdc35e1b.png)

**Comment by brian-brazil** [comment]
I'm not seeing how the code can get there with a 200. Does the data end up in the pushgateway as expected?

**Comment by namsoo2** [comment]
@brian-brazil 
Yes, pushgateway contains all the data as expected.
Let me know if you need any information.

**Comment by namsoo2** [comment]
@brian-brazil 
In my project's gradle I set it as below
`compile("io.prometheus:simpleclient_pushgateway")`
And when confirmed by Intellij, it was 0.9.0.
So I was convinced that it was 0.9.0.
However, when I analyzed the built jar, it was 0.7.0.
I solved the problem by writing the version as below.
`compile("io.prometheus:simpleclient_pushgateway:0.9.0")`
Thank you.

**Comment by brian-brazil** [comment]
Okay, so using the older version then was the issue.

**Comment by javaDer** [comment]
oh yes , Yes, I use 0.9.0 , problem solving  
![image](https://user-images.githubusercontent.com/10390876/88748824-91c95300-d184-11ea-945a-73e7ce2f7116.png)
