### ISSUE TITLE
Improve error reporting upon inconsistent metrics

### ISSUE THREAD

**Issue by BigCrunsh** [prometheus/client_java#52]
If a registry containing metrics with duplicate names is pushed, a 500 is returned:

``` java
CollectorRegistry pushRegistry = new CollectorRegistry();
Gauge g1 = (Gauge) Gauge.build().name("g1").help("blah1").register(pushRegistry);
Gauge g2 = (Gauge) Gauge.build().name("g1").help("blah2").register(pushRegistry);

PushGateway pg = new PushGateway(address)
pg.push(pushRegistry, "job", "instance");
```

The error is not meaningful and I actually would expect that an error is thrown already when registering gauge g2.

This is related to [Issue 14](https://github.com/prometheus/pushgateway/issues/14) in the prometheus/pushgateway repo.

**Comment by BigCrunsh** [comment]
> it's not possible to check in the general case as a Collector may export any metric

@brian-brazil: but it should be possible for inconsistencies that lead directly to errors in prometheus, right? E.g., ``register`` in [CollectorRegistry](https://github.com/prometheus/client_java/blob/master/simpleclient/src/main/java/io/prometheus/client/CollectorRegistry.java#L36) swallows the return value that is false if a collector cannot be added.

**Comment by brian-brazil** [comment]
In the simpleclient, a Collector can always be added to a CollectorRegistry. No exceptions are currently thrown in that case, so there's no errors to be swallowed.

I've a suspicion this is a case of the pushgateway being overly strict in what it accepts.

**Comment by BigCrunsh** [comment]
> I've a suspicion this is a case of the pushgateway being overly strict in what it accepts.

@brian-brazil: Regarding to the example above, does it makes sense to register two gauges with the same name? In my case it was a copy&paste error.

**Comment by brian-brazil** [comment]
It's an error to do so, the only time I can think of where you could make that work is if two modules were being careful to avoid clashing on labels - but they should be using the same Gauge in that case,

Where it gets tricky is if two completely separate bits of code use the same metric name, as you have the option of breaking just that metric or the entire binary.

**Comment by juliusv** [comment]
The Go client library goes to quite some lengths here to ensure that the same metric may be exported by different parts of the same binary, but not with the same set of labels. Not sure if that's something that should/could be done for the Java one as well?

**Comment by juliusv** [comment]
Just as a reference, the `Desc` type is used to ensure this consistency in the Go client library: http://godoc.org/github.com/prometheus/client_golang/prometheus#Desc

**Comment by brian-brazil** [comment]
The go client is overly restrictive as it doesn't allow for dynamic metric names, I had to bypass that in the node_exporter for example. A different design is needed, it'll always be a bit best effort when it comes to custom collectors but we can do something useful at least for the primary metrics.

This will all fall out naturally when we add support for exporting a subset of metrics.

> that the same metric may be exported by different parts of the same binary, but not with the same set of labels.

That shouldn't be allowed.

**Comment by juliusv** [comment]
>> that the same metric may be exported by different parts of the same binary, but not with the same set of labels.
>
> That shouldn't be allowed.

That's a question for @beorn7 then, but I think there were legitimate use cases for this.

**Comment by beorn7** [comment]
> This will all fall out naturally when we add support for exporting a subset of metrics.

Intriguing. Could you shed some light on the context here?

**Comment by brian-brazil** [comment]
>>This will all fall out naturally when we add support for exporting a subset of metrics.
Intriguing. 
>Could you shed some light on the context here?

In order to select only the Collectors needed to provide the subset, we need a mapping from metric names to collectors. Having such a mapping is also where you can implement a restriction on duplicate names.

>>> that the same metric may be exported by different parts of the same binary, but not with the same set of labels.
>> That shouldn't be allowed.
> That's a question for @beorn7 then, but I think there were legitimate use cases for this.

There's use cases for exporting the to the same metric from different parts of the codebase, I'd be very wary of allowing that via separate metric objects.

**Comment by beorn7** [comment]
@brian-brazil OK, got it. And yes, that's the way it is done in `client_golang`.

`client_golang` even allows to export metrics with the same name from different parts of the code while enforcing the same label set, but you have to provide different const value labels.... Anyway, power user shit... :)

**Comment by beorn7** [comment]
And yes, `client_golang` will be extended to allow metrics registration by prefix, or even an "unchecked" registration where you can collect anything at your own risk.
