### ISSUE TITLE
When use the java agent there are too many MetricFamilySamples$Sample in the heap

### ISSUE THREAD

**Issue by mingyuanzhu** [prometheus/client_java#523]
I used the javaagent to get some metrics like `java -javaagent:/opt/jmx_exporter/jmx_prometheus_javaagent.jar=8080 ...`, the version is 0.8.0
With the service running day by day we found the CPU usage is increase like this
![image](https://user-images.githubusercontent.com/6222056/73429795-71f0d800-4377-11ea-8f84-fa9255d5f406.png)
And I checked the GC rate trend is same with the CPU increase.
![image](https://user-images.githubusercontent.com/6222056/73429941-c6945300-4377-11ea-9821-83c6ec32d7e8.png)
 And then I used the command `jmap -histo:live 1` to find there were more prometheus jmx relative objects. I am not sure is there an memory leak or it is normal case.
![image](https://user-images.githubusercontent.com/6222056/73430318-b7fa6b80-4378-11ea-9223-86c0cff4f9a2.png)

And after I restarted the service and use `jmap` again, I can not find too many prometheus objects.

**Comment by brian-brazil** [comment]
Are you seeing this only with the jmx exporter, or client_java generally? Do you have a build up of network sockets too?

**Comment by mingyuanzhu** [comment]
> Are you seeing this only with the jmx exporter, or client_java generally? Do you have a build up of network sockets too?

I am not sure what do you mean the build-up of network sockets? The service is a HTTP API service.

**Comment by brian-brazil** [comment]
Exactly what I said, are their open network sockets to the exporter? The only way I can think of offhand of this being possible is that we're waiting to send metrics to a buildup of clients who aren't responding.

**Comment by mingyuanzhu** [comment]
Yes, I think the Prometheus server collected these metrics. You can see the above screenshot about the GC. These metrics are collected from the Prometheus JMX_exporter.

**Comment by mingyuanzhu** [comment]
Sorry I think the issue does not cause by the agent. Thanks very much.

**Comment by javicg** [comment]
@mingyuanzhu would you mind sharing more details as to what exactly caused the issue? We are facing the same problem, and it would be good to have a resolution here for future reference.
Thanks in advance.
