### ISSUE TITLE
SimpleTimer#defaultTimeProvider make public to allow easier replacement by clients

### ISSUE THREAD

**Issue by kuzkdmy** [prometheus/client_java#524]
System.nanoTime call is extremely slow 
summary.startTimer and then timer.observeDuration results in 2 calls for nanoTime
We have manually seen this on our test reporting with 100K rows * (5-7 data enrichment call for each row) that our Instrumented thread pools that do observeDuration are ~ 1 minute, but without observeDuration ~ 8 seconds.
Sure that there is a need to investigate a lot and benchmark, but also seems that the easiest first change can be just make SimpleTimer to be public static defaultTimeProvider field, this will allows for clients to change it without reflection.
```
public class SimpleTimer {
  static TimeProvider defaultTimeProvider = new TimeProvider();
}
```
Thanks

**Comment by brian-brazil** [comment]
This sounds like an issue with your JVM/OS, this should be adding only 10-20ms per our benchmarks.

If you have more niche needs then you're probably best providing your own timer class.

**Comment by kuzkdmy** [comment]
This is not local problem with OS/JVM, we have seen this locally on Mac and Linux with OpenJDK and GraalVM and on production as RPM packaged on Linux bare metal.
https://www.javaadvent.com/2019/12/measuring-time-from-java-to-kernel-and-back.html
Good explanation article of the nano calls, and os.

**Comment by brian-brazil** [comment]
You're not going to get anything faster or more precise than nanoTime. If you're not using TSC then that's something that needs resolving outside of this codebase.

**Comment by brian-brazil** [comment]
I don't think there's anything we can do here, this sounds like a local deployment issue.
