### ISSUE TITLE
Dropwizard prometheus do not evaluate URI template

### ISSUE THREAD

**Issue by alexandernajafi** [prometheus/client_java#528]
Not sure if this is the correct forum, please redirect me otherwise. 

I have a Dropwizard application that exposes metrics to prometheus using the dependencies below. However, if I create an endpoint GET /v1/book/{Id} and annotate the resource method with `@Timed` the metrics exposed in prometheus contains the evaluated request parameters. How can I expose the metric with the template instead?

For example, if I do two requests, one for /v1/book/a and one for /v1/book/b, two metrics will be exposed in prometheus (counter, timer and buckets) instead of one for /v1/book/{ID}. How can I achieve this behavior?

My dependencies:
```
<dependency>
            <groupId>io.dropwizard.metrics</groupId>
            <artifactId>metrics-core</artifactId>
            <version>4.1.0</version>
</dependency>
<dependency>
            <groupId>io.prometheus</groupId>
            <artifactId>simpleclient_dropwizard</artifactId>
            <version>0.6.0</version>
</dependency>
<dependency>
            <groupId>io.prometheus</groupId>
            <artifactId>simpleclient_servlet</artifactId>
            <version>0.6.0</version>
</dependency>
```

This is how I set it up. 
```
private void registerMetrics(Environment environment) {
        CollectorRegistry collectorRegistry = new CollectorRegistry();
        collectorRegistry.register(new DropwizardExports(environment.metrics()));
        environment.admin().addServlet("metrics", new MetricsServlet(collectorRegistry))
                   .addMapping("/metrics");

        environment.jersey().register(new InstrumentedResourceMethodApplicationListener(environment.metrics()));
        environment.jersey().register(new ExceptionCounterFilter(environment.metrics()));
    }
```

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
