### ISSUE TITLE
Make HTTPMetricHandler public

### ISSUE THREAD

**Issue by janssk1** [prometheus/client_java#529]
The HTTPServer is nice little server exposing stats. 
However, it would be even better if i can easily expose metrics in a (sun) HTTP server that i control myself. Then i can setup the server the way i want (eg include other handlers)
In this case, i only need the httpmetricHandler from the prometheus client library, but unfortunately the handler is package private

**Comment by brian-brazil** [comment]
Would you like to send a PR?

**Comment by janssk1** [comment]
Sure
