### ISSUE TITLE
log4j2 appender should allow counter name to be set via config

### ISSUE THREAD

**Issue by travisspencer** [prometheus/client_java#538]
The log4j2 appender should allow an admin to set the counter name via config instead of always hard coding it to `log4j2_appender_total`. This, together with the fix for #536 , will allow an admin to add multiple appenders with different filters to track log counts separately.

**Comment by brian-brazil** [comment]
That's getting a bit niche, if you're able to do that then adding counters directly to the code would be a better option.

**Comment by travisspencer** [comment]
Another use case is we want our counters to always start with `our-product-*`. Then, in Grafana, it's easy to find them all, including those made by this plugin. We just search for our prefix.

I don't think this is niche at all. That's 2 use cases, the code change is small, and it's not a breaking change -- as you'll see in a sec when I put up the PR.

**Comment by brian-brazil** [comment]
> Another use case is we want our counters to always start with our-product-*. 

That's for target labels, not metric names.

This module is intended for noticing if the overall number of log lines has a big change, if you want more granular than that they direct instrumentation is more appropriate.

**Comment by travisspencer** [comment]
Let me explain a bit more because I'm not sure you're getting my point. (If you are, please read on anyway.)

We use this module in our product. Our product has LOTS of metrics; they all start with `idsvr*`. We want to also capture log counts (trace, debug, etc.) just as this module already does. However, we want them to show up grouped together with our other metrics, not under `log4j2_appender_total`. So, we have this now:

```
idsvr_http_server_request_time_count 1.0
idsvr_http_server_request_time_sum 1.091628703
# HELP idsvr_oauth_delegation_issued Delegation issued event counter
# TYPE idsvr_oauth_delegation_issued counter
idsvr_oauth_delegation_issued{client_id="client-one",} 1.0
# HELP idsvr_oauth_token_issued OAuth token issued event counter
# TYPE idsvr_oauth_token_issued counter
idsvr_oauth_token_issued{client_id="client-one",token_type="access",} 1.0
# HELP idsvr_jvm_memory_used Used memory (bytes)
# TYPE idsvr_jvm_memory_used gauge
idsvr_jvm_memory_used{memory_id="Code Cache",memory_area="Non-heap memory",} 1.97456E7
idsvr_jvm_memory_used{memory_id="G1 Survivor Space",memory_area="Heap memory",} 1.8874368E7
idsvr_jvm_memory_used{memory_id="G1 Eden Space",memory_area="Heap memory",} 4.2991616E7
idsvr_jvm_memory_used{memory_id="G1 Old Gen",memory_area="Heap memory",} 2.7493368E7
idsvr_jvm_memory_used{memory_id="Compressed Class Space",memory_area="Non-heap memory",} 8609136.0
idsvr_jvm_memory_used{memory_id="Metaspace",memory_area="Non-heap memory",} 6.2669976E7
# HELP log4j2_appender_total Log4j2 log statements at various log levels
# TYPE log4j2_appender_total counter
log4j2_appender_total{level="debug",} 34466.0
log4j2_appender_total{level="warn",} 4.0
log4j2_appender_total{level="trace",} 95583.0
log4j2_appender_total{level="error",} 0.0
log4j2_appender_total{level="fatal",} 0.0
log4j2_appender_total{level="info",} 7118.0
etc.
```

What we want is this:

```
idsvr_http_server_request_time_count 1.0
idsvr_http_server_request_time_sum 1.091628703
# HELP idsvr_oauth_delegation_issued Delegation issued event counter
# TYPE idsvr_oauth_delegation_issued counter
idsvr_oauth_delegation_issued{client_id="client-one",} 1.0
# HELP idsvr_oauth_token_issued OAuth token issued event counter
# TYPE idsvr_oauth_token_issued counter
idsvr_oauth_token_issued{client_id="client-one",token_type="access",} 1.0
# HELP idsvr_jvm_memory_used Used memory (bytes)
# TYPE idsvr_jvm_memory_used gauge
idsvr_jvm_memory_used{memory_id="Code Cache",memory_area="Non-heap memory",} 1.97456E7
idsvr_jvm_memory_used{memory_id="G1 Survivor Space",memory_area="Heap memory",} 1.8874368E7
idsvr_jvm_memory_used{memory_id="G1 Eden Space",memory_area="Heap memory",} 4.2991616E7
idsvr_jvm_memory_used{memory_id="G1 Old Gen",memory_area="Heap memory",} 2.7493368E7
idsvr_jvm_memory_used{memory_id="Compressed Class Space",memory_area="Non-heap memory",} 8609136.0
idsvr_jvm_memory_used{memory_id="Metaspace",memory_area="Non-heap memory",} 6.2669976E7
# HELP log4j2_appender_total Log4j2 log statements at various log levels
# TYPE log4j2_appender_total counter
idsvr_logs_total{level="debug",} 34466.0
idsvr_logs_total{level="warn",} 4.0
idsvr_logs_total{level="trace",} 95583.0
idsvr_logs_total{level="error",} 0.0
idsvr_logs_total{level="fatal",} 0.0
idsvr_logs_total{level="info",} 7118.0
etc.
```

This should be possible by configuring log4j like this:

```xml
<Appenders>
        <Prometheus name="metrics" counterName="idsvr_logs_total"/>
</Appenders>
```

When that `counterName` attribute isn't set, nothing changes in existing deployments.

**Comment by brian-brazil** [comment]
This is not what metric names are for, nor should you be prefixing anything else not directly coming from your code such as the JVM metrics. See https://www.robustperception.io/target-labels-not-metric-name-prefixes

**Comment by travisspencer** [comment]
When our product runs in K8S, there's dozens or 100's of metrics on the Prometheus endpoint. It's too hard to find the ones that don't come from our product if they're not prefixed. Effectively, the metrics produced from this module are part of our product (from the perspective of the customer), since it's reporting on logs from our product.

I don't see why you're digger your heals in so hard about this. It's an opt-in feature, it's not a breaking change for existing deployments, it enables multiple new use cases. What is the problem here? Ideology?

**Comment by brian-brazil** [comment]
The use cases you intend to use this for appear to be anti-patterns, thus I'm reluctant to add it.

**Comment by travisspencer** [comment]
```xml
<Appenders>
    <Prometheus name="metrics" counterName="idsvr_logs_total">
        <filters>
                <MarkerFilter marker="REQUEST" onMatch="DENY" onMismatch="ACCEPT"/>
        </filters>
    </Prometheus>
    <Prometheus name="metrics" counterName="idsvr_request_logs_total">
        <filters>
                <MarkerFilter marker="REQUEST" onMatch="ACCEPT" onMismatch="DENY"/>
        </filters>
    </Prometheus>
</Appenders>
```
With this, I then have these counters:
```
idsvr_logs_total{level="debug",} 34466.0
idsvr_logs_total{level="warn",} 4.0
idsvr_logs_total{level="trace",} 95583.0
idsvr_logs_total{level="error",} 0.0
idsvr_logs_total{level="fatal",} 0.0
idsvr_logs_total{level="info",} 7118.0

idsvr_request_logs_total{level="info",} 10000.0
```

Request logs can now be filtered out (with the fix from the other PR) and this new name allows for counting only logs marked with a particular marker. 

This doesn't seem like an anit-pattern to me. Seems like very useful stuff.

**Comment by brian-brazil** [comment]
If you're getting that granular that looks like you're using logs as a metric event transport, which isn't exactly efficient. This would be better served by using direct instrumentation.

**Comment by travisspencer** [comment]
I have rewritten the appender to add this feature and filtering support. I'll just use my code then.
