### ISSUE TITLE
pushgateway java api Gauge can not set same name

### ISSUE THREAD

**Issue by gjie1991** [prometheus/client_java#546]
CollectorRegistry test = new CollectorRegistry();
        Gauge guage1 = Gauge.build("java_lang_G1_Young_Generation_LastGcInfo_memoryUsageBeforeGc_used", "TYPE java_lang_G1_Young_Generation_LastGcInfo_memoryUsageBeforeGc_used untyped")
                .labelNames("type", "key")
                .create();
        guage1.labels("GarbageCollector", "CodeHeap 'profiled nmethods")
        .set(6777088.0);
        guage1.register(test);

        Gauge guage2 = Gauge.build("java_lang_G1_Young_Generation_LastGcInfo_memoryUsageBeforeGc_used", "TYPE java_lang_G1_Young_Generation_LastGcInfo_memoryUsageBeforeGc_used untyped")
                .labelNames("type", "key")
                .create();
        guage2.labels("GarbageCollector", "G1 Old Gen")
                .set(3466752.0);
        guage2.register(test);

        pg.push(test,"test");

Exception in thread "main" java.lang.IllegalArgumentException: Collector already registered that provides name: java_lang_G1_Young_Generation_LastGcInfo_memoryUsageBeforeGc_used
	at io.prometheus.client.CollectorRegistry.register(CollectorRegistry.java:54)
	at io.prometheus.client.Collector.register(Collector.java:139)

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
