### ISSUE TITLE
Memory leak in CKMSQuantiles.java

### ISSUE THREAD

**Issue by grksharma999** [prometheus/client_java#550]
This issue is more related to Memory leak in CKMSQuantiles.java? #422
I am getting this issue on a CKMSQuantiles$Quantile

**Comment by brian-brazil** [comment]
Can you provide more details?

**Comment by grksharma999** [comment]
My application is running on Tomcat JVM. With increasing in requests/second to my application there is a memory leak in the JVM the memory is not getting released. Per my analysis the CollectorRegistry class usage causing the CKMSQuantiles$Quantile objects are not released.

The Heap dump in regular intervals show the leak suspect of 95% on the class CKMSQuantiles$Quantile.

**Comment by brian-brazil** [comment]
Can you share graphs and code?

**Comment by grksharma999** [comment]
Unfortunately I cannot share them as per the policies of my organization. But I observed it is pretty similar to the graphs of the issue #422

**Comment by grksharma999** [comment]
Unfortunately I cannot share them as per the policies of my organization. But I observed it is pretty similar to the graphs of the issue #422

**Comment by brian-brazil** [comment]
That wasn't an issue with client_java. I'm afraid without data, there's not much we can do.

**Comment by brian-brazil** [comment]
Lacking information there's not much we can do here, and it's likely this code will be replaced at some point anyway.
