### ISSUE TITLE
Add .set method on counters

### ISSUE THREAD

**Issue by phemmer** [prometheus/client_java#554]
It's entirely possible I'm missing something, but counters seem to be unable to handle certain use cases because of their lack of a `.set()` method. I understand that counters *should* only ever increase, thus only having `.inc()` would seem to make sense. But they *can* decrease. The prometheus [`rate()` function](https://prometheus.io/docs/prometheus/latest/querying/functions/#rate) handles for reductions in the value by assuming a reset from 0.

In my case, the metric I'm pulling is an absolute value (meaning I retrieve the total, not the difference each poll) from an external source. Now naively I might do `counter.inc(absVal - counter.get())`. However the value I am reading is an integer which overflows/wraps, and when this happens, the calculation becomes negative (which `.inc()` has a check for and throws an exception).

I can think of 3 ways to compensate for this:
1. I can manually check if `absVal < counter.get()` and when seen, unregister the counter and create a new one. This is crude.
2. keep track of the last `absVal` outside of the counter, and when it wraps, reset the "last" value to `0`, and send the current value to `counter.inc()`. This is complex/messy.
3. Do some arithmetic (modulo) shenanigans. Also complex, but maybe least so.

The `counter` type stores the absolute value internally, so it would be much simpler if a `.set()` method were added instead of having to deal with only having `.inc()`.  
Alternatively `.inc()` could remove the negative value check so it stops throwing exceptions.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by phemmer** [comment]
This wasn't a question. It was a feature request.

**Comment by beorn7** [comment]
What @brian-brazil probably meant to say is the following: “Counters deliberately don't allow `set()` or `dec()`. If you want to understand why, asking that question on the prometheus-users mailing list is a great idea.”
