### ISSUE TITLE
Memory Leak on Histogram Timer

### ISSUE THREAD

**Issue by Unniboy** [prometheus/client_java#562]
Hi Folks,

Upon running a static analyzer code, I get a memory leak reported on the `Histogram.Timer` when I don't want to use the `close` method, but the `observeDuration` to get the value of the metric.

The `Histogram.Timer` is implemented as a `Closeable`, but the `close` method just calls `observeDuration`. I believe there is no system resource getting used in `Timer` which requires to be closed.

Therefore, is this resource leak a false positive?

_Note: Upon using `close`, the resource leak is no more reported._

**Comment by brian-brazil** [comment]
That's a false positive, the only resource is the object itself.
