### ISSUE TITLE
Maven artifactId  naming problem

### ISSUE THREAD

**Issue by Guohao1020** [prometheus/client_java#565]
Hi,
>Its artifactId name is bad, which causes dependency errors, and the Maven naming specification can be viewed at https://maven.apache.org/guides/mini/guide-naming-conventions.html Dependencies such as the following will cause the corresponding version not to be found.ArtifactId can only be used in lowercase and special characters can only be used **-** not  **_**

```
<!-- Hotspot JVM metrics-->
<dependency>
  <groupId>io.prometheus</groupId>
  <artifactId>simpleclient_hotspot</artifactId>
  <version>0.9.0</version>
</dependency>
<!-- Exposition HTTPServer-->
<dependency>
  <groupId>io.prometheus</groupId>
  <artifactId>simpleclient_httpserver</artifactId>
  <version>0.9.0</version>
</dependency>
<!-- Pushgateway exposition-->
<dependency>
  <groupId>io.prometheus</groupId>
  <artifactId>simpleclient_pushgateway</artifactId>
  <version>0.9.0</version>
</dependency>
```

**Comment by brian-brazil** [comment]
Can you explain more about what you're reporting?

**Comment by brian-brazil** [comment]
I've not heard back from you and see no issues per that page, so closing.
