### ISSUE TITLE
NPE setting .labelNames while using Gauge.build()

### ISSUE THREAD

**Issue by imranansari** [prometheus/client_java#569]
Hello,

Not sure why I get a NPE when setting the `labelNames`, I'm able to provide labels just fine using the REST API directly but not with the Java Client, skipping the labels in Java does work fine as well, what gives ?

```java
        CollectorRegistry registry = new CollectorRegistry();
        final Gauge duration = Gauge.build()
                .name(metricName)
                .labelNames("l1", "l2")
                .help("Duration in seconds.")
                .register(registry)
        Gauge.Timer durationTimer = duration.startTimer();
```

```sh
java.lang.NullPointerException
	at io.prometheus.client.Gauge.startTimer(Gauge.java:283)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by alexklibisz** [comment]
@imranansari Did you ever figure this out? Looks like nobody responded on the mailing list.

**Comment by alexklibisz** [comment]
Ok, figured it out. You have to call `.labels(...).set(metricValue)` as one call, rather than separate calls to `.labels(...)` and `.set(metricValue)`.
