### ISSUE TITLE
“annotation-based metrics” feature 

### ISSUE THREAD

**Issue by lemon-simple** [prometheus/client_java#571]
hi，is there a plan to do a “annotation-based metrics” feature ？I did some，and used in prod env .  How about I submit this feature?

**Comment by brian-brazil** [comment]
There's not, as that'd require a specific build setup on the part of users. You can of course build such a thing on top of this library.

**Comment by lemon-simple** [comment]
> There's not, as that'd require a specific build setup on the part of users. You can of course build such a thing on top of this library.

ok. i'll Submit this new feature later. Do U have any suggestions ?

**Comment by brian-brazil** [comment]
Not particularly, as it's not a feature that is going to be here and it really depends on the ecosystem you're in.
