### ISSUE TITLE
Add support for OpenMetrics

### ISSUE THREAD

**Issue by joe-elliott** [prometheus/client_java#609]
The official go and python clients already support OM and the Ruby client has a [running issue](https://github.com/prometheus/client_ruby/issues/189) tracking progress.

The Java client is in wide use and it would benefit the Prometheus ecosystem for it to also support OM.

**Comment by brian-brazil** [comment]
I'm already working on this.

**Comment by berkus** [comment]
Hmm, PR link?

**Comment by fstab** [comment]
What's missing? OpenMetrics support is available since a long time. If you don't see it, it's likely because OM format is only produced if you request with the OM HTTP header:
```
curl -H 'Accept: application/openmetrics-text; version=1.0.0; charset=utf-8' http://localhost:8080/metrics
```

**Comment by berkus** [comment]
Oh, thanks @fstab 

I basically wanted to look into the java implementation, hence asked for a PR link. If you could point into the section of the code that implements openmetrics specifically that'd be helpful as well.

**Comment by fstab** [comment]
You can just search for an OpenMetrics type, like `Info`.

**Comment by berkus** [comment]
Thank you, will try that!
