### ISSUE TITLE
Jakarta Servlet 5.0

### ISSUE THREAD

**Issue by halset** [prometheus/client_java#610]
Looks like servlet-api are moving to jakarta package names. Any plans for upgrading client_java to support it? It will probably take several years before everyone is over, so perhaps we need parallel releases?

https://jakarta.ee/specifications/servlet/5.0/

**Comment by brian-brazil** [comment]
What would it involve? Is there something in there that would break existing users of it? What would be the benefits? This library supports back to Java 6, so that has to be kept working.

**Comment by halset** [comment]
There are new package names for the servlet stuff. The new API uses `jakarta.servlet` instead of `javax.servlet`.

Perhaps copying over `simpleclient_servlet` to `simpleclient_servlet-servetletapi5` and let the user choose?

Or people can just create their own copy of the MetricsServlet using the new API. Luckily, it is very small.

**Comment by brian-brazil** [comment]
If it's just a rename then I would presume that there's an adapter out there for it. We already have quite a few different HTTP exposition options, i'd rather not add more if we don't have to.

**Comment by halset** [comment]
Okay. I do not think it is just a rename, but there are not other changes for MetricsServlet at least. Not fixing this here is fine with me as I can just have my own copy of MetricsServlet with this change locally in each project. This is quite new to me as I just discovered this by reading up on jetty 10 and jetty 11.

**Comment by brian-brazil** [comment]
I'd recommend against copying, as this code will be changing in the near future to handle OpenMetrics negotiation.

**Comment by lfgod** [comment]
We have a similar situation in our project as we are moving from javax.* (Jetty 9.x ) to jakarta.*(Jetty 11)  . We use the simpleclient_servlet jar which use javax.*.  The quick solution for us would be to copy and refactor the import statements to use jakarta.* instead of javax.*. However we would prefer to use a new simpleclient_servlet_jakarta.  It would be great if we can have client with jakarta support. Thanks in adavance.

**Comment by mmadoo** [comment]
I have created the pull request https://github.com/prometheus/client_java/pull/647 for this.

**Comment by jonathanl-telenav** [comment]
Is there any chance we could get this PR merged? Thanks -- Jon

**Comment by fstab** [comment]
Isn't it this one? Or am I confusing things? https://github.com/prometheus/client_java/tree/main/simpleclient_servlet_jakarta

**Comment by jonathanl-telenav** [comment]
thanks!
