### ISSUE TITLE
Dropwizard client quantile label naming

### ISSUE THREAD

**Issue by alexandernajafi** [prometheus/client_java#621]
In the [DropwizardExports](https://github.com/prometheus/client_java/blob/0fa8ad630df972f3c44550e073878debb9bd02f6/simpleclient_dropwizard/src/main/java/io/prometheus/client/dropwizard/DropwizardExports.java#L120) file, in the method [fromSnapshotAndCount](https://github.com/prometheus/client_java/blob/0fa8ad630df972f3c44550e073878debb9bd02f6/simpleclient_dropwizard/src/main/java/io/prometheus/client/dropwizard/DropwizardExports.java#L120) we see that the quantiles are exported as

```
sampleBuilder.createSample(dropwizardName, "", Arrays.asList("quantile"), Arrays.asList("0.5"), snapshot.getMedian() * factor)
```

Could we change the name of the label from `quantile` to `le` as Prometheus `histogram_quantile` requires the label to be named `le`. What is the intention behind this naming or could it be configured maybe? Or am I missing something?

**Comment by brian-brazil** [comment]
Quantiles are not histograms, this would not be correct. You can't do math on quantiles - you have to use them as-is.

**Comment by alexandernajafi** [comment]
I see, thank you for your quick reply. I'll close this issue.
