### ISSUE TITLE
Cannot restrict the size of SimpleCollector.children.

### ISSUE THREAD

**Issue by CrazyJoey** [prometheus/client_java#625]
Hi, 
Is it possible to get  the size of SimpleCollector.children.

```java
private String[] labelNames = new String[]{"serviceName", "endpoint", "requestType"};

Gauge gauge = Gauge.build()
                    .name("service_metric")
                    .help("Service Metric")
                    .labelNames(labelNames)
                    .create();

```

To avoid oom, we need to check the size of children when inc Gauge metric.
```
public void collect(String[] labels, double rt) {
    if (gauge.getChildren().size() < 10000) { //to provide method  like this
        gauge.labels(labels).inc(rt);
    }
}

```

**Comment by tomwilkie** [comment]
Hi @CrazyJoey! It sounds like you're using potentially unbounded label values?  This is an anti-pattern in Prometheus: you should guarantee the cardinality of your labels values our bounded by eg not include raw HTTP paths, user id etc.  

See https://prometheus.io/docs/practices/naming/#labels for more info.
