### ISSUE TITLE
TextFormat: Provide an easy way of mutating the values written

### ISSUE THREAD

**Issue by bjung82** [prometheus/client_java#627]
Hi,

a quite common use case is (should be!) testing the whole alertchain:
we provide Prometheus-metrics and use prometheus + alertmanager for
building alertchains. It is really hard to test these chains (initially). All depends
on the value in the exported metric, finally. By providing a simple interface that allows
mutating the value written, we could really improve the situation of testing the whole
alertchain, end-to-end.

I will provide a PR for this.

Regards
Benjamin

**Comment by fstab** [comment]
Thanks for the PR. Let's continue the discussion there. #628
