### ISSUE TITLE
Version 0.10.0 suffixes counter names with "_total" and "_created"

### ISSUE THREAD

**Issue by s4nk** [prometheus/client_java#629]
I noticed that in version 0.10.0 creating a Counter called "foo" and transforming it to text using `TextFormat.write004` results in the output containing 2 records: one called `foo_total` and another called `foo_created`. Previously there would be just one record called `foo`. Is this intentional?

**Comment by fstab** [comment]
From the release notes
> With this release the client_java simpleclient switches to the OpenMetrics data model and adds support for various new OpenMetrics-related features. This should be largely seamless, however any counters which lack a _total suffix on their sample will now have it added. If you'd prefer to make that change more gradually, you should change your metric names before upgrading to this version.

So basically up to now it was just a naming convention that counters _should_ have a `_total` suffix, but with [OpenMetrics](https://github.com/OpenObservability/OpenMetrics/blob/master/specification/OpenMetrics.md) counters _must_ have a `_total` suffix, and the library will add it if it's missing.

The `_created` time was also introduced to comply with OpenMetrics, but that's not a breaking change. You can ignore it if you don't want to use it. It helps monitoring systems figure out when counters were reset to zero (for example after an application restart).
