### ISSUE TITLE
Avoid deploy path in the MetricsFilter

### ISSUE THREAD

**Issue by lapo-luchini** [prometheus/client_java#631]
Right now if I have a WAR using `MetricsFilter` on `/*` and deploy that under `/deployPoint` I get metrics content like:

```
projectName_requests_count{path="/deployPoint/api/listUser",method="GET",} 2.0
projectName_requests_sum{path="/deployPoint/api/listUser",method="GET",} 0.228438531
```

and if on a different server (or even the same) I have the same WAR deployed under `/anotherDeploy` I get metrics that are difficult to `SUM()` together, as they have a different `path` label, while being logically "the same metric".

I'd suggest changing like this:
```patch
-        String path = request.getRequestURI();
+        String path = request.getRequestURI().substring(request.getContextPath().length());
```

(also as suggested by @jfbreault in https://github.com/prometheus/client_java/pull/168#discussion_r91014868)

**Comment by lapo-luchini** [comment]
(also as suggested by @jfbreault in https://github.com/prometheus/client_java/pull/168#discussion_r91014868)

**Comment by fstab** [comment]
Hi Lapo, I see your point, but if we do this we might break things for other users who need to distinguish different contexts. Maybe we could introduce a `strip-context-path` configuration with `false` as the default (compatible with the current behavior), and strip the context path only if `strip-context-path` is `true`.

Would you like to create a PR for that?

**Comment by lapo-luchini** [comment]
That seems like the best approach. I will create a PR momentarily.
