### ISSUE TITLE
Support request and response timeouts in HTTPServer

### ISSUE THREAD

**Issue by perlun** [prometheus/client_java#636]
### Problem description

The `com.sun.net.httpserver.HttpServer` as used by `io.prometheus.client.exporter.HTTPServer` does not, by default, use any request and response timeouts at all. This means that an HTTP server set up with a limited amount of threads (say, 1 or 5) can easily be fully blocked by a malicious/misconfigured client (or a network failure), indefinitely.

We have seen this ourselves with a custom Prometheus publisher in our code (which also uses `com.sun.net.httpserver.HttpServer`), and the slightly naïve approach we took was attempting to override the default timeouts in our code using a static initializer:

```java
    static {
        System.setProperty( "sun.net.httpserver.maxReqTime", "60" );
        System.setProperty( "sun.net.httpserver.maxRspTime", "600" );
    }
```

_However_, because we also use [the Prometheus JMX exporter](https://github.com/prometheus/jmx_exporter) which in turn uses `simpleclient_httpserver` under the hood, the JMX exporter agent runs before our own code (presumably because of how Java agents work in the JVM) => it becomes impossible to override the request and response timeouts using the approach above. Here's the stack trace for when `sun.net.httpserver.ServerConfig` gets initialized (after which it becomes impossible to override these properties):

![image](https://user-images.githubusercontent.com/630613/110440725-a62de080-80c1-11eb-90db-50bf242e527d.png)

### Workaround

Set `-Dsun.net.httpserver.maxReqTime=60 -Dsun.net.httpserver.maxRspTime=600` on the command line instead; it will then apply to all use cases of `com.sun.net.httpserver.HttpServer` withinin the Java runmtime in question.

### Suggested changes

I am creating this issue to raise awareness of the problem and discuss potential ways to improve this before spending any time on a potential PR.

Personally, I think it's a bit problematic to rely on the JDK defaults in this case; it would make sense to set up some reasonable defaults in case the user hasn't set these system properties (since I'd claim it's rather unlikely that the user actually wants an "infinite" request/response timeout" like this). 

One important question then  is whether this should be done in `io.prometheus.client.exporter.HTTPServer` or taken care of by the JMX exporter? Feel free to suggest what you think would make most sense. :+1:

**Comment by fstab** [comment]
Thanks for the suggestion. I agree, a timeout makes sense. I think the best place to do it is in `io.prometheus.client.exporter.HTTPServer`. You must make sure to set the system properties before the `sun.net.httpserver.ServerConfig` class is loaded. A PR would be awesome.

**Comment by perlun** [comment]
> A PR would be awesome.

Here we go: https://github.com/prometheus/client_java/pull/643
