### ISSUE TITLE
"_sum" is not being generated for Dropwizard Histogram and Summary Metrics.

### ISSUE THREAD

**Issue by askant98** [prometheus/client_java#638]
We are using Dropwizard metrics with OpenTelemetry+Prometheus Receiver. We are generating metrics in Prometheus Exp format using the client_java module. All metrics work as expected except the Summary and Histograms. **_sum** counter must be generated for Summary and Histogram metrics for this to be compatible with OpenTelemetry. The value can be "zero" for _sum counter.

**Comment by fstab** [comment]
Is there any API in Dropwizard histograms to get the sum? If they don't provide a sum I don't know where we could get it from.

**Comment by askant98** [comment]
True Dropwizard histograms do not track sum. Since it is unavailable, Can the sum be printed as "0" to ensure compatibility with Prometheus Exposition format?

**Comment by brian-brazil** [comment]
The Prometheus Exposition format does not require a sum, nor does OpenMetrics. The correct thing to do in cases like these is to not expose it.

**Comment by fstab** [comment]
Thanks Brian for clarifying.
