### ISSUE TITLE
Deprecate old client

### ISSUE THREAD

**Issue by beorn7** [prometheus/client_java#64]
At some point, we want to deprecate the old client and at the same time get rid of JSON (which is deprecated and only supported by the old client).

The new `simpleclient` is essentially missing two features:
- protobuf support (needed for scenarios where a server scrapes many samples, 100k+/sec)
- summary support

Both are not strictly mandatory, but in use right now. We have to vet if an implementation makes sense.

**Comment by brian-brazil** [comment]
My plan was to not implement either of those (text should be good enough, and we have histogram now), and to write a custom collector that'll let data from the original client be exposed via the simpleclient. This offers a sane transition path.

**Comment by beorn7** [comment]
We have to see how the usage of summaries over here develops. If nobody needs them, fine.

In my load tests, I could see that a busy server spends a significant time on parsing the scraped metric, and that was pure protobuf. Blowing that share up by a factor of ~6 will be significant in high-load scenarios. We have to vet how relevant this is. I expect the Java client to be the most widely used client, so we should at least be prepared for some users requiring protobuf one day.

**Comment by brian-brazil** [comment]
I'd hope to allow plugging in of protobuf exporter at some future point for those who need it.

**Comment by brian-brazil** [comment]
The old client was deprecated a while back.
