### ISSUE TITLE
0.10.0 introduced a breaking change on metric names without an option to disable it

### ISSUE THREAD

**Issue by niwinz** [prometheus/client_java#640]
On my testing environment I have detected that many counters are suffixed with `_total` and added a new metric with `_created` suffix. After reading the release notes, I realized of the **breaking change**. Maybe some more emphasis on the BREAKING changed would be awesome.

In our case we don't want change our metric names, so we will not be able to upgrade to the latest versions :(

I think this kind of breaking changes should be introduced gradually, making them optional in any case.
A simple configuration flag on the registry will solve the issue.

**Comment by fstab** [comment]
Thanks for your feedback. It's too late to change this now, but the good news for the future is: `client_java` 0.10.0 implements the [OpenMetrics](https://openmetrics.io/) standard, so this will remain pretty stable in the future. So if you manage to update your metric names it will very likely be the last time you have to do this.

**Comment by niwinz** [comment]
I think you still have the option to add a flag for disable this new behavior for people on the same situation as me. As far as I know, prometheus does not support reniming existing metrics (maybe I'm wrong).

In the worse case and without an option to disable this new behavior, we probably will need to go to fork and vendor the 0.9.0 version, because changing the name right now is not an option.

**Comment by hirunatan** [comment]
Our problem is that we apparently cannot change the name of existing metrics. And If we create new metrics, we lose all previous data and everything starts from zero.

If there is a way of renaming metrics without losing data it would also be ok.

**Comment by BoopBoopBeepBoop** [comment]
Echoing the discontent on this one ... perhaps our fault for not picking up the breaking change in the release notes, but we just spent more than a little while trying to figure out why our dashboards were missing seemingly arbitrary subsets of metrics. Pretty significant breaking change anywhere that someone has a query wired to one of these metrics, I think.
