### ISSUE TITLE
documented for production metric names are changed by 0.10.0 client

### ISSUE THREAD

**Issue by ndimitry** [prometheus/client_java#649]
We use Prometheus to collect and store metrics (so, a big thanks for the effort maintaining and enhancing it).

At the moment a lot of names are already documented and used for years so for us this is not a desirable behaviour to have "_total" being added to each counter (this breaks both documentation and precreated Grafana dashboards).

Is there some way to keep names unchanged? Or maybe some flag could be introduced to keep compatibility? If not there should (I'm sure) be an idea behind that, in case so, please, explain it to me.

Thanks in advance for the reply!

**Comment by fstab** [comment]
Hi ndimitry, the idea is to become compatible with the [OpenMetrics](https://openmetrics.io/) standard. However, it might be good to introduce an "allow invalid counter names" flag in the next release so that people who cannot update their Grafana dashboards are not stuck forever with the previous release.

**Comment by ndimitry** [comment]
Hi @fstab , thank you for an explanation!
I think I will create a pull request to make it possible to allow invalid counter names.
Hopefully we will finally move to the new standard too. Do you know if there's a chance that the draft will change and "_total" suffix will be (for example) replaced by other suffix? I'm asking that to try to avoid cases when we adopt to the new standard and then run into the case when we need to further adupt to the newer changes.
