### ISSUE TITLE
SimpleCollector.Builder register's type inference goes wrong way

### ISSUE THREAD

**Issue by mwitkow-io** [prometheus/client_java#65]
This is a problem you can encounter mostly Scala. Because Scala does type inference for parameters, if you do:

```
val myCounter = Counter.build().name("foo").register()
```
it will have type `Nothing`

That's because the type inference introduced in
https://github.com/prometheus/client_java/commit/ed184d8e50c82e98bb2706723fff764424840c3a
cause it to infer the type from the assignment parameter, not from the type of Builder.

I'll send in a patch once I find some time to fix it.

**Comment by brian-brazil** [comment]
If it's too hard to tweak, I'm open to a PR to inline SimpleCollector.
