### ISSUE TITLE
simpleclient_graphite: To push data from prometheus client to graphite

### ISSUE THREAD

**Issue by rekhajoshm** [prometheus/client_java#66]
Use prometheus client and generate histograms and push that data to graphite.
Skip prometheus server layer.

**Comment by rekhajoshm** [comment]
Trying to create GraphiteFormat.java ( based on https://github.com/prometheus/client_java/blob/master/simpleclient_common/src/main/java/io/prometheus/client/exporter/common/TextFormat.java)
But if you [~bbrazil] can delegate it and get it done faster, would like that too :-)

**Comment by brian-brazil** [comment]
This has been implemented.
