### ISSUE TITLE
Implementing Exemplars

### ISSUE THREAD

**Issue by christian-morin** [prometheus/client_java#668]
Trying to implement Exemplars in my application. My application aggregates Traces, analyzes its contents and reports the summaries as Prometheus metrics. So my use-case is that I want to add trace_id and span_id to the prometheus values as Exemplars. But I can't get it to work...the Prometheus HTTP Server never adds the Exemplars to the output. Not sure how to get it working? (If possible?).

Importing client 0.11
```java
<dependency>
        <groupId>io.prometheus</groupId>
        <artifactId>simpleclient_httpserver</artifactId>
        <version>0.11.0</version>
</dependency>
```

Starting HTTP Server
```java
HTTPServer server = new HTTPServer(9090);
```

Adding a Simple Counter to my class
```java
public class NumberOfSpans {
  private static final Counter counter = Counter.build()
      .name("spans_total")
      .help("Number of spans")
          .withExemplars()
          .create()
      .register();
```

Updates the counter with dummy Exemplar
```java
counter.incWithExemplar("span_id", "abcdef", "trace_id", "123456");
```

But still, the Prometheus output is simply
```
# HELP spans_total Number of spans
# TYPE spans_total counter
spans_total 1.0

**Comment by fstab** [comment]
Did you choose the right `Accept:` header? Exemplars are supported by the OpenMetrics export format and not by the original text format. In order to get metrics in OpenMetrics format you need to set the `Accept:` header like this:

```
curl -H 'Accept: application/openmetrics-text; version=1.0.0; charset=utf-8' http://localhost:8080/metrics
```

**Comment by fstab** [comment]
I added this to README.md.

**Comment by christian-morin** [comment]
That was the missing piece. Thank you! Perfect adding it to the README, makes it easier to get up and going.
