### ISSUE TITLE
Trailing comma in output

### ISSUE THREAD

**Issue by weihao** [prometheus/client_java#675]
```
bungee_jvm_threads_state{state="NEW",} 0.0
bungee_jvm_threads_state{state="TIMED_WAITING",} 30.0
bungee_jvm_threads_state{state="TERMINATED",} 0.0
bungee_jvm_threads_state{state="RUNNABLE",} 23.0
bungee_jvm_threads_state{state="BLOCKED",} 0.0
bungee_jvm_threads_state{state="WAITING",} 16.0
# HELP bungee_online_players unique online players
# TYPE bungee_online_players gauge
bungee_online_players{server="lobby",} 0.0
bungee_online_players{server="smp",} 0.0
```
this is a trailing comma when `labelNames` variable is present. This can be reproduced using a custom collector.

**Comment by weihao** [comment]
https://github.com/prometheus/client_java/blob/70e0f5ab5bf8f8876a18c75d33d1c9dc4cac9232/simpleclient_common/src/main/java/io/prometheus/client/exporter/common/TextFormat.java#L231

The logic here skips the first label, and appends "," at the beginning of every other label.
So we want `{state="WAITING"}` in the output. But now it has a trailing comma which is unexpected

**Comment by fstab** [comment]
The trailing comma is intentional in the Prometheus text format. Quote from https://prometheus.io/docs/prometheus/latest/querying/operators/:
> label list is a list of unquoted labels that may include a trailing comma, i.e. both `(label1, label2)` and `(label1, label2,)` are valid syntax.

The new [OpenMetrics](https://openmetrics.io/) format does not have a trailing comma, so if you get your metrics with the following `Accept:` header you won't see that comma:
```
curl -H 'Accept: application/openmetrics-text; version=1.0.0; charset=utf-8' http://localhost:9999/metrics
```

**Comment by weihao** [comment]
@fstab thank you for the information
