### ISSUE TITLE
Are there any plans to consider supporting other trace systems  when adding Exemplar?

### ISSUE THREAD

**Issue by chenmudu** [prometheus/client_java#677]
It may seem that only Otel is supported, but there are cases where applications that use client_java to generate metrics are using other trace systems and have the same requirements.  Are there any plans to consider supporting other trace systems  when adding Exemplar? 

Thanks a lot.  Looking forward to your reply.

**Comment by fstab** [comment]
Yes. Ideally users of other systems will create PRs to add support for their tracers to `client_java`. The intention is to make this easy: `simpleclient_tracer_otel` has less than 40 lines of code and I hope integrating other systems is not more complex. However, there's not much feedback yet from the tracer community regarding the integration of other tracing systems.

**Comment by chenmudu** [comment]
Cool. I'm excited about this feature, and I've already started thinking about upgrading prometheus and client_java in my work to be associated with traces. 

I believe there will be some similar requirements in the near future. Please feel free to contact me when you start thinking about supporting other trace systems to add Exemplar. I'm very excited about this feature.

Thanks a lot.
