### ISSUE TITLE
Few issues around of OSGi-specific headers in manifests

### ISSUE THREAD

**Issue by bigmarvin** [prometheus/client_java#678]
I'm glad to see most artifacts of this project are packed as bundles, while I find some little glitches as listed below.

1. The artifacts of name `simpleclient_tracer_*` are not packed as bundles while other bundles like `simpleclient` itself import packages from them, which fails the startup of OSGi runtime.
2. The resolution of all imported packages is mandatory by default, but I doubt if every client would use every imported package every time. It's better to make them optional so the runtime knows which version of packages to look for when necessary and yet no startup is blocked.

**Comment by fstab** [comment]
Thanks for bringing this up. I've never looked into OSGI. Could you let me know a simple way to set up an OSGI project so that I could try this? Maybe I can turn it into an automated test.

**Comment by bigmarvin** [comment]
Here are some resources I planned to explore when available. Wish them help!

https://felix.apache.org/documentation/subprojects.html

**Comment by bigmarvin** [comment]
Thanks for addressing the 1st part! Let me try to illustrate the 2nd part as following.

The primary advantage of OSGi would be enabling same class of different versions co-work properly in one JVM. It's achieved by building the topology of versioned packages provided/required by bundles (called wiring).

During the start-up of OSGi runtime, it would check if this topology can be built or not. If some package required by some bundle is mandatory while no bundle can provide it, the start-up would fail. That's what I ran into in the first place. If the required package is optional, on the other hand, the start-up won't fail at this phase at least.

Optional resolution is handy when, say some classes under some target package integrate with many partners or so (e.g. some middleware integrating with all kinds of JMS implementation). However, as some client of this target package, it would only integrate with one or few partners in real world. If the packages of all partners are mandatorily required, the client must also include all package providers in the runtime for wiring to work but effectively most of them would be never used. If the resolution is optional, such massive inclusion wouldn't be necessary.

The drawback would be, however, if the packages of some partner **in use** are absent, e.g. not provided by any bundle, the start-up would still fail when the client bundle tries to load some class using that partner in the target package. Though postponed from wiring phase to activating phase, this error is expected and can be fixed by including the provider of these missing classes (usually some artifact of the partner). OSGi runtime would always use the info of import-package instructions to locate qualified packages regardless of its resolution, mandatory or optional.

Based on what I know, optional imported packages are OK for bundles without any resources at runtime (e.g. no OSGi service), because they don't really load any class. The client bundle is responsible to load and use classes it requires, together with its dependencies, so it can make some packages mandatorily required by itself.

Finally, it's correct to test every change, and this change can be tested by running OSGi runtime with some predefined combinations of artifacts, to make sure some regular use scenarios are supported. However, this isn't trivial as you may have tried.

Wish it help!

**Comment by hdost** [comment]
Having had some work with OSGi  in the past (granted it's been a few years now), and from your explanation I am curious why the focus is on these particular libraries for the second part because as far as I can tell all them would be useless without the OpenTelemetry APIs so the bundles upstream of this, so the ones depending on `simpleclient_tracer_otel*` should make them optional and in fact these libraries. That would fix your issue with providing them wouldn't it?
A: Some App
B: One of the Simple Client Tracer Libs
C: OpenTelemetry Lib
A ----(optional) ----> B ---(mandatory)---> C
"A" should be able to start up no problem without it, no?

**Comment by iskandergaba** [comment]
Any progress on this issue?

**Comment by fstab** [comment]
Should be fixed by #790.
