### ISSUE TITLE
Build failures with Java 17

### ISSUE THREAD

**Issue by dhoard** [prometheus/client_java#697]
**Description**

Java 17 no longer supports a Java 1.6 source/compile target

**Background**

`client_java`, as well as other Prometheus projects, have maintained Java 1.6 compatibility because of legacy application support.

Java 17 no longer supports a Java 1.6 as a source/compile target

```
[ERROR] Source option 6 is no longer supported. Use 7 or later.
[ERROR] Target option 6 is no longer supported. Use 7 or later.
```

**Impact/Resolution**

Java 11 is required to build `client_java`.

**Comment by fstab** [comment]
Azul offers support for Java 6 until December 2026 ([wikipedia](https://en.wikipedia.org/wiki/Java_version_history)), and there are people who have to run legacy Java 6 applications.

So, if the choice is to drop Java 6 support or to require `client_java` developers to use Java 11, I'd vote for the latter. Note that `client_java` runs fine with Java 17, so this is not an incompatibility for users of `client_java`, just for developers who want to compile `client_java` from source.

**Comment by dhoard** [comment]
I am not proposing either but wanted to call out the issue for future developers/contributors.

**Comment by dhoard** [comment]
Closing. Will not be resolved until we drop Java 6 support.
