### ISSUE TITLE
Performance issues 

### ISSUE THREAD

**Issue by queenns** [prometheus/client_java#701]
1.arthas
[arthas@43073]$ trace io.prometheus.client.exporter.common.TextFormat write004 -skipJDKMethod false
Press Q or Ctrl+C to abort.
Affect(class count: 1 , method count: 1) cost in **588 ms**, listenerId: 8
`---ts=2021-09-24 15:51:11;thread_name=XNIO-1 task-12;id=25d;is_daemon=false;priority=5;TCCL=org.springframework.boot.loader.LaunchedURLClassLoader@5fe1ce85
    `---[861.656614ms] io.prometheus.client.exporter.common.TextFormat:write004()
        +---[min=8.43E-4ms,max=0.002575ms,total=0.049649ms,count=36] java.util.Enumeration:hasMoreElements() #21
        +---[min=0.001032ms,max=643.767212ms,total=**649.867232ms**,count=35] java.util.Enumeration:nextElement() #22
        +---[min=7.26E-4ms,max=0.004105ms,total=0.046336ms,count=35] java.io.Writer:write() #23
        +---[min=7.51E-4ms,max=0.004264ms,total=0.042369ms,count=35] java.io.Writer:write() #24
        +---[min=7.17E-4ms,max=0.001895ms,total=0.036536ms,count=35] java.io.Writer:write() #25
        +---[min=0.001386ms,max=0.022203ms,total=0.31047ms,count=35] io.prometheus.client.exporter.common.TextFormat:writeEscapedHelp() #26
        +---[min=6.73E-4ms,max=0.001718ms,total=0.036091ms,count=35] java.io.Writer:write() #27
        +---[min=7.19E-4ms,max=0.001685ms,total=0.039582ms,count=35] java.io.Writer:write() #29
        +---[min=7.07E-4ms,max=0.011341ms,total=0.048119ms,count=35] java.io.Writer:write() #30
        +---[min=7.07E-4ms,max=0.0015ms,total=0.037023ms,count=35] java.io.Writer:write() #31
        +---[min=0.001132ms,max=0.014737ms,total=0.080013ms,count=35] io.prometheus.client.exporter.common.TextFormat:typeString() #32
        +---[min=7.3E-4ms,max=0.00795ms,total=0.045281ms,count=35] java.io.Writer:write() #32
        +---[min=7.16E-4ms,max=0.001316ms,total=0.036039ms,count=35] java.io.Writer:write() #33
        +---[min=8.91E-4ms,max=0.014068ms,total=0.061959ms,count=35] java.util.List:iterator() #35
        +---[min=7.08E-4ms,max=0.02596ms,total=2.41381ms,count=1981] java.util.Iterator:hasNext() #35
        +---[min=7.12E-4ms,max=0.014521ms,total=2.258357ms,count=1946] java.util.Iterator:next() #35
        +---[min=6.92E-4ms,max=0.116062ms,total=2.672124ms,count=1946] java.io.Writer:write() #36
        +---[min=6.77E-4ms,max=0.082178ms,total=2.390942ms,count=1946] java.util.List:size() #37
        +---[min=6.8E-4ms,max=0.024811ms,total=2.178406ms,count=1946] java.io.Writer:write() #38
        +---[min=6.68E-4ms,max=0.099623ms,total=9.867393ms,count=8814] java.util.List:size() #39
        +---[min=7.29E-4ms,max=0.145148ms,total=8.107956ms,count=6868] java.util.List:get() #40
        +---[min=6.89E-4ms,max=0.049363ms,total=8.103762ms,count=6868] java.io.Writer:write() #40
        +---[min=6.77E-4ms,max=0.098032ms,total=7.70286ms,count=6868] java.io.Writer:write() #41
        +---[min=7.33E-4ms,max=0.150485ms,total=8.54277ms,count=6868] java.util.List:get() #42
        +---[min=9.02E-4ms,max=0.29643ms,total=15.712317ms,count=6868] io.prometheus.client.exporter.common.TextFormat:writeEscapedLabelValue() #42
        +---[min=6.71E-4ms,max=1.452657ms,total=8.977985ms,count=6868] java.io.Writer:write() #43
        +---[min=6.93E-4ms,max=0.033116ms,total=2.24966ms,count=1946] java.io.Writer:write() #45
        +---[min=6.68E-4ms,max=0.01514ms,total=2.13224ms,count=1946] java.io.Writer:write() #47
        +---[min=8.51E-4ms,max=0.102075ms,total=3.746299ms,count=1946] io.prometheus.client.Collector:doubleToGoString() #48
        +---[min=6.85E-4ms,max=0.015345ms,total=2.20596ms,count=1946] java.io.Writer:write() #48
        `---[min=6.74E-4ms,max=0.023748ms,total=2.138488ms,count=1946] java.io.Writer:write() #53

2.curl "http://127.0.0.1:8080/actuator/prometheus" > prometheus.txt
cat prometheus.txt |grep -v "#"|wc -l
1954

Why is it so slow?

**Comment by queenns** [comment]
io.prometheus:simpleclient:0.8.1

**Comment by queenns** [comment]
`---ts=2021-09-24 17:15:11;thread_name=XNIO-1 task-9;id=24f;is_daemon=false;priority=5;TCCL=org.springframework.boot.loader.LaunchedURLClassLoader@5fe1ce85
    `---[825.326634ms] io.micrometer.prometheus.MicrometerCollector:collect()
        +---[0.003202ms] io.micrometer.prometheus.PrometheusConfig:descriptions() #64
        +---[0.001251ms] io.micrometer.core.instrument.Meter$Id:getDescription() #64
        `---[min=133.410758ms,max=144.572367ms,total=**825.153148ms**,count=6] **io.micrometer.prometheus.MicrometerCollector$Child:samples()** #6

**Comment by fstab** [comment]
I'm not exactly sure what your setup is. Are you calling `TextFormat.write004(Writer, Enumeration)` from Micrometer? Then I'd say there could be two reasons:
1. The writer is slow, because it's writing directly to a network connection.
2. The enumeration is slow, because it implicitly calls some callbacks on JMX or similar to get data.

Without further context it's hard to answer your question.

**Comment by queenns** [comment]
> I'm not exactly sure what your setup is. Are you calling `TextFormat.write004(Writer, Enumeration)` from Micrometer? Then I'd say there could be two reasons:
> 
> 1. The writer is slow, because it's writing directly to a network connection.
> 2. The enumeration is slow, because it implicitly calls some callbacks on JMX or similar to get data.
> 
> Without further context it's hard to answer your question.

**io.micrometer.prometheus.MicrometerCollector$Child:samples()** 

Online service tracking analysis
Custom service indicators are configured to methods based on aspects and using java annotations. When different methods are called, the indicators will increase.
When the response time of a prometheus server pull reaches **400-600ms**, my service has **1800 summary** indicators
After the online service was restarted, a prometheus server pull was within **100ms**. At that time, about **900** indicators were retrieved. The longer the time, the more methods are called, and the more indicators there are, the slower the response starts.
So my intuition tells me that the high probability is due to a large number of indicators and summary types, which ultimately lead to problems.
I don't know how to verify and finalize it. Based on the above judgment, I will take another look at my service.
