### ISSUE TITLE
io.prometheus.client.exporter.HTTPServer cannot export exemplar

### ISSUE THREAD

**Issue by yangtaoran** [prometheus/client_java#714]
io.prometheus.client.exporter.HTTPServer default use HTTPMetricHandler to handle Prometheus server pull request, the HTTPMetricHandler use TextFormat.writeFormat() method to write metrics data, but the TextFormat.writeFormat() don't write Sample's exemplar data. is there any plan to complete it?

**Comment by fstab** [comment]
Exemplars are only exposed if the request has the following header:
```
Accept: application/openmetrics-text; version=1.0.0; charset=utf-8
```
See

https://github.com/prometheus/client_java/blob/f2536bf2383f2e1393310ab51c25cdcabdfead13/simpleclient_httpserver/src/main/java/io/prometheus/client/exporter/HTTPServer.java#L93-L93

**Comment by yangtaoran** [comment]
> Exemplars are only exposed if the request has the following header:
> 
> ```
> Accept: application/openmetrics-text; version=1.0.0; charset=utf-8
> ```
> 
> See
> 
> https://github.com/prometheus/client_java/blob/f2536bf2383f2e1393310ab51c25cdcabdfead13/simpleclient_httpserver/src/main/java/io/prometheus/client/exporter/HTTPServer.java#L93-L93

it's feasible, thank you
