### ISSUE TITLE
How to close the quantile when I've already turned on the summary with quantile

### ISSUE THREAD

**Issue by cyzFC** [prometheus/client_java#715]
I found that the memory increases a lot because of Summary for some services, so I want to reduce memory usage by not calculating quantile. But I don't find some methods to make quantiles to empty in Summary.class. I also don't want to new another Summary because it can't save existing data. For examples, when the number of children.size() > 10000 in Summary, don't need to  calculating quantile and release the memory used to calculate quantile.

**Comment by fstab** [comment]
Summaries do not have quantiles by default. Quantiles are only calculated if you explicitly add them in the Summary builder. I'm not sure if I get your question correctly, but if you don't want quantiles for your Summary, just don't add them.

That being said, if you have more than 10k children for a single metric, that sounds like cardinality explosion. You should reconsider your label values and only use labels that result in a much smaller number of children.

**Comment by cyzFC** [comment]
> 默认情况下，摘要没有分位数。仅当您在“摘要”构建器中明确添加分位数时，才会计算分位数。我不确定我是否正确理解了您的问题，但如果您不想要摘要中的分位数，请不要添加它们。
> 
> 话虽如此，如果您有超过 1 万个孩子用于单个指标，这听起来像是基数爆炸。您应该重新考虑您的标签值，并且只使用导致孩子数量少得多的标签。

Maybe in the beginning I

**Comment by cyzFC** [comment]
> Summaries do not have quantiles by default. Quantiles are only calculated if you explicitly add them in the Summary builder. I'm not sure if I get your question correctly, but if you don't want quantiles for your Summary, just don't add them.
> 
> That being said, if you have more than 10k children for a single metric, that sounds like cardinality explosion. You should reconsider your label values and only use labels that result in a much smaller number of children.

I mean i wish some ways of dynamically controlling whether or not to calculate quantiles. When I find a lot of children, I hope just not to  calculate quantiles like a switch. I don't found this method to control in source code.
