### ISSUE TITLE
Failed to register Collector of type Gauge

### ISSUE THREAD

**Issue by menvol3** [prometheus/client_java#719]
Hi,
I'm trying to push some metrics from the java code using the java client to Prometheus Pushgateway, and currently, I’m stuck with the error bellow

`
Exception in thread "main" java.lang.IllegalArgumentException: Failed to register Collector of type Gauge: my_metric is already in use by another Collector of type Gauge
	at io.prometheus.client.CollectorRegistry.register(CollectorRegistry.java:57)
	at io.prometheus.client.SimpleCollector$Builder.register(SimpleCollector.java:261)
	at io.prometheus.client.SimpleCollector$Builder.register(SimpleCollector.java:253)
`

My idea is to push one metric but with dynamically changing labels and values.

```
    private static void sendMetricsToPushgateway(List<DeviceState> successChecks) {
        successChecks.forEach(deviceState -> {
            String email = .getEmail();
            String kind =  .getname();

            CollectorRegistry registry = new CollectorRegistry();
            Gauge requests = Gauge.build()
                .name("my_metric").help(" ")
                .labelNames("email", "name").register();
            requests.labels(email,name).set(0); // It will be dynamically changed. 

            PushGateway pushgateway = new PushGateway("127.0.0.1:9091");
            try {
                pushgateway.pushAdd(registry, "my_job");
            } catch (IOException e) {
                e.printStackTrace();
            }
        });
    }
```

Can someone please help to find a solution to this problem?

**Comment by fstab** [comment]
The call
```java
Gauge.build()
                .name("my_metric").help(" ")
                .labelNames("email", "name").register();
```
must be executed only once. Once the gauge is registered, you cannot register it a second time.

Move that call out of the `sendMetricsToPushgateway()` method and re-use the `requests` variable.

**Comment by menvol3** [comment]
Hi @fstab,

Thanks for the reply.

Since I’m new with something like Java coding, could you please send the full example of code, to be sure that it will work?
