### ISSUE TITLE
Make HTTPMetricHandler constructor public so people can use it in their own servers.

### ISSUE THREAD

**Issue by kurtostfeld** [prometheus/client_java#720]
I'd like to be able to run a standard JDK HttpServer, and customize + use that server for non-Prometheus related HTTP functionality and add the Prometheus Metrics handler like this:

```
            var listenAddress = new InetSocketAddress("localhost", 8080);
            var httpServer = HttpServer.create(listenAddress, 0);
            httpServer.createContext("/metrics", new HTTPMetricsHandler(CollectorRegistry.defaultRegistry));
            httpServer.start();
```

**Comment by dhoard** [comment]
@kurtostfeld I have created a PR to allow this functionality.

**Comment by fstab** [comment]
@dhoard wouldn't it be enough to just make the `HTTPMetricsHandler` constructor `public`?

**Comment by dhoard** [comment]
@fstab I have refactored `HTTPMetricsHandler` to have public constructors and added a test case in `TestHTTPServer`.

**Comment by fstab** [comment]
Thanks a lot! I merged it, it will become part of the next release.
