### ISSUE TITLE
Jakarta EE 9 compatibile version of BasicAuthHttpConnectionFactory

### ISSUE THREAD

**Issue by wilkinsona** [prometheus/client_java#721]
In Jakarata EE 9, the JAX-B API moves into the `jakarta.xml.bind` package space. Currently, `BasicAuthHttpConnectionFactory` uses `javax.xml.bind.DatatypeConverter` which is not available in a Jakarta EE 9 environment. If you only support Java 8 and later, switching to `java.util.Base64` would allow the same code to work with both Jakarta EE 8 and Jakarta EE 9.

**Comment by dhoard** [comment]
`client_java` maintains support from 1.6+. I have created a PR to use an embedded Base64 implement, https://github.com/prometheus/client_java/pull/698, which would remove the JAX-B API dependency, but it's hasn't been accepted.

Your only current option would be to fork and change the code.

**Comment by fstab** [comment]
@dhoard sorry for not getting back to your PR for so long. I'm reviewing it now.

**Comment by dhoard** [comment]
@wilkinsona This should be resolved with the merge of https://github.com/prometheus/client_java/pull/698

**Comment by wilkinsona** [comment]
I saw that, thank you. I'm not sure how the team manage their issue tracker so I'll leave the issue open for them to action as they see fit.

**Comment by fstab** [comment]
Thanks @dhoard! Closing this now :)
