### ISSUE TITLE
HTTPMetricHandler make constructor public

### ISSUE THREAD

**Issue by pokusak** [prometheus/client_java#723]
Class HTTPMetricHandler is currently public but constructors are not. I can create HTTPServer with my own HttpServer, but building it will start my server, thats may not be desirable. Therefore there is no way I can use only handler not server. 

Is there a reason why to prevent creations of instances of HTTPMetricHandler ? Please make constructors public.

**Comment by fstab** [comment]
This has been done with #722 and will be part of the next release.

**Comment by pokusak** [comment]
Sorry & thanks.
