### ISSUE TITLE
io.prometheus.parent:0.13.0 missing in repo1.maven.org

### ISSUE THREAD

**Issue by sverrehu** [prometheus/client_java#729]
There is no 0.13.0 directory in https://repo1.maven.org/maven2/io/prometheus/parent/, leading to build failures for the 0.13.0 versions of client_java.

**Comment by cryptoki** [comment]
➕1 same here. please update.

**Comment by fstab** [comment]
Sorry, I missed this. I released this. It should appear as soon as the Sonatype repository is synced.

**Comment by fstab** [comment]
It's there now https://repo.maven.apache.org/maven2/io/prometheus/simpleclient/0.13.0/.

**Comment by sverrehu** [comment]
Thanks for fixing this so promptly!
