### ISSUE TITLE
io.prometheus.client.vertx.MetricsHandler fails with NoSuchMethodError with vertx 4.2.1

### ISSUE THREAD

**Issue by kanibs** [prometheus/client_java#731]
Hi,

We have been using `io.prometheus.client.vertx.MetricsHandler` class for exposing our metrics endpoint, to be scraped by Prometheus

We upgraded the vertx to version 4.2.1, and post that we are getting and Error:

```
java.lang.NoSuchMethodError: io.vertx.core.http.HttpServerResponse.end(Lio/vertx/core/buffer/Buffer;)V
	at io.prometheus.client.vertx.MetricsHandler.handle(MetricsHandler.java:80)
```

The Prometheus client we are using is 0.13.0.

I was wondering if the Prometheus client is not compatible with this version of vertx? The dependency of Prometheus client that we are using are:

```
<dependency>
      <groupId>io.prometheus</groupId>
      <artifactId>simpleclient_hotspot</artifactId>
      <version>0.13.0</version>
    </dependency>

    <dependency>
      <groupId>io.prometheus</groupId>
      <artifactId>simpleclient_vertx</artifactId>
      <version>0.13.0</version>
    </dependency>
```

Any suggestion/response to this would be very helpful.

**Comment by fstab** [comment]
`client_java` is compiled against Vert.x 3, where the method `HttpServerResponse.end(Buffer)` returns `void`

https://github.com/eclipse-vertx/vert.x/blob/3.9/src/main/java/io/vertx/core/http/HttpServerResponse.java#L258

In Vert.x 4 the same method returns `Future<Void>`:

https://github.com/eclipse-vertx/vert.x/blob/4.1/src/main/java/io/vertx/core/http/HttpServerResponse.java#L248

Therefore you get the `NoSuchMethodError` at runtime: `client_java` is trying to call `void end(String chunk)` but that doesn't exist in Vert.x 4 (the return type is part of the method signature in Java).

The cleanest way to fix this would be to create a new `simpleclient_vertx4` module as a copy of `simpleclient_vertx` and compile that against Vert.x 4. If you have some time, please open a PR. This has been brought up a couple of times (for example #684) so it should be worthwhile fixing.

**Comment by kanibs** [comment]
Thank you @fstab for the clarification. I will surely try this out and create a PR

**Comment by Ritikj55** [comment]
Though using this dependency  
    <dependency>
      <groupId>io.prometheus</groupId>
      <artifactId>simpleclient_vertx4</artifactId>
      <version>0.16.0</version>
    </dependency>
    is not throwing error and after deploying the the application the appticaion is getting up but its not showing any data  in prometheous for the application
