### ISSUE TITLE
Both 'Content-Length: 0' and 'Transfer-Encoding: chunked' found when 'Accept-encoding: gzip' header not sent

### ISSUE THREAD

**Issue by ShaharTrasmitSecurity** [prometheus/client_java#732]
According to the http 1.1 spec:

> A sender MUST NOT send a Content-Length header field in any message
> that contains a Transfer-Encoding header field. (https://tools.ietf.org/html/rfc7230#section-3.3.2).

When testing prometheus metrics exposition, we are creating HTTPServer (in `io.prometheus.client.exporter.HTTPServer`) to expose metrics to, and sending HTTP requests to query the exposed metrics

When no metrics matches the query and an empty response should return, the following exception occur:

```
java.lang.IllegalArgumentException: Both 'Content-Length: 0' and 'Transfer-Encoding: chunked' found
```

After debugging, i found that when gzip encoding is not allowed (through `Accept-encoding` header), the response will always be encoded as chunked, and will contain the Content-Length: 0 header which conflicts with the HTTP 1.1 spec

** The issue occur only when the content length is 0

**Comment by dhoard** [comment]
@ShaharTrasmitSecurity I suspect it's in `HTTPMetricHandler` in this code...

```
            } else {
                String contentType = TextFormat.chooseContentType(t.getRequestHeaders().getFirst("Accept"));
                t.getResponseHeaders().set("Content-Type", contentType);
                Predicate<String> filter = sampleNameFilterSupplier == null ? null : sampleNameFilterSupplier.get();
                filter = SampleNameFilter.restrictToNamesEqualTo(filter, parseQuery(query));
                if (filter == null) {
                    TextFormat.writeFormat(contentType, osw, registry.metricFamilySamples());
                } else {
                    TextFormat.writeFormat(contentType, osw, registry.filteredMetricFamilySamples(filter));
                }
            }
```

A JUnit test will need to be written in `TestHTTPServer` to confirm.

**Comment by dhoard** [comment]
@ShaharTrasmitSecurity @fstab I have an initial branch of code https://github.com/dhoard/client_java/tree/issue_732 that appears to resolve the issue, but requires refactoring of `TestHttpServer` to be able to get HTTP response headers.

Implementing https://github.com/prometheus/client_java/issues/700 would make this type of test easier.

**Comment by dhoard** [comment]
@ShaharTrasmitSecurity PR https://github.com/prometheus/client_java/pull/738 has been merged to resolve the issue in the next release.
