### ISSUE TITLE
Log4j vulnerability *Now its 2.17*

### ISSUE THREAD

**Issue by desjardd1** [prometheus/client_java#737]
Just an update I know this client only uses what is installed but now 2.17 is released to fix ANOTHER issue. Thanks again for the work here all appreciate it. Just want to get this noted so I can tell security team we are addressing this :) 

Thanks everyone!

**Comment by fstab** [comment]
Yes, this time I was fast, I bumped log4j to 2.17 yesterday and released it https://github.com/prometheus/client_java/releases/tag/parent-0.14.1
