### ISSUE TITLE
MetricsServlet is overriding init(ServletConfig config) method without calling super.init(config)

### ISSUE THREAD

**Issue by s0ar** [prometheus/client_java#739]
Since version 0.12.0 the Servlet init is broken for further customization. The MetricsServlet overrides init(ServletConfig config) method from the from GenericServlet.class (javax.servlet-api) without calling super.init(config) as described in the JavaDoc.

> Called by the servlet container to indicate to a servlet that the servlet is being placed into service. See Servlet.init.
> This implementation stores the ServletConfig object it receives from the servlet container for later use. When overriding this form of the method, call super.init(config).

This leads to not calling the GenericServlet.init() method which might be used for further initialization code.
Thus, a call to super.init(servletConfig) in MetricsServlet.init method should fix this.

**Comment by fstab** [comment]
You mean like this? https://github.com/prometheus/client_java/pull/740

**Comment by s0ar** [comment]
That was fast, yes thanks!

**Comment by fstab** [comment]
Thanks for reporting, I merged it.
