### ISSUE TITLE
Proposal: Convert Project to Build With Gradle

### ISSUE THREAD

**Issue by hdost** [prometheus/client_java#742]
Allows for a more flexibility and can benefit even more from caching as we could also cache unchanged classes being built.
https://docs.gradle.org/current/userguide/build_cache.html#sec:build_cache_enable

Tasks 
- [ ] Preform initial conversion
- [ ] Ensure shading works properly
- [ ] Ensure different Java version builds work
- [ ] Ensure separation between unit and integration tests
- [ ] Release to Maven central
- [ ] Creating source Jars
- [ ] Creating Javadoc JARs
- [ ] Document How to build, release, test
- [ ] document how to use maven plugins
- [ ] Document how this maps to maven

**Comment by fstab** [comment]
I personally know Maven much better than Gradle, and there are some non-trivial configurations in the Maven build (shading, different Java versions, separation between unit and integration tests, release to Maven central, creating source and Javadoc JARs, ...). I fear I would need to spend significant time learning the new build system.

I don't have a strong opinion on the build system, but before we switch it would be good to have a good understanding how to work with the new system, so I don't need to spend too much time getting things done that I know how to do with Maven.

**Comment by hdost** [comment]
That makes perfect sense, i can create list of the areas of concern and ensure there's documentation. If you're not opposed I would propose creating the gradle files and once things are building as expected and documentation is in place remove the maven build files.

**Comment by hdost** [comment]
@fstab alright so I was working on some initial conversions and the first thing that comes up is compatibility of Java 6 and Java 8. One of the issues is that there's reliance on Otel for exemplars which technically isn't supported below Java 8. I know from the other thread about 1.0 that there's desire to maintain backwards compatibility. 
Right now IMO there's a potential conflict of support that isn't being resolved but it's only hidden. I personally don't have horse in the Java 6 race but I totally understand wanting to maintain that compatibility for Enterprises who aren't able to move at lightning pace. 
My proposal would be that for 1.0 that there's clearly defined separation of JDK6 and JDK 8+ 
This is quite easily done in gradle it just depends on how you might want to proceed.

**Comment by fstab** [comment]
I'm not sure about this. Would the Java 6 version and the Java 8+ version be different?

**Comment by hdost** [comment]
> I'm not sure about this. Would the Java 6 version and the Java 8+ version be different?

As mentioned above OpenTelemetry is built against JDK 8 which means that while as long as people don't include those they should hopefully be ok there's no official delineation for it. People just "have to know" 
There are other libraries which are supported here which likely have similar restrictions. I do see one case where jdk8 is specifically called out.

**Comment by fstab** [comment]
Support for Exemplars works as follows: If the OpenTelemetry tracing library is detected, you will get OTel Exemplars by default. If an application does not use the OpenTelemetry tracing library, you won't get OTel Exemplars.

This idea can be applied to other tracing libraries as well: In the future, we might detect other tracing libraries, and if such a library is present, we will use that to provide Exemplars.

In my view Java 6 applications are just like any other application. A Java 6 application will not use the OpenTelemetry tracing library, and thus `client_java` will not provide OTel Exemplars.

I don't see what separate Java 6 / Java 8+ distributions would do differently.

**Comment by jeuxdaily** [comment]
cordova has many problems
I don't why???

**Comment by hdost** [comment]
After some experimentation, this seems like it might be more work than it's worth due to the Java targeting, maybe if a some point java 6 get's dropped.
