### ISSUE TITLE
Proposal: Migrate from CircleCI to Github Actions

### ISSUE THREAD

**Issue by hdost** [prometheus/client_java#743]
The change seems relatively simple and there's no real benefit for this repo as it's a simple Linux java build anyhow.

Reference for How: https://docs.github.com/en/actions/migrating-to-github-actions/migrating-from-circleci-to-github-actions

**Comment by fstab** [comment]
Hi @hdost, my understanding is that all projects in the Prometheus organization are built with CircleCI ([client_golang](https://github.com/prometheus/client_golang), [client_python](https://github.com/prometheus/client_python), [client_ruby](https://github.com/prometheus/client_ruby), [prometheus](https://github.com/prometheus/prometheus), [alertmanager](https://github.com/prometheus/alertmanager/), [pushgateway](https://github.com/prometheus/pushgateway)), and they use a common [Prometheus ORB](https://circleci.com/developer/orbs/orb/prometheus/prometheus) for cross-project tasks like releasing Docker images (not needed by `client_java` though, as we release via Maven central). Some Projects have Github actions as well, but as far as I can see it's not for releasing, but just for tasks like running a Go linter.

Having the same built tool makes it easy for Prometheus community members to understand the build process for other Prometheus projects. There should be a good reason to switch to a different build tool `client_java` while all the others use CircleCI. I'm not really missing anything with CircleCI. Do you have anything specific in mind?

**Comment by hdost** [comment]
That's logical. Will close.
