### ISSUE TITLE
Distribution error

### ISSUE THREAD

**Issue by prepor** [prometheus/client_java#75]
Hello! I have this error while bootstrapping of dependencies:

```
Retrieving io/prometheus/simpleclient/0.0.9/simpleclient-0.0.9.pom from central
Could not transfer artifact io.prometheus:simpleclient:pom:0.0.9 from/to central (https://repo1.maven.org/maven2/): Checksum validation failed, expected 6b5cd46506ce0d2f5d90b659d1134c4f8cca5bbd but is 6e5340c298b8dfc29b1c52c1c54deae77a46d69d
```

**Comment by juliusv** [comment]
@brian-brazil Any idea what this could be?

**Comment by brian-brazil** [comment]
I can reproduce it, the release must have been incorrect. However the pom content looks correct.

**Comment by xperimental** [comment]
I also noticed the checksum error on 0.0.9. Additionally the pom files ([example](https://repo1.maven.org/maven2/io/prometheus/simpleclient_common/0.0.9/simpleclient_common-0.0.9.pom)) contain dependencies with variables (`${project.version}`) which seems to work with Maven (although it should create a warning) but causes problems with other tools.

**Comment by brian-brazil** [comment]
@xperimental Which tools does that cause problems with? gradle?

I'll undo that next release anyway.

**Comment by xperimental** [comment]
With this library I had the problem with sbt specifically. But I had other tools (for example gradle) complain as well (not with this library, but in the same situation). I first blamed the "bundle" packaging and tried to work around that, but then noticed that it could resolve the `simpleclient` artifact just fine and that led me to the conclusion that the variables are the cause (simpleclient only has a variable in the test scope).

**Comment by prepor** [comment]
I had the problem with leiningen (clojure)

**Comment by xperimental** [comment]
When do you plan to do the next release?

**Comment by brian-brazil** [comment]
I'm planning on next week, I want to put in support for the new pushgateway urls.

**Comment by xperimental** [comment]
Ok, this week would be great. Thanks.

**Comment by brian-brazil** [comment]
The release of 0.10.0 is staged at https://oss.sonatype.org/service/local/repositories/ioprometheus-1013/content/ if you'd like to verify it all works as expected. It seems fine to me, but it'd be good to confirm.

**Comment by xperimental** [comment]
Version from staging works from sbt.

**Comment by brian-brazil** [comment]
Thanks for testing, I'll push that out Monday morning then.

**Comment by brian-brazil** [comment]
0.0.10 released which fixes this.
