### ISSUE TITLE
jvm_memory_bytes_used{area="nonheap",} seems to have failed

### ISSUE THREAD

**Issue by wang007** [prometheus/client_java#752]
```
    private static List<ByteBuffer> bbs = new ArrayList<>();

    @RequestMapping("/oom")
    public String oom() {
        bbs.add(ByteBuffer.allocateDirect(1024 * 1024 * 200));
        bbs.add(ByteBuffer.allocate(1024 * 1024 * 200));
        return "ok";
    }
 ```
 when I request  this controller method from web in order to use  noheap memory, but jvm_memory_bytes_used{area="nonheap",} not growing consistently.
 

 env:
```
# TYPE jvm_info gauge
jvm_info{version="1.8.0_271-b09",vendor="Oracle Corporation",runtime="Java(TM) SE Runtime Environment",} 1.0
```

**Comment by fstab** [comment]
`client_java` does not do much here, it just takes the value from [MemoryMXBean.getNonHeapMemoryUsage()](https://cr.openjdk.java.net/~iris/se/11/latestSpec/api/java.management/java/lang/management/MemoryMXBean.html#getNonHeapMemoryUsage()).

Do you get correct values when accessing the `MemoryMXBean` directly, for example by attaching JDK Mission Control and looking at the MBean browser?

**Comment by wang007** [comment]
I understand that noheap only includes metaspace, codecache, and does not include application directly allocated out-of-heap memory.

**Comment by wang007** [comment]
It should be used jvm_buffer_pool_used_bytes metrics. 
thanks @fstab

**Comment by fstab** [comment]
On Linux you also have `process_virtual_memory_bytes` which shows the values from `/proc/self/status`. Maybe that helps.
