### ISSUE TITLE
How to change http server thread number

### ISSUE THREAD

**Issue by cutiechi** [prometheus/client_java#753]
<img width="980" alt="图片" src="https://user-images.githubusercontent.com/27606234/150086511-1ae121ee-f38f-4064-9094-e51c41a4ddb5.png">

**Comment by cutiechi** [comment]
#438

**Comment by fstab** [comment]
Reminds me of that comment here. We never followed up on that, but maybe it would be good to just do this.

https://github.com/prometheus/client_java/pull/704#issuecomment-939543271

**Comment by dhoard** [comment]
@fstab I agree.

I see two approaches...

1. Adding a new method like `withThreadCount(int minThreads, int maxThreads, long keepAliveMs)` to `HTTPServer.Builder` and force usage of a `ThreadPoolExecutor`.

2. Add a new method `withExecutorService(ExecutorService executorService)` to `HTTPServer.Builder`.

The defaults for both approaches (not calling the method) would mimic the current behavior.

I would lean toward approach 2.

**Comment by fstab** [comment]
+1 for approach 2.

**Comment by dhoard** [comment]
Code implementation in PR https://github.com/prometheus/client_java/pull/756

**Comment by fstab** [comment]
Closing this as the PR is merged.
