### ISSUE TITLE
why there is no convenient api to calculate average value of histogram

### ISSUE THREAD

**Issue by WestFarmer** [prometheus/client_java#764]

**Comment by hdost** [comment]
GIven that the client is used to expose metrics for calculation in Prometheus I am not sure I see what the use case would be.

**Comment by fstab** [comment]
From the [Prometheus documentation](https://prometheus.io/docs/practices/histograms/):
> To calculate the average request duration during the last 5 minutes from a histogram or summary called http_request_duration_seconds, use the following expression:
  ```
  rate(http_request_duration_seconds_sum[5m])
  /
  rate(http_request_duration_seconds_count[5m])
  ```

You are supposed to run this query in the Prometheus server, not in the metric library.
