### ISSUE TITLE
How to create commons labels?

### ISSUE THREAD

**Issue by mmaico** [prometheus/client_java#772]
I have several metrics on my system and i would like to put a default label on all of they one. I need to put the cluster where the machines is running, but i haven't found a way to do that.

Is it possible to do this using this lib?

**Comment by bjung82** [comment]
This  kind of labels could also be added during the scrape, e.g. like the Prometheus operator on Kubernetes does for namespace names etc. You can supply this info in the scrape config, no need emit/add this label in the /metrics endpoint itself.Am 30.03.2022 23:59 schrieb Marcelo Maico ***@***.***>:
I have several metrics on my system and i would like to put a default label on all of they one. I need to put the cluster where the machines is running, but i haven't found a way to do that.
Is it possible to do this using this lib?

**Comment by fstab** [comment]
Interesting that you are bringing this up. We have a monthly Prometheus dev summit (see our [public calendar](https://calendar.google.com/calendar/u/0/embed?src=prometheus.io_bdf9qgm081nrd0fe32g3olsld0@group.calendar.google.com)), and supporting common labels in the client libraries is on the agenda for the next one on 28 April. I would like to prepare a proposal together with @csmarchbanks (maintainer of the Python client library), so your input is very welcome.

As of now, there is no explicit support for common labels in `client_java`. Without explicit support, you could do a couple of things:

1. Add default labels explicitly
   ```java
    public static String[] labelNames(String... names) {
        // return an array containing the names and the default label names
    }
    public static String[] labelValues(String... values) {
        // return an array containing the values and the default label values
    }
    // example counter
    Counter counter = Counter.build()
        .name("test")
        .help("test counter")
        .labelNames(labelNames("myLabel")) // <-- this will add the default label names and "myLabel"
        .register();
    // example usage
    counter.labels(labelValues("myValue")).inc(); // <-- this will add the default label values and "myValue"
    ```
2. Create a wrapper
    ```java
    public static class CounterWithDefaultLabels {
        private final Counter counter;
        public Counter.Child labels(String... values) {
            return counter.labels(/* values + default values */);
        }
    }
    // now you can use CounterWithDefaultLabels just like a regular counter:
    counter.labels("myValue").inc();
    ```
I guess there are more options how you can do this.

I am curious what you think? Do the approaches above work for you, or would it be better to have direct support in the library? And if we implemented direct support in the library, how should the API look like?
