### ISSUE TITLE
found strange code, please review

### ISSUE THREAD

**Issue by GreenRover** [prometheus/client_java#792]
Makes this line of code sense for any one out there:

https://github.com/prometheus/client_java/blob/master/simpleclient_servlet_jakarta/src/main/java/io/prometheus/client/servlet/jakarta/Adapter.java#L61

**Comment by dhoard** [comment]
Bug. PR https://github.com/prometheus/client_java/pull/794 submitted.

**Comment by fstab** [comment]
Right, this is a typo. Thanks for fixing, I merged the fix.

**Comment by dhoard** [comment]
@GreenRover Thanks for your static review! Please close.
