### ISSUE TITLE
Failed to download dependencies while deploying

### ISSUE THREAD

**Issue by ne0h** [prometheus/client_java#81]
Hi,

I've downloaded the latest release and I am trying to deploy it. When I run `mvn clean deploy` i get this download error:

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project parent: Failed to deploy artifacts: Could not transfer artifact io.prometheus:parent:pom:0.0.10 from/to ossrh (https://oss.sonatype.org/service/local/staging/deploy/maven2/): Failed to transfer file: https://oss.sonatype.org/service/local/staging/deploy/maven2/io/prometheus/parent/0.0.10/parent-0.0.10.pom. Return code is: 401, ReasonPhrase:Unauthorized. -> [Help 1]`

What can I do here?

Thanks in advance!
Max

**Comment by brian-brazil** [comment]
Only the maintainers of client_java (i.e. me) can do a release and deploy. What you want is `mvn clean package`, or use the existing packages from the central repository. http://www.boxever.com/easy-java-instrumentation-with-prometheus has an example pom for an older version.

**Comment by ne0h** [comment]
Thank you, this blog post looks really good!

Now I have a "new" error:
`java.lang.NoClassDefFoundError: io/prometheus/client/Metrics$MetricFamily
	at io.prometheus.client.metrics.Counter$Builder.build(Counter.java:240)`

**Comment by brian-brazil** [comment]
I think you're mixing the original and simple client. You should only use the `simpleclient` modules.

**Comment by ne0h** [comment]
Oh cool, it works. Thank you!
