### ISSUE TITLE
The  function of  writeFormat() in TextFormat.class  has a small flaw

### ISSUE THREAD

**Issue by Bo-Qiu** [prometheus/client_java#817]
There is a redundant comma in the output，E.g：

call_total{monitor_ip="127.0.0.1",host_ip="127.0.0.1", env="qa",} 300.0

`if (sample.labelNames.size() > 0) {
          writer.write('{');
          for (int i = 0; i < sample.labelNames.size(); ++i) {
            writer.write(sample.labelNames.get(i));
            writer.write("=\"");
            writeEscapedLabelValue(writer, sample.labelValues.get(i));
            writer.write("\",");
          }
          writer.write('}');
        }`

**Comment by Bo-Qiu** [comment]
I'll fix it and create a pr.

**Comment by dhoard** [comment]
@Bo-Qiu this has come up a few times and the maintainers have chosen not to fix it.

https://github.com/prometheus/client_java/issues/210
https://github.com/prometheus/client_java/issues/262
https://github.com/prometheus/client_java/issues/351
https://github.com/prometheus/client_java/issues/675

Per @fstab 

> The trailing comma is intentional in the Prometheus text format. Quote from https://prometheus.io/docs/prometheus/latest/querying/operators/:
> 
> > label list is a list of unquoted labels that may include a trailing comma, i.e. both `(label1, label2)` and `(label1, label2,)` are valid syntax.
> 
> The new [OpenMetrics](https://openmetrics.io/) format does not have a trailing comma, so if you get your metrics with the following `Accept:` header you won't see that comma:
> 
> ```
> curl -H 'Accept: application/openmetrics-text; version=1.0.0; charset=utf-8' http://localhost:9999/metrics
> ```

... `may include` is not `must include`... so not sure why there has been pushback on a change.

**Comment by Bo-Qiu** [comment]
I get it, thx.
