### ISSUE TITLE
Error messages from pushgateway are swallowed.

### ISSUE THREAD

**Issue by beorn7** [prometheus/client_java#82]
https://github.com/prometheus/client_java/blob/master/simpleclient_pushgateway/src/main/java/io/prometheus/client/exporter/PushGateway.java#L272-L274 only reports the URL and the status code in case of an error pushing to pushgateway. However, the body does contain valuable information about the reason for the error. The error message should be reported, too.

**Comment by brian-brazil** [comment]
Further investigation indicates that if there's status code that's >400 then the http libraries that come with Java will throw an exception with no way to workaround that when you try to find out more about what happened.

Thus this is unfortunately not possible with the java client, unless I'm missing something.
