### ISSUE TITLE
downloadable  jar files 

### ISSUE THREAD

**Issue by zmf0507** [prometheus/client_java#821]
@fstab @dhoard can you tell me from where can I get the latest jar files for this java client? Thanks

**Comment by dhoard** [comment]
The latest release jars can be downloaded from the release page https://github.com/prometheus/client_java/releases), or a Maven repository (https://mvnrepository.com/artifact/io.prometheus/simpleclient)

For the latest unreleased code, you will need to clone `main` and build. Keep in mind that the latest unreleased code is always subject to change.

**Comment by leocb** [comment]
Hi! Am I missing something? I can't find the `jar` files in the releases page at all.

**Comment by zeitlinger** [comment]
I don't think we ever had the jar files attached in the release page. Please use maven or gradle: https://prometheus.github.io/client_java/getting-started/quickstart/
