### ISSUE TITLE
OpenMetrics Version

### ISSUE THREAD

**Issue by muzammil786** [prometheus/client_java#870]
What version of the OpenMetrics standard is followed in the latest release of this library?
Is there a documentation where the previous library versions can be checked against the version of the OpenMetrics standard?

**Comment by fstab** [comment]
The OpenMetrics support did not change, this should still be compliant with https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md, except that we allow Exemplars on all metric types, see [Prometheus Dev Summit decision on 2022-11-10](https://docs.google.com/document/d/11LC3wJcVk00l8w5P3oLQ-m3Y37iom6INAMEu2ZAGIIE/edit).

If you notice any difference please open an issue, this would likely be a bug.

**Comment by muzammil786** [comment]
Thanks @fstab . 
Can you confirm which version of the standard the library is compatible with?

**Comment by fstab** [comment]
Content-Type is "application/openmetrics-text; version=1.0.0; charset=utf-8".

https://github.com/prometheus/client_java/blob/586c2f9e4c62553eb157c82b292377521375f554/prometheus-metrics-exposition-formats/src/main/java/io/prometheus/metrics/expositionformats/OpenMetricsTextFormatWriter.java#L38C47-L38C107

Does that answer your question?

**Comment by muzammil786** [comment]
Yes, that will work. Thank you. 
I noticed that this file was only checked in version 1.0.x. Does it mean the previous versions did not specify the standard?

**Comment by fstab** [comment]
No, the reason why the file is new is that we now have different files for Prometheus text format and for OpenMetrics format. Previously both exposition formats were implemented in the same Java class. However, this is just restructuring of the code, the exposition format itself didn't change.

**Comment by muzammil786** [comment]
Thanks a lot for your explanation.
