### ISSUE TITLE
Support for java 21 virtual thread model

### ISSUE THREAD

**Issue by jkvargas** [prometheus/client_java#885]
Its more a question than an issue.
Do we have support for that?
Thanks.

**Comment by fstab** [comment]
This is a very generic question :). What would you like to see?

**Comment by jkvargas** [comment]
hey @fstab,
So, I was interested on jvm_threads_current, jvm_threads_state and jvm_threads_peak for virtual threads.
Or does it only analyze platform threads?

**Comment by fstab** [comment]
You can see here where the metrics are coming from. If there's anything that needs to be adapted for Java 21 please let me know. https://github.com/prometheus/client_java/blob/main/prometheus-metrics-instrumentation-jvm/src/main/java/io/prometheus/metrics/instrumentation/jvm/JvmThreadsMetrics.java#L76
