### ISSUE TITLE
Summary DataPoint SlidingWindow only uses 'current' slice, resulting in periodic NaN values

### ISSUE THREAD

**Issue by yrn1** [prometheus/client_java#894]
In io.prometheus.metrics.core.metrics.SlidingWindow, a ringBuffer of T is maintained. In case of Summary, T is CKMSQuantiles. But this ringBuffer is never actually fully used: only the 'current' element of the buffer is ever used (all other methods are private):

```
public synchronized T current() {
    return rotate();
}

public synchronized void observe(double value) {
    observeFunction.accept(rotate(), value);
}
```

E.g. in Summary.DataPoint#makeQuantiles(), only quantileValues.current() is used:

```
for (int i = 0; i < getQuantiles().size(); i++) {
    CKMSQuantiles.Quantile quantile = getQuantiles().get(i);
    quantiles[i] = new Quantile(quantile.quantile, quantileValues.current().get(quantile.quantile));
}
```

When this current slice happens to be just rotated, then DataPoint.makeQuantiles() will result in a NaN value.
Isn't the purpose of having a SlidingWindow to the full window when calculating a value, instead of only using the current slice?

**Comment by fstab** [comment]
Good catch, thanks for the bug report. I'll fix it asap, hoping to find the time tomorrow.

**Comment by fstab** [comment]
I think the `observe()` function should be like this

```java
    public synchronized void observe(double value) {
        rotate();
        for (T t : ringBuffer) {
            observeFunction.accept(t, value);
        } 
```

but I want to write a unit test first, because there should definitely be a test.

**Comment by fstab** [comment]
Here's an explanation: Imagine you have maxAge of 5 minutes. Then you expect all observations to be present for 5 minutes. So if you query the current bucket, you want to get all observations between now and 5 minutes ago.

* The current bucket represents all observations within the last 5 minutes, i.e. all observations between now and 5 minutes ago.
* The current+1 bucket has all observations within the last 4 minutes. After the next rotate it will become the current bucket and contain all observations within the last 5 minutes.
* The current+2 bucket has all observations within the last 3 minutes. After 2 rotates it will become the current bucket and contain all observations within the last 5 minutes.
* ...

So you have to observe values in all buckets. Makes sense?

#896 has a fix.

**Comment by fstab** [comment]
Ah, I read your comment again and understand what you mean. Yes, the solution you are describing would work, but only if you could aggregate all buckets at scrape time. Aggregating Summaries is not possible, that's why it can't be implemented that way. We need to aggregate at observe time, not at scrape time.

**Comment by yrn1** [comment]
Ah, yes, got it.
