### ISSUE TITLE
Which is the Java 17 supported version ?

### ISSUE THREAD

**Issue by Shalaka1197** [prometheus/client_java#909]
Which is the Java 17 supported version ?

**Comment by fstab** [comment]
* All versions of `client_java` can be used with Java 17.
* If you want to compile `client_java` from source, you need `1.0.0` or higher, because previous versions were backwards compatible with Java 6 and Java 17 does not have Java 6 support.

**Comment by dhoard** [comment]
To add to @fstab's answer, the next Prometheus JMX Exporter, which will use `client_java` `1.0.x` has been indirectly tested on....

```
alibabadragonwell/dragonwell:17
amazoncorretto:17
antublue/openlogic-openjdk:17
azul/zulu-openjdk:17
bellsoft/liberica-openjdk-debian:17
bitnami/java:17
eclipse-temurin:17
eclipse-temurin:17-alpine
ghcr.io/graalvm/jdk:java17
ibm-semeru-runtimes:open-17-jdk-focal
konajdk/konajdk:17-tlinux
mcr.microsoft.com/openjdk/jdk:17-mariner
mcr.microsoft.com/openjdk/jdk:17-mariner-cm1
mcr.microsoft.com/openjdk/jdk:17-ubuntu
openjdk:17
registry.access.redhat.com/ubi8/openjdk-17-runtime:latest
sapmachine:17
```

**Comment by Shalaka1197** [comment]
I am using below version and project is running on java 17. please let me know still I need to upgrade it ? and Prometheus application also needs to upgraded ?  @fstab @dhoard 
     <dependency>
            <groupId>io.prometheus</groupId>
            <artifactId>simpleclient</artifactId>
            <version>0.6.0</version>
        </dependency>

**Comment by fstab** [comment]
No need to upgrade, `simpleclient` works for all Java versions >= 6, including Java 17 and newer.
