### ISSUE TITLE
Make client as an OSGI Bundle to facilitate integration

### ISSUE THREAD

**Issue by sebadiaz** [prometheus/client_java#92]
Make client as an OSGI Bundle to facilitate integration

It will be really upfull to integrate this client in a oOSGI bundle

Depending artifcats should be OSGI bundle too. 

I hope it will possible.

For the moment I m making my proper Client

**Comment by brian-brazil** [comment]
Did #68 not take care of this?

**Comment by sebadiaz** [comment]
right
