### ISSUE TITLE
Promethus Core Counter and Gauge Query

### ISSUE THREAD

**Issue by rinkigoyal** [prometheus/client_java#920]
I am trying to use promethus metric core latest version for exporting metrics. I have below queries:
a)While using  Gauge, it is missing dec function.
Is there any reason for not supporting this function ?
At this point, we can only increment or set the value. How to decrement the value for gauge?

b) What is reason for not exporting existing value like get() in Counter and Gauge similar to simple client API.

**Comment by fstab** [comment]
There is a `dec()` function. It's inherited from the `GaugeDataPoint` interface. `Gauge` implements that interface.

**Comment by fstab** [comment]
`get()` was really missing. I created #934.
