### ISSUE TITLE
Explicit Exception for Duplicate Labels during Scrape

### ISSUE THREAD

**Issue by fstab** [prometheus/client_java#942]
When a collector produces duplicate labels (same metric name, same label names, same label values) during scrape, `client_java` throws an IllegalArgumentException.

https://github.com/prometheus/client_java/blob/f1cc00a21dc458d2704c4775e88704df895ca875/prometheus-metrics-model/src/main/java/io/prometheus/metrics/model/snapshots/MetricSnapshot.java#L46

It would be better to have an explicit Exception for that so the collector can catch it. This would help with https://github.com/prometheus/jmx_exporter/issues/911#issuecomment-2032985025

**Comment by dhoard** [comment]
Looking at the code, `MetricSnapshot` has the `MetricMetadata` which could be added to the exception. This would provide more information about the configuration issue.
