### ISSUE TITLE
Add response body to error message when push gateway returns != 202

### ISSUE THREAD

**Issue by fedotxxl** [prometheus/client_java#95]
Please check this problem - https://github.com/prometheus/pushgateway/issues/68 - I don't have enough information to fix the problem.

I'm not java guru but it should be possible to read body in any case:
http://stackoverflow.com/questions/25011927/how-do-i-get-response-body-using-java-net-httpurlconnection-when-401-is-returne
http://stackoverflow.com/questions/613307/read-error-response-body-in-java

**Comment by brian-brazil** [comment]
This was previously discussed in #83, this is unfortunately not generally possible.
