### ISSUE TITLE
info required for compatible version with openjdk21

### ISSUE THREAD

**Issue by sahil3390** [prometheus/client_java#965]
Hello team,

Which version of Prometheus JVM Client is compatible with openjdk21?

Regards,
Sahil

**Comment by dhoard** [comment]
The latest 1.x.x versions have been tested with Java 21.

**Comment by fstab** [comment]
Thanks Doug. I also think the older 0.x versions are compatible. Java is very good with maintaining backwards compatibility. If you take a library that was compiled for Java 6 it should run with Java 21 without any issues.
