### ISSUE TITLE
[FeatureRequest] Add option to distinguish JVM metrics from multiple sources

### ISSUE THREAD

**Issue by penev-ff** [prometheus/client_java#986]
Hello, 

The JVM instrumentation module provides a variety of out-of-the-box JVM and process metrics.
This is very useful for monitoring the JVM characteristics.
I know that you can also register particular JVM metrics separately.

However, I would like to propose a feature that allows renaming the JVM metrics exposed by the `JvmMetrics` class, 
or at least an option to add a prefix/domain to the metrics name.

i.e. `jvm_threads_current` -> `com_org_jvm_threads_current`

This would be very useful for users who want to distinguish between the JVM metrics coming from multiple sources.

**Comment by dhoard** [comment]
@penev-ff can you elaborate/provide a more concrete use case this solves?

**Comment by penev-ff** [comment]
@dhoard 

A Kubernetes cluster with **multiple** Java-based microservices running in separate pods. 
Each pod hosts a Java process, and you are using a monitoring solution like [Dynatrace](https://docs.dynatrace.com/docs/shortlink/monitor-prometheus-metrics#annotate-prometheus-exporter-pods) to collect JVM metrics from all these processes. Dynatrace scrapes these metrics from endpoints exposed by the Java processes running inside the pods.

When identical metric names are used across different pods, it becomes challenging to distinguish which metrics belong to which pod or microservice in Dynatrace.

**Comment by dhoard** [comment]
@penev-ff I would consider adding a server-specific metric prefix specific to an application/pod anti-pattern.

_Typically_ within an observability platform, you should be able to see the source (server) of metrics.

Dynatrace captures the server name of the source (server) it scrapes. This should be available in the Dynatrace UI.

**Comment by penev-ff** [comment]
Thanks, @dhoard , for the input! I will consider this.
